### ISSUE TITLE
[Bug]: No camera data is transferred when creating the camera profile. fields remain empty.

### ISSUE THREAD

**Issue by Fersy2003** [gyroflow/gyroflow#100]
### Gyroflow version

1.0.0 rc1

### What operating system are you using?

Win11

### What GPU are you using?

RTX2080TI

### What happened?

no camera data is transferred when creating the camera profile. fields remain empty.

[____480p_4by3_960x720-60.00fps.zip](https://github.com/gyroflow/gyroflow/files/8010002/____480p_4by3_960x720-60.00fps.zip)

**Comment by AdrianEddy** [comment]
Duplicate of #94
