### ISSUE TITLE
[Feature request]: ArduPilot .bin log support

### ISSUE THREAD

**Issue by avsaase** [gyroflow/gyroflow#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be great if GF would natively support ArduPilot dataflash logs in .bin format. Various tools exist to convert logs to CSV format but it would be much nicer if GF could also perform this step.

By default, Ardupilot logs at too low rates to use for video stabilization but this can be increased to 400Hz I think.

Here is an example log: https://drive.google.com/file/d/10g0Smjz236A9_7Iz-2n8jfWaW1PZcLS7/view?usp=sharing

**Comment by AdrianEddy** [comment]
.bin log parser is now implemented as of https://github.com/AdrianEddy/telemetry-parser/commit/8f2d3b582f02260e2d37c664f7524dd39be60d85 and 8320ff81c49d2939dd6cff208609a374a18fbb66
Code here: https://github.com/AdrianEddy/telemetry-parser/blob/master/src/ardupilot/bin.rs
It also reads quaternions stored in the log files, set `Integration method` to `None` to use them directly.
