### ISSUE TITLE
Adaptive zoom doesn't work properly with some lens profiles

### ISSUE THREAD

**Issue by Seba112PL** [gyroflow/gyroflow#103]
### Gyroflow version

1.0

### What operating system are you using?

Windows 10

### What happened?

When using gyroflow 1.0 and when changing output resolution of file it changes safe area causing it to zoom too much or too little (showing egdes) despite using dynamic croping

It is happening on Insta 360 go2 and runcam 5 orange using dynamic crop. Propably it is a problem on more cameras

![720](https://user-images.githubusercontent.com/81588853/152684524-6f0547de-698c-4e83-b1a4-480b29bb7583.png)
![1440](https://user-images.githubusercontent.com/81588853/152684528-6f24b5d5-9dbc-446a-939a-aae5fe802501.png)
![2668](https://user-images.githubusercontent.com/81588853/152684534-14989c55-22b1-414a-bb79-3378ee68569b.png)

**Comment by redstar01** [comment]
Hi! Tested on BetaFPV SMO 4K camera and got the same behavior

**Comment by Seba112PL** [comment]
Hero 6. Same thing

![7202](https://user-images.githubusercontent.com/81588853/152839120-179d72d4-31ad-458b-a560-87d4ed637ce4.png)
![1520](https://user-images.githubusercontent.com/81588853/152839134-643693f3-e932-4819-8d9d-4eeaf422ca37.png)
![2302](https://user-images.githubusercontent.com/81588853/152839151-b2d54cc0-d002-4880-ac08-ea6004cb4c2a.png)

**Comment by Seba112PL** [comment]
Hero 7. same thing

![720](https://user-images.githubusercontent.com/81588853/152880230-0654e5d8-ee90-473c-8b85-662771934339.png)
![1080](https://user-images.githubusercontent.com/81588853/152880234-e4615c10-3dd9-4080-931a-2f51d535e3e0.png)
![1440](https://user-images.githubusercontent.com/81588853/152880235-68b452b5-22ff-4d5b-86a7-b532b3f36b3e.png)
g

**Comment by redstar01** [comment]
#113 #110

**Comment by AdrianEddy** [comment]
> Not sure but it seems not related to lens profiles, same cases #113 #110. I guess the problem is more general

these are two different issues, we'll fix both

**Comment by AdrianEddy** [comment]
it also happens with this lens profile
[Panasonic_BGH1_Laowa7.5mm_3840x2160_16by9.json.zip](https://github.com/gyroflow/gyroflow/files/8027127/Panasonic_BGH1_Laowa7.5mm_3840x2160_16by9.json.zip)

**Comment by marcroe** [comment]
I think I know why this is happening. The border of the image frame is approximated/interpolated with a few points that are determined using undistort operation. The "grid" for interpolation is not dense enough for those very curved profiles (insta360). But I am a bit surprised why this happens with GoPro footage. I have not experienced this. There might be another issue that's linked to the FOV slider

**Comment by AdrianEddy** [comment]
That Hero 7 lens profile is definitely wrong, I would just ignore that one. Also the Hero6 comment was about changing the output resolution and that's fixed too. 

So the remaining issue is with Insta360 lens profiles, and that BGH1 one I posted.
I'm also sometimes seeing tiny black borders on sharp moves in certain videos, something is not entirely accurate there

**Comment by marcroe** [comment]
Ok, great. then it's definitely the interpolation of the frame border that's causing it.
Will look into it.

**Comment by mycosd** [comment]
I've tested it with #201 and it doesn't appear to let the safe area go outside the video, like the default FOV estimator. However it isn't correct either. The problem is, the boundary polygon of the go2 lens isn't continous, it has spots in it, which both estimation processes don't expect at all
![grafik](https://user-images.githubusercontent.com/7397998/154857713-1c5c8362-dcfa-465f-941b-de1fb2f0f778.png)

**Comment by AdrianEddy** [comment]
This is no longer an issue for correct lens profiles
