### ISSUE TITLE
[Bug]: Missing Caddx Polar Nano preset

### ISSUE THREAD

**Issue by jesuslg123** [gyroflow/gyroflow#104]
### Gyroflow version

1.0.0-rc1

### What operating system are you using?

Mac OS 12.0.1

### What happened?

Hello,

On the latest version 1.0.0-rc1 Caddx Polar Nano preset is missing, which it was available already. I can see there are 2 different polar preset as well.

![image](https://user-images.githubusercontent.com/7817064/152694167-d4e9f6f6-43db-4b27-85be-0295fd8b9f17.png)

**Comment by AdrianEddy** [comment]
You mean it was present in 0.3.0? I don't see it here: https://github.com/ElvinC/gyroflow/tree/master/camera_presets/Caddx

**Comment by AdrianEddy** [comment]
Fixed in 1ac0da28ea582229ea324b39b8d2a661545d4303

**Comment by jesuslg123** [comment]
Great! Thanks I just realized it was in another fork and also on the dev branch https://github.com/ElvinC/gyroflow/pull/131 
To many changes but for great! Awesome work! Version 1 looks stunning!
