### ISSUE TITLE
[Bug]: Dynamic Cropping not working when exporting a vertical video

### ISSUE THREAD

**Issue by Emanuele-Spatola** [gyroflow/gyroflow#110]
### Gyroflow version

v1.0.0-rc1

### What operating system are you using?

Mac OS

### What GPU are you using?

Radeon Pro 460 

### What happened?

The dynamic cropping feature is not working as expected (black edeges are visible) when the export resolution has height bigger then width (eg. fullhd vertical):

<img width="1440" alt="Screenshot 2022-02-07 at 16 16 57" src="https://user-images.githubusercontent.com/5675600/152824853-974d37c3-c63d-47b8-b128-76660a08c26e.png">
.

**Comment by AdrianEddy** [comment]
Fixed in 0eb75f87a41e70594c234ea889ec73b758a8cd7f
