### ISSUE TITLE
[Bug]: UI issues : In multi-byte languages, the display lines will be misaligned.

### ISSUE THREAD

**Issue by inouekou** [gyroflow/gyroflow#120]
### Gyroflow version

v1.0.0-RC1 (gh169)

### What operating system are you using?

Windows 10

### What happened?

In multi-byte languages, the display lines will be misaligned.

![スクリーンショット 2022-02-08 125624_2](https://user-images.githubusercontent.com/12888924/152924594-3657c0a2-4c9e-4105-aa1a-00f520e39965.jpg)

**Comment by inouekou** [comment]
It is only in the left pane that the lines are misaligned.

![スクリーンショット 2022-02-08 144122](https://user-images.githubusercontent.com/12888924/152925518-ca90ffd5-6c2b-4551-9017-ff273984a681.jpg)

**Comment by AdrianEddy** [comment]
Should be fixed in this one: https://github.com/gyroflow/gyroflow/suites/5222869367/artifacts/160142556
