### ISSUE TITLE
[Feature request]: Please add support for Gopro Session 4

### ISSUE THREAD

**Issue by luchsus** [gyroflow/gyroflow#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

GoPro Session 4 has an Gyro, but no build in stabilization. I would love to stabilize with gyroflow.
Can you provide advice, how to stabilize those videos?

**Comment by ElvinC** [comment]
Based on current knowledge, the Hero 4 unfortunately doesn't log the motion data to the GPMF metadata track. from [GPMF-parser](https://github.com/gopro/gpmf-parser):

> GoPro HERO5, HERO6 and Fusion cameras have a GPMF track. HERO4 Black will have GPMF flight telemetry when attach to the GoPro Karma drone. All GoPro HERO4 onwards can have third party BlueTooth sensor adding GPMF data.

So I'm closing this unless you have some new info.
