### ISSUE TITLE
[Bug]: VCRUNTIME140_1.dll was not found ... can't run

### ISSUE THREAD

**Issue by Schweizer33** [gyroflow/gyroflow#122]
### Gyroflow version

v1.0.0-rc1

### What operating system are you using?

Windows 10 Home

### What happened?

I got this error multiple times when it was loading up.  I found this same driver in one of my other directories and so I copied it to the gyroflow directory and then the application loaded fine.

**Comment by AdrianEddy** [comment]
Next time install this: https://aka.ms/vs/17/release/vc_redist.x64.exe
It's in the README in system requirements section
