### ISSUE TITLE
Not opening DNxHR HQ

### ISSUE THREAD

**Issue by leitmanr** [gyroflow/gyroflow#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0-rc1(gh189)

### What operating system are you using?

Windows 10 Pro 21H2 19044.1466

### What GPU are you using?

EVGA RTX 3080ti FTW3

### What happened?

Cant import following formats

DNxHR HQX 10bit 422 footage
[EBU_DNxHR_HQX_10bit.zip](https://github.com/gyroflow/gyroflow/files/8025667/EBU_DNxHR_HQX_10bit.zip)

![image](https://user-images.githubusercontent.com/99039827/153031002-bb4fa775-badc-4b4a-8ebb-61e75bc17976.png)

DNxHR 444 10bit
[EBU_DNxHR_4444_10bit.zip](https://github.com/gyroflow/gyroflow/files/8025677/EBU_DNxHR_4444_10bit.zip)

![image](https://user-images.githubusercontent.com/99039827/153031206-a1545e74-5661-45c7-a705-84493f38d791.png)

DNxHR HQ 8bit 422
[EBU_DNxHR_HQ.zip](https://github.com/gyroflow/gyroflow/files/8025682/EBU_DNxHR_HQ.zip)

![image](https://user-images.githubusercontent.com/99039827/153031336-6126b51f-7c60-46b2-902d-da1d68ee4b95.png)

**Comment by AdrianEddy** [comment]
Fixed in latest dev build
