### ISSUE TITLE
Linux 1.0rc1 appimage missing features

### ISSUE THREAD

**Issue by eburrows** [gyroflow/gyroflow#134]
The Linux 1.0rc1 appimage is missing at least:
1. Video rotation adjustment under the "Video Information" pane. The pencil icon does not appear.
2. Export aspect ratio unlocking. The padlock icon does not appear.

Observed on:
Ubuntu 18.04
nVidia GTX 1080, with nvidia drivers (not noveau)
OpenCL using CUDA
Insta360 GO2 with updated firmware Pro-Wide source file

**Comment by AdrianEddy** [comment]
Do all other icons appear? can you post screenshot?

**Comment by eburrows** [comment]
Screenshot attached
![Gyroflow-missing-icons-issue134-1](https://user-images.githubusercontent.com/911817/153094787-2e7073c3-43de-468f-9ffa-36612acb0028.png)
.

**Comment by AdrianEddy** [comment]
ok, all icons are missing, I saw this already on some linux distros. Probably some dependency is missing, they are svg icons

**Comment by eburrows** [comment]
I installed the listed dependencies, and I don't see any obvious missing SVG-related packages from Apt. 

I can run the AppImage, but not the binary, as I have glibc6 2.27, not the required 2.28. Perhaps it is some dependency on Ubuntu 20. Unfortunately I can't run strace on the appimage, so I can't see what SVG libraries it's trying to load. I'll see if there's a way to get glibc6 2.28 available, or run it in a VM.

**Comment by eburrows** [comment]
When I run the appimage as root with strace, I can see it trying to load /usr/share/pixmaps/pencil.svg, but that's not on my system. I assume it's not in the appimage either.

**Comment by AdrianEddy** [comment]
It's also not our icons. Our icons are stored in binary as resource so they won't be loaded from the filesystem. The issue is probably with svg renderer so look for some shared library failing to load

**Comment by eburrows** [comment]
The only SVG library I see failing to load is plugins/imageformats/libqsvg.so.avx2.

$ grep -i svg strace.out | grep -v 'usr/share'
23734 writev(5, [{iov_base="X\0\0\0\0\0\0\0\302\r\0\0\0\0\0\0", iov_len=16}, {iov_base="<\t\25,\0\0\0\0\"\0\0\0\0\0\0\0\16\0\0\0\10\0\0\0libqsvgi"..., iov_len=72}], 2) = 88
23731 lstat("/tmp/.mount_Gyrofl8EOQ6s/plugins/iconengines/libqsvgicon.so",  <unfinished ...>
23731 openat(AT_FDCWD, "/tmp/.mount_Gyrofl8EOQ6s/plugins/iconengines/libqsvgicon.so", O_RDONLY|O_CLOEXEC <unfinished ...>
23734 writev(5, [{iov_base="X\0\0\0\0\0\0\0\337\r\0\0\0\0\0\0", iov_len=16}, {iov_base="\234\t\25,\0\0\0\0\36\0\0\0\0\0\0\0\n\0\0\0\10\0\0\0libqsvg."..., iov_len=72}], 2) = 88
23731 lstat("/tmp/.mount_Gyrofl8EOQ6s/plugins/imageformats/libqsvg.so",  <unfinished ...>
23731 openat(AT_FDCWD, "/tmp/.mount_Gyrofl8EOQ6s/plugins/imageformats/libqsvg.so", O_RDONLY|O_CLOEXEC <unfinished ...>
23731 openat(AT_FDCWD, "/tmp/.mount_Gyrofl8EOQ6s/plugins/imageformats/libqsvg.so.avx2", O_RDONLY|O_CLOEXEC <unfinished ...>
23731 access("/tmp/.mount_Gyrofl8EOQ6s/plugins/imageformats/libqsvg.so.avx2", F_OK <unfinished ...>
23731 openat(AT_FDCWD, "/tmp/.mount_Gyrofl8EOQ6s/plugins/imageformats/libqsvg.so", O_RDONLY|O_CLOEXEC <unfinished ...>
23731 openat(AT_FDCWD, "/tmp/.mount_Gyrofl8EOQ6s//lib/x86_64/libQt6Svg.so.6", O_RDONLY|O_CLOEXEC <unfinished ...>
23731 openat(AT_FDCWD, "/tmp/.mount_Gyrofl8EOQ6s//lib/libQt6Svg.so.6", O_RDONLY|O_CLOEXEC <unfinished ...>
23731 read(50, "Qt6Svg.so.6\n7f1565047000-7f15650"..., 1024) = 1024


$ cd /tmp/.mount_GyroflF0ZID7/
$ ls plugins/iconengines/libqsvgicon.so
plugins/iconengines/libqsvgicon.so
$ ls plugins/imageformats/libqsvg.so
plugins/imageformats/libqsvg.so
$ ls plugins/imageformats/libqsvg.so
plugins/imageformats/libqsvg.so
$ ls plugins/imageformats/libqsvg.so.avx2
ls: cannot access 'plugins/imageformats/libqsvg.so.avx2': No such file or directory
$ ls lib/x86_64/libQt6Svg.so.6
ls: cannot access 'lib/x86_64/libQt6Svg.so.6': No such file or directory
$ ls lib/libQt6Svg.so.6
lib/libQt6Svg.so.6

**Comment by schnupperm** [comment]
I have the same problem on kubuntu 20.04 LTS and 21.10 with the tar.gz version.
strace output is attached. 
[strace.gyroflow.gz](https://github.com/gyroflow/gyroflow/files/8056455/strace.gyroflow.gz)

**Comment by Entropy512** [comment]
Also happens for kubuntu 21.10 built from source, latest git master

It is interesting that @eburrows saw a load attempt for /usr/share/pixmaps/pencil.svg - it almost looks like something is attempting to load the icons from /usr/share/pixmaps instead of wherever they are embedded

`sudo ln -s ~adodd/gitrepos/gyroflow/resources/icons/svg/*.svg .` run in /usr/share/pixmaps will make the icons appear...  obviously NOT a valid solution.

Well most of the icons.  The file dialog is missing all icons so it's nearly impossible to use - just a white bar at the top.

**Comment by schnupperm** [comment]
build from todays source on kubutu 20.04. Still no icons, even with Entorpy512s soft link work around.

**Comment by pitts-mo** [comment]
I have also noticed open file dialogs do not appear to render correctly for me with linux appimages.
Is that symptom related to this issue?
-p

image is from v1.0.0-rc5 on lubuntu 20.04 w/intel cpu/gpu.

![Gyroflow-linux-appimage-v1 0 0-rc5-Open_file](https://user-images.githubusercontent.com/22757216/157444990-cd926c42-8193-4075-80ec-d7211e49c4b5.jpg)

**Comment by Entropy512** [comment]
Not just the appimages - also affects self-built on Kubuntu 21.10

**Comment by JoshuaNitschke** [comment]
I'm taking a look at this issue.

**Comment by JoshuaNitschke** [comment]
I made some progress, will try to finish it by next weekend.
![image](https://user-images.githubusercontent.com/33307206/180637809-a0a6572d-0b0d-4ba5-af46-2f7c8e623a9f.png)
