### ISSUE TITLE
Improve error message when permission is denied

### ISSUE THREAD

**Issue by ih8unot** [gyroflow/gyroflow#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

Latest

### What operating system are you using?

Windows 11

### What GPU are you using?

Geoforce 2070 Super

### What happened?

Error when attempting to export. Resolved by simple export to D:\
![error](https://user-images.githubusercontent.com/56354742/153095524-51dc59a2-703b-4b8d-a488-9d6633dc42a8.png)

**Comment by AdrianEddy** [comment]
![image](https://user-images.githubusercontent.com/3849067/153721871-b402d46b-8048-4cb3-8f4b-149c544ad8ec.png)

**Comment by AdrianEddy** [comment]
Fixed in 4aa9097f508ae0184f1fa6e483689532f1ba9644
