### ISSUE TITLE
vcpkg should be installed with disableMetrics

### ISSUE THREAD

**Issue by hexarch** [gyroflow/gyroflow#136]
Please install vcpkg with telemetry disable on file gyroflow/ext/install-deps-linux.sh:

./vcpkg/bootstrap-vcpkg.sh -disableMetrics

Output from the install:

> "Downloading vcpkg-glibc...
> Telemetry
> ---------
> vcpkg collects usage data in order to help us improve your experience.
> The data collected by Microsoft is anonymous.
> You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
> passing --disable-metrics to vcpkg on the command line,
> or by setting the VCPKG_DISABLE_METRICS environment variable.
> 
> Read more about vcpkg telemetry at docs/about/privacy.md"

**Comment by AdrianEddy** [comment]
Thanks, done in a77886ee710a03ff07c4ad1ab9987dec3b7fda20
