### ISSUE TITLE
Added angle setting for accelerometer.

### ISSUE THREAD

**Issue by inouekou** [gyroflow/gyroflow#138]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

When the gyro and accelerometer are separated, as in the GoPro HERO6, the Rock Horizon cannot be used when shooting in UMMA style.
It would be nice to be able to set the accelerometer angle separately from the gyro angle.

**Comment by ElvinC** [comment]
For now you can use this tool: https://jaromeyer.github.io/rsgopatcher/

**Comment by AdrianEddy** [comment]
Done in eba7b94237341eecf149694892d0b5bd72374815
Right click on Rotation and check "Separate accelerometer rotation"
