### ISSUE TITLE
Audio Desync on Insta360 One R 1-Inch

### ISSUE THREAD

**Issue by KwadLife** [gyroflow/gyroflow#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0 RC2

### What operating system are you using?

Windows 10

### What GPU are you using?

Nvidia geforce GTX 1060

### What happened?

Exported Insta360 OneR 1 Inch edition footage and the Audio is heavily off. 
Used trim function so I am not sure if this is the same issue as bug #19

**Comment by B-nutze-RR** [comment]
There should be no issue if you don't use the IN trim or export the entire clip

**Comment by AdrianEddy** [comment]
Yes, it's the same as #19 , the amount of offset depends on  the size of audio packets (*groups of samples*), so it will vary between files
