### ISSUE TITLE
Wrong Imu orientation

### ISSUE THREAD

**Issue by loutwice** [gyroflow/gyroflow#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0-RC2

### What operating system are you using?

windows 10

### What GPU are you using?

nvidia 

### What happened?

when i change imu orientation x to X it changes y 
when i change y to Y it changes x

i have included my log file

![unknown (1)](https://user-images.githubusercontent.com/7931460/153206586-fe2dbeda-041a-4acb-a3de-d6b6cdf99177.png)
![unknown](https://user-images.githubusercontent.com/7931460/153206591-82459ddd-3b6f-4cc3-afa3-fb1239ebdda4.png)
[00002A02.XPD.gcsv.zip](https://github.com/gyroflow/gyroflow/files/8032923/00002A02.XPD.gcsv.zip)

**Comment by ElvinC** [comment]
This is expected behavoir, but elaborating in the docs might be useful:
If you have some `input`, then `Yxz` means:

* Take `y` from `input` and put in `x` of `output` (displayed)
* Take `-x` from `input` and put in `y` of `output`
* Take `-z` from `input` and put in `z` of `output`
