### ISSUE TITLE
It does not work good for sony rx0 II

### ISSUE THREAD

**Issue by xstrim1** [gyroflow/gyroflow#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0 rc2

### What operating system are you using?

windows 10

### What GPU are you using?

gtx1060 3gb

### What happened?

Hello. Can not make it work correctly for my camera sony rx0 II
There is catalyst browse from sony and it works good
attaching files from the link [https://drive.google.com/drive/folders/15o6NPRwIQJPPyke6ltnm6iK95tgkQclI?usp=sharing](url)
(Original files, calibration preset, calibration video, stabilization with catalist and Gyroflow)

**Comment by AdrianEddy** [comment]
It works fine, just set the Rolling shutter correction to 33ms and add a few milliseconds to the autosync points. Here's the working .gyroflow file:
[original C0352.zip](https://github.com/gyroflow/gyroflow/files/8033774/original.C0352.zip) (place next to your video and open the video in gyroflow, it'll ask you to load .gyroflow file)
