### ISSUE TITLE
Batch processing when loaded multiple video files

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#15]
This is separate from render queue, it would work with files that don't need autosync like GoPro and can use the same settings for all.

With render queue it will be possible to work on each file manually but then render them together

**Comment by Garban5** [comment]
Yeah! this is a good feature. I was used the CLI comand on de 0.3.0 version with a .bat file. 
Keep in mind that the new Reel v2, will have Batch export feature.
