### ISSUE TITLE
Not able to run exe file

### ISSUE THREAD

**Issue by Outboxfpv** [gyroflow/gyroflow#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.00

### What operating system are you using?

Windows 10 64 bit

### What GPU are you using?

Nvedia Quadro FX 4000

### What happened?

When I am running the gyro flow exe file iam getting this error message given below

**clgetkernelargingo could not be located in dynamic link library** #

### Relevant log output

```shell
clgetkernelargingo could not be located in dynamic link library
```

**Comment by ElvinC** [comment]
Is that the full copied error log, and are you sure it wasn't `clgetkernelarginfo` instead of `clgetkernelargingo`?

**Comment by Outboxfpv** [comment]
Tanks its solved. I had to install another graphics card driver
