### ISSUE TITLE
Improve `.gyroflow` file

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#156]
- [x] Include export parameters
- [ ] Include autosync parameters
- [x] When loading `.gyroflow` file, look for the same video filename in the same path, instead of trying to load video from full hardcoded path (for example when you move video file to another folder)
- [x] Implement loading this file purely in `core` (parse and load all parameters, useful for plugins). 
- [x] Maybe implement optional binary packed storage for the gyro data? the files can get pretty big, I imagine using simply `bincode` + base64 would reduce them significantly. We lose portability a bit here, but I think 99% users will use it with our code (either main program or plugins) anyway

**Comment by pitts-mo** [comment]
My thoughts:
-I utilize read only access on my source folders so specifying the export path for .gyroflow files is desired.
-It seems desirable to enhance default .gyroflow file naming to differentiate between "with" and basic .gyroflow files.

-I also imagine production environments would desire specifying full paths for all input and output. If a search feature is added to locate moved files then an option to disable this search feature may also be desirable.

-p

**Comment by AdrianEddy** [comment]
> * [x]  I utilize read only access on my source folders so specifying the export path for .gyroflow files is desired.

If it can't save the `.gyroflow` file in the video directory, it will ask you for new location

> * [ ]  It seems desirable to enhance default .gyroflow file naming to differentiate between "with" and basic .gyroflow files.

What's the use case? IMO it will create more problems that it solves. You can always look at the file size.

> * [x]  I also imagine production environments would desire specifying full paths for all input and output. If a search feature is added to locate moved files then an option to disable this search feature may also be desirable.

It always tries to load from absolute path first. Only if it's not found it falls back to searching in `.gyroflow` directory

**Comment by AdrianEddy** [comment]
Implemented in cec97ec1f750b5e85f4246034827fd0e854d4c7c
