### ISSUE TITLE
After changing preview resolution detected features are disappearing

### ISSUE THREAD

**Issue by Seba112PL** [gyroflow/gyroflow#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0 rc.2

### What operating system are you using?

Windows 10

### What happened?
![before](https://user-images.githubusercontent.com/81588853/153655575-24d73445-47dc-4d3e-87f1-572336c6d187.png)

After changing preview resolution detected features are disappearing
Before

After

![after](https://user-images.githubusercontent.com/81588853/153655653-c6cfcb2d-5eff-4f37-b3b9-e24a097903d4.png)

**Comment by AdrianEddy** [comment]
Fixed in af04c7b05497b0dbae029caa35c530e7a6a17038
