### ISSUE TITLE
For cameras that are making separate CSV files detect gyrofile using date of making that file

### ISSUE THREAD

**Issue by Seba112PL** [gyroflow/gyroflow#161]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Some cameras, for example runcam orange, are making seperate CSV file that have the same date/time of creation of that file as a video file. Gyroflow might autoselect that file based on that when importing file. Could be handy for now and maybe in the future when batch processing will be added

**Comment by AdrianEddy** [comment]
Dupliate of #70
