### ISSUE TITLE
Add some test video and data

### ISSUE THREAD

**Issue by hanabic** [gyroflow/gyroflow#165]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I don't have some camera in the supported list. But I hope to run gyroflow and evaluate perfermance.
So is there some tets video and data in the project?

**Comment by AdrianEddy** [comment]
Test clips were added to the README, link here: https://drive.google.com/drive/folders/1sbZiLN5-sv_sGul1E_DUOluB5OMHfySh?usp=sharing
