### ISSUE TITLE
Sony a6600 GyroData

### ISSUE THREAD

**Issue by apocalyp0sys** [gyroflow/gyroflow#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-rc2

### What operating system are you using?

Windows 10 20H2

### What happened?

Hello.

Sony a6600 is listed as a supported source for gyro data, but I dont think it exposes any gyro data at all. I tried recording several clips in different modes (XAVC S HD, XAVC S 4K 100Mbit, steady shot on/off, etc), Gyroflow can't detect any gyro data.  [telemetry-parser](https://github.com/AdrianEddy/telemetry-parser) gyro2bb outputs empty csv file with headers only.

Sony's Catalyst Browse aslo doesn't indicate any of my clips have gyro data.

My a6600 has latest firmware 1.10.

Maybe there is some specific recording mode that exposes gyro data? If no, perhaps a6600 should be remeved  from supported sources.

**Comment by AdrianEddy** [comment]
You're right, it doesn't have gyro data. I've heard Sony promised to include it in firmware update but that never happened. Removed from the list
