### ISSUE TITLE
Export drops one frame from the end of file

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#168]

**Comment by relaxgit** [comment]
maybe thats why my 59.94 fps footage wont be exactly 59.94 after rendering?

**Comment by AdrianEddy** [comment]
This is caused by the same framerate difference as in #181

**Comment by AdrianEddy** [comment]
Should be fixed now in https://gyroflow.xyz/devbuild/?autodownload please check @relaxgit

**Comment by AdrianEddy** [comment]
Fixed in 8d38a61c41f8556e7722271f252cc5825a401dd7 and 55e1fb8de7c698f5ede9d4c5dc31f8362a54b501
