### ISSUE TITLE
Add preview when dragging trim and move timeline when dragging trim to the edge of timeline

### ISSUE THREAD

**Issue by Seba112PL** [gyroflow/gyroflow#176]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I think it could be nice to add there features.

Preview while draging trim
![2022-02-13 09-21-18](https://user-images.githubusercontent.com/81588853/153745099-70a1bd2f-cbcf-49e1-8b3a-0006e3ab1623.gif)

Draging trim outside of timeline
![2022-02-13 09-21-45 (1)](https://user-images.githubusercontent.com/81588853/153745175-2e94b285-5d81-443f-b958-ffb9fc6c038b.gif)

**Comment by AdrianEddy** [comment]
Done in 7590704586409c2c2c9cbe3f21dcd76e8d6cfdb3
