### ISSUE TITLE
Previous frame not working 

### ISSUE THREAD

**Issue by Seba112PL** [gyroflow/gyroflow#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

rc3 gh257

### What operating system are you using?

Windows 10

### What happened?

Next frame is working fine but previous not.

![2022-02-13 09-36-14](https://user-images.githubusercontent.com/81588853/153745573-a052f7c0-7867-49be-b164-b5ff1f7880b2.gif)

**Comment by lukegluke** [comment]
Still the same in 1.0.1. Previous frame (left) works only couple frames, than stops, while long jump (cntrl+left) works better.

**Comment by AdrianEddy** [comment]
This is essentially the same as #296

**Comment by AdrianEddy** [comment]
Fixed in latest dev build
