### ISSUE TITLE
Gyroflow H264 Hero10 export drops frames in FinalCutPro M1 Air

### ISSUE THREAD

**Issue by B-nutze-RR** [gyroflow/gyroflow#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

RC3

### What operating system are you using?

Mac OS

### What GPU are you using?

M1 Air 

### What happened?

H264 95 Mbit/s 59.94 Gopro Hero 10 video exported from Gyroflow skips frames in Finalcut Pro playback .A RSgo export or the source Gopro file play fine in Finalcut Rro .
Attached video shows the issue in screen recording .

https://www.youtube.com/watch?v=9XNnV67FH8Y

reported from @BMSweb on discord.

<img width="1233" alt="M1_air_FCpro_dropp_frames_hero10" src="https://user-images.githubusercontent.com/49525731/153752881-b7b8d767-8098-4f39-9ed1-235c129098a5.png">

### Relevant log output

```shell
not provided yet
```

**Comment by AdrianEddy** [comment]
Should be fixed now in https://gyroflow.xyz/devbuild/?autodownload

**Comment by AdrianEddy** [comment]
Fixed in 55e1fb8de7c698f5ede9d4c5dc31f8362a54b501
