### ISSUE TITLE
MacBook Pro M1 perfomance drop on Hero 5 Session footage

### ISSUE THREAD

**Issue by nogod4me** [gyroflow/gyroflow#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0-rc3

### What operating system are you using?

macOS Monterey 12.2

### What GPU are you using?

Apple Silicon M1

### What happened?

Testing GF on my GoPro 5 Session with 2.7K 4:3 25FPS footage. After pressing Export first 7-10% of process runs pretty fast, then performance gradually slows till 1 frame per second. GPU encoding goes the same. I have to say that I use my own calibration preset for 2.7K 4by3 on Session 5. 
By the way GoPro Hero10 footage encodes amazingly fast. 
![Снимок экрана 2022-02-13 в 21 08 52](https://user-images.githubusercontent.com/99600621/153757069-a0a257bc-1801-41c2-8ea3-66392264718e.png)

https://user-images.githubusercontent.com/99600621/153757226-5de5c9d4-887c-41a1-be40-b8368b82c93f.mov

**Comment by nogod4me** [comment]
<img width="411" alt="Снимок экрана 2022-02-13 в 23 25 35" src="https://user-images.githubusercontent.com/99600621/153762641-cde87798-31f3-439e-8f1a-9bc9283472bc.png">
I can't even finish one video.

**Comment by AdrianEddy** [comment]
So it happens only with Hero 5 video? Can you upload it?

**Comment by Volus208** [comment]
I can confirm this also happens for me, Ubuntu 20.04 LTS with a Gopro Hero5 Session, and I tried every exporting setting. However I noticed that I can't use my GPU for rendering

**Comment by nogod4me** [comment]
<img width="411" alt="Снимок экрана 2022-02-14 в 06 23 07" src="https://user-images.githubusercontent.com/99600621/153779955-74ad12fb-7f21-4ff7-bcea-db0be5902925.png">

**Comment by nogod4me** [comment]
> 

Yes, Session 5 footage runs like this.

**Comment by nogod4me** [comment]
> I can confirm this also happens for me, Ubuntu 20.04 LTS with a Gopro Hero5 Session, and I tried every exporting setting. However I noticed that I can't use my GPU for rendering

CPU encoding works well?

**Comment by HenningSE** [comment]
I got the same problem with Gopro Hero5 Black footage on an Intel MacBook Pro.

**Comment by AdrianEddy** [comment]
This should be fixed in latest dev build https://github.com/gyroflow/gyroflow/suites/5296956914/artifacts/164310984

**Comment by AdrianEddy** [comment]
sorry apparently github failed to include it, here's fixed version: https://github.com/gyroflow/gyroflow/suites/5298111892/artifacts/164378495

**Comment by Volus208** [comment]
This dev build doesn't work on ubuntu, It starts exporting then says ffmpeg::Error(1668179713: Input changed)
I'm using an intel core i5 9400F and an Nvidia gtx 1050ti

**Comment by Volus208** [comment]
It seems to work after the third try, I think the beggining of the file was "corrupted", which happens often on the session 5

**Comment by HenningSE** [comment]
The fix is working for me. Thanks for you awesome work.

**Comment by AdrianEddy** [comment]
> This dev build doesn't work on ubuntu, It starts exporting then says ffmpeg::Error(1668179713: Input changed) I'm using an intel core i5 9400F and an Nvidia gtx 1050ti

can you send me a file which causes that error?

**Comment by AdrianEddy** [comment]
@Volus208 does it work with this version? https://gyroflow.xyz/devbuild/?autodownload

**Comment by nogod4me** [comment]
> @Volus208 does it work with this version? https://gyroflow.xyz/devbuild/?autodownload

For me now it works fast but there is such error at the end.. Result file is not playable. 
![Снимок экрана 2022-02-15 в 10 09 16](https://user-images.githubusercontent.com/99600621/153985416-6dbef7f7-9220-448d-b59f-0619243e198c.png)

**Comment by AdrianEddy** [comment]
fixed with latest dev build (gh274) https://gyroflow.xyz/devbuild/?autodownload

**Comment by nogod4me** [comment]
> fixed with latest dev build (gh274) https://gyroflow.xyz/devbuild/?autodownload

I just installed it from that link. Then I cut couple frames from the start and the end of file and it worked well.

**Comment by AdrianEddy** [comment]
Yes
