### ISSUE TITLE
SONY ZV-1 stabilization profile not available in Templates

### ISSUE THREAD

**Issue by LouloOWeB** [gyroflow/gyroflow#184]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hello

Thank you already for this superb post production stabilization software which is already working miracles on the GoPro for FPV Drone Flight!!!

I was attracted by the fact that certain cameras, including the SONY ZV-1, were among the compatible cameras.

Reason why I downloaded the RC2 then the RC3 recently, but without finding the profile of the SONY ZV-1 camera to my great regret.

I tried to create a profile myself, from a video of my SONY ZV-1 with an Analysis, but the result was 999 in red, therefore unusable.

Do you plan to release a SONY ZV-1 Profile soon, which takes into account the dyu Gyroscope Information of this device?

Thank you for your comeback.

LouloOWeB.

**Comment by AdrianEddy** [comment]
Profiles are created by the community, we don't own every possible camera out there. Creating a lens profile is really easy, please follow these steps: https://docs.gyroflow.xyz/guide/calibration/#creating-camera-preset and you should be able to create a lens profile for your camera in less than 10 minutes

**Comment by AdrianEddy** [comment]
[Sony ZV1 profiles.zip](https://github.com/gyroflow/gyroflow/files/8056374/Sony.ZV1.profiles.zip)
or you can try some of these
