### ISSUE TITLE
Unusable after RC2 on MacPro late 2013

### ISSUE THREAD

**Issue by Fabersa** [gyroflow/gyroflow#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0 rc3

### What operating system are you using?

MacOS 12.1

### What GPU are you using?

AMD FirePro D700 6gb

### What happened?

I'm trying to get rid of the wobbly video output achieved after 1:15 hours rendering of the RC1 but I've found video preview freeze in RC2 and the impossibility to render on the RC3. I'm forced to use the RC1 but I can't have any good results. The rendering on RC3 failed cause an HWUnknown issue on x264 codec instead I've set the x265 output.... Please help me!

**Comment by AdrianEddy** [comment]
what's the exact error message? did you try unchecking "Gpu decoding" under Advanced? what camera is your video file from?

**Comment by Fabersa** [comment]
![Schermata 2022-02-14 alle 09 47 49](https://user-images.githubusercontent.com/3049126/153831172-e6babe0e-3018-48eb-89ae-2228171d3590.png)

That's the error window after the GPU rendering, unchecking the GPU rendering it works (same RT) now I'm waiting for the results. The previews had lot of frame dropping and I can't judge if I've reached a good stabilization since for what I can see on the preview my video is still wobbly.

The origin file is from an Insta360 One-r 1"

**Comment by AdrianEddy** [comment]
Does it work in this build? https://gyroflow.xyz/devbuild/?autodownload
Can you confirm rc2 works, but rc3 doesn't?

**Comment by Fabersa** [comment]
GPU encoding no longer working after RC1

**Comment by AdrianEddy** [comment]
What's the error message?

**Comment by Fabersa** [comment]
as you can see on my previous attachment : An error occurred: FFmpeg error 542398533 Generic error in an external library
 etc

**Comment by AdrianEddy** [comment]
@Fabersa does it work after you disable "GPU decoding" under Advanced?
RC1 didn't support GPU encoding on mac at all - it was using CPU encoder (without showing gpu error)

**Comment by Fabersa** [comment]
Yes it works w/o GPU Encoding but it takes a life to encode a minute long clip....

**Comment by AdrianEddy** [comment]
Does this still happen in latest dev build?  https://gyroflow.xyz/devbuild/?autodownload

**Comment by Fabersa** [comment]
Now seems working again!
