### ISSUE TITLE
Sync offset should be extrapolated before the first sync point and after the last sync point

### ISSUE THREAD

**Issue by Aphobius** [gyroflow/gyroflow#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

Gyroflow v1.0.0-rc3

### What operating system are you using?

Windows 11

### What GPU are you using?

RTX 2070

### What happened?

Sync offset should be extrapolated before the first sync point and after the last sync point, without changing the interpolation between sync points.

The offset before the first sync point should have the same slope that is present between the first 2 sync points and the offset after the last sync point should have the same slope that is between the last 2 sync points.

Issue:
![sync slope](https://user-images.githubusercontent.com/61385283/153842198-268274d6-c8bc-4f96-9c95-e0ec75abdf9c.jpg)

**Comment by ElvinC** [comment]
Fixed in https://github.com/gyroflow/gyroflow/commit/5faf8f82095010785a527e24c715483fb68fd3a4
