### ISSUE TITLE
"FOV = 1" with double click on it

### ISSUE THREAD

**Issue by Hixx** [gyroflow/gyroflow#189]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Please make "FOV"-field to revert to "1" by double clicking on "FOV"-field.
This may be also done with some parameters to revert them back to defaults.

**Comment by ElvinC** [comment]
All sliders can be reset through right click. Is that fine?

**Comment by Hixx** [comment]
> All sliders can be reset through right click. Is that fine?
Yeah! Thanks!

**Comment by mycosd** [comment]
I would prefer double-click as well. Some other programs do ctrl+click reset, which is also easier then going through a menu

**Comment by ElvinC** [comment]
Added in https://github.com/gyroflow/gyroflow/pull/210

**Comment by Hixx** [comment]
Thank you very much!
