### ISSUE TITLE
Add transparency as background option

### ISSUE THREAD

**Issue by Janoz-NL** [gyroflow/gyroflow#194]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

It would be really nice to have a transparency option for the background. This probably isn't possible for x264 and x265 output, but if it would only work for PNG's it would be more than enough (although I read somewhere ProRes also has transparency options)

**Comment by relaxgit** [comment]
set a weird color as background, and chroma key in your editor

**Comment by Entropy512** [comment]
ProRes 4444 does support alpha, 422 does not.

**Comment by AdrianEddy** [comment]
Done in abb0fd509c6978a16d366f5cad555cfa2c843678
Use hex color code with alpha: `#AARRGGBB`, eg. `#00000000` or just `transparent`

Supported in PNG and ProRes 4444/4444XQ
Latest dev build: https://gyroflow.xyz/devbuild/?autodownload
