### ISSUE TITLE
sony rx0 II problem with audio after render

### ISSUE THREAD

**Issue by xstrim1** [gyroflow/gyroflow#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

rc3

### What operating system are you using?

win 10

### What happened?

![Resolve_Vabo7sz4kx](https://user-images.githubusercontent.com/99343216/154425274-6f9c02fb-c3c5-4b71-9161-c9a7f393ca41.jpg)
source:
[https://drive.google.com/drive/folders/1xekj6U3iEyhY1QP5bO60xj-k_SpVk83v?usp=sharing](url)

**Comment by AdrianEddy** [comment]
Thanks for the test file, this is tracked in #146
