### ISSUE TITLE
Logging by Android apps: 'unsupported file format' error

### ISSUE THREAD

**Issue by nikster89** [gyroflow/gyroflow#205]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I've tried to log via smartphone's apps - not sure if I found ones from the supported list (Sensor Logger, G-Field Recorder, Gyro) - so I tested G-Sensor logger and Sensor Logger on two different phones. I tried to open.csv files in Gyroflow, and received 'unsupported file format' error. My questions:
- is it any difference between the apps?
- is it possible to provide some instructions and/or supported apps links?
    
 Thank you!

**Comment by AdrianEddy** [comment]
Use latest dev build: https://gyroflow.xyz/devbuild/?autodownload
