### ISSUE TITLE
Why does my GPU isn't actually loaded while encoding through it?

### ISSUE THREAD

**Issue by timmal** [gyroflow/gyroflow#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-rc4

### What operating system are you using?

macOS Monterey 12.2.1

### What GPU are you using?

AMD Radeon Pro 5600M

### What happened?

Why does my GPU isn't actually loaded while encoding through it?

<img width="1170" alt="Снимок экрана 2022-02-22 в 21 31 11" src="https://user-images.githubusercontent.com/59456023/155206753-fcef9d5a-25fc-4fc9-8a72-1f1b796ec505.png">

**Comment by AdrianEddy** [comment]
Most likely because OpenCL on some Macs (or all Intel ones) uses CPU. It should be fixed when #12 is done

**Comment by AdrianEddy** [comment]
Please try latest dev build and let me know if it changed anything in this regard: https://gyroflow.xyz/devbuild/?autodownload
the app title should say `v1.0.0-rc4 (gh341)`

**Comment by timmal** [comment]
GPU is works now. But there is no preview and output result have artefacts 

<img width="1659" alt="Снимок экрана 2022-03-01 в 13 38 16" src="https://user-images.githubusercontent.com/59456023/156162768-bec616ae-085b-4c1d-a214-95f40b09f107.png">

<img width="2057" alt="Снимок экрана 2022-03-01 в 13 38 04" src="https://user-images.githubusercontent.com/59456023/156162730-127962cb-83bb-43c0-a5bc-213f9982a8e0.png">

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
