### ISSUE TITLE
Set language with "system default" somehow not function on MacOS

### ISSUE THREAD

**Issue by DusKing1** [gyroflow/gyroflow#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0-RC4

### What operating system are you using?

MacOS 13.4

### What happened?

The "language auto-detect" somehow does not function very well on MacOS. E.g. I've received a lot of reports from Chinese MacOS users asking me "why no Chinese".

![27c5f340a1941336f2fe7d37776d8a8](https://user-images.githubusercontent.com/31283897/155261475-d0cbb9fd-5f39-4488-8dce-35b4cde7cdf4.jpg)

**Comment by AdrianEddy** [comment]
This should be fixed in f792726e7512e4f6f09146b3305e1a031ba321cb and will be in rc5. If it happens again please reopen
