### ISSUE TITLE
ffmpeg error function not implemented

### ISSUE THREAD

**Issue by rgruian** [gyroflow/gyroflow#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0-rc4

### What operating system are you using?

Windows 10 build 19044.1526

### What GPU are you using?

unknown

### What happened?

Started an export process for a video recorded using GoPro Session 5, and immediately got an error message stating "ffmpeg error: function not implemented".
![Screenshot 2022-02-26 003948](https://user-images.githubusercontent.com/29284534/155836559-e69de2e9-b3b3-40ac-bbc9-2b94235a2c96.png)

**Comment by AdrianEddy** [comment]
Please upload gyroflow.log file

**Comment by AdrianEddy** [comment]
Update your GPU drivers (Intel) and if that doesn't help, please attach `gyroflow.log` file after the error appears and you close the app. Use latest dev build to get the log https://gyroflow.xyz/devbuild/?autodownload

**Comment by AdrianEddy** [comment]
There's nothing I can do without a log file so I'm closing this issue. If it's still happening, please attach the `gyroflow.log` file from latest dev version (link above)
