### ISSUE TITLE
clGetKernelArgInfo Error (procedure entry point not found)

### ISSUE THREAD

**Issue by Milo78FPV** [gyroflow/gyroflow#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.rc4

### What operating system are you using?

windows10 with all updates, but the pc has been updated from win7

### What GPU are you using?

NVIDIA GeForce GT330 (very old, made in 2009/10)

### What happened?

I just installed Gyroflow. When I try to open the gyroflow.exe, the error (German) "Der Prozedureinsprungspunkt "clGetKernelArgInfo" wurde in der DLL "(My folder where I saved Gyroflow)" nicht gefunden.
I use a very old PC so it might be that it doesn't support some features which are neccessery for Gyroflow.
![image](https://user-images.githubusercontent.com/69196892/156878902-7c2a2457-aaae-4c49-b733-4a43565f6621.png)

**Comment by AdrianEddy** [comment]
You can try installing latest GPU driver, but your GPU is probably too old.
You can also try to disable GPU processing by editing `Gyroflow_with_console.bat` file (in Notepad for example) and adding this as a second line: `set NO_OPENCL=1`. If it still fails you can also add `set NO_WGPU=1`
after these changes run `Gyroflow_with_console.bat`

Use latest dev build for this: https://gyroflow.xyz/devbuild/?autodownload
