### ISSUE TITLE
Black pixels in white areas of the output video

### ISSUE THREAD

**Issue by avsaase** [gyroflow/gyroflow#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0-RC4

### What operating system are you using?

Windows 10

### What GPU are you using?

Radeon RX 570

### What happened?

My output video has some black pixels in white areas of the frame (that are not in the input video):
![2022-03-06 23_03_06-RC_0006_220306154632_stabilized_1 mp4 - VLC media player](https://user-images.githubusercontent.com/880421/156944058-2b50a64c-695a-42bc-a86a-bc787c535fe3.png)
![2022-03-06 23_04_49-RC_0006_220306154632_stabilized_1 mp4 - VLC media player](https://user-images.githubusercontent.com/880421/156944078-dd6b0187-bb2e-4ab6-b13c-d5254f48cc5f.png)

This happens both with CPU and GPU encoding but the black pixels are not visible in the video preview. 

Here are the original video and a clip of the output video that demonstrates the problem: https://drive.google.com/drive/folders/19W-V0fH5X4CkeF3TJElUFNdRXscMtdXq?usp=sharing.

The camera is a Runcam 5 Orange. Please let me know if you need more info.

**Comment by AdrianEddy** [comment]
Can you reproduce it using latest dev build? Can you attach gyroflow.log after exporting with these artefacts? I've seen this before but I can't seem to reproduce it anymore, weird

**Comment by avsaase** [comment]
Yes, same issue with the latest dev build. I also tried h264 encoding but that didn't make a difference. 

I added the gyroflow.log file to the Google Drive folder.

**Comment by AdrianEddy** [comment]
Fixed in c360a63d1275db0dce33e2dbdc1a96660a8e7de6
