### ISSUE TITLE
Radeon Pro Vega 64 16 GB GPU encoding crashes

### ISSUE THREAD

**Issue by lomk07** [gyroflow/gyroflow#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0

### What operating system are you using?

mac os 10.14.6

### What GPU are you using?

Radeon Pro Vega 64 16 GB

### What happened?

GPU / Hardware acceleration works in preview but not with rendering. ffmpeg h264/h265 and prores enabled.
Happens with both GoPro 9 and IFlight/Insta360 Go P3 at 4K. Exporting without GPU encoding works.

Nevertheless THANK you devs for providing this amazing tool - FOR FREE. You rock!

<img width="544" alt="gyroflow ffmpeg error" src="https://user-images.githubusercontent.com/101281760/157496444-add75142-5360-4933-bf13-92ed26b885a4.png">

**Comment by AdrianEddy** [comment]
Did you try disabling GPU decoding under Advanced?

**Comment by lomk07** [comment]
I´m using 1.0.0 rc5 on mac. There are two options: GPU encoding for exporting / GPU decoding for preview window (as far as I understand the UI - please correct me if I´m wrong) 

When I try to export with encoding on and decoding off a slightly different error is displayed

<img width="291" alt="gyroflow ffmpeg error GPU decoding off GPU encoding on" src="https://user-images.githubusercontent.com/101281760/157609667-d12f41d8-65d5-4a04-94d7-a0c4559a90a8.png">
.

I´ll try to get a better log later.

**Comment by AdrianEddy** [comment]
What are your export settings? Which codec and bitrate? What format is the input file?

**Comment by AdrianEddy** [comment]
Please attach `gyroflow.log` after you get that error and close the app

Right click on Gyroflow -> Open package contents -> Contents -> MacOS -> gyroflow.log

**Comment by AdrianEddy** [comment]
Should be fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
