### ISSUE TITLE
FFmpeg error 12912

### ISSUE THREAD

**Issue by Starlights74** [gyroflow/gyroflow#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

from 1.0.0rc3 to 1.0.0rc5

### What operating system are you using?

Mac OS Monterey 12.2.1

### What GPU are you using?

Radeon Pro 580 8Gbyte

### What happened?

it happens immediately when I press export
![Schermata 2022-03-12 alle 18 18 45](https://user-images.githubusercontent.com/101472471/158028232-e79cd937-660d-450f-b1eb-c47dfd38f90d.jpg)

**Comment by dustin** [comment]
I had a similar, but not identical error.  Disabling GPU encoding made it work for me.

<img width="295" alt="Screen Shot 2022-03-12 at 10 06 40" src="https://user-images.githubusercontent.com/1779/158029493-3fc024c1-04ff-4e7d-b582-d0bc9a734112.png">

The AAC error goes away if I disable audio, of course, but the render only proceeds with GPU disabled.

**Comment by Starlights74** [comment]
thanks, without "GPU encoding" it works, but I lose all benefit of my iMac Radeon 580 Pro card.
on a i7 4,2Ghz it encoding only a 4fps a GoPro 4k 50fps file. :-(

**Comment by AdrianEddy** [comment]
Please try latest dev build https://gyroflow.xyz/devbuild/?autodownload and upload the log file after you get the error and close the app

Open package contents -> Contents -> MacOS -> gyroflow.log file

**Comment by AdrianEddy** [comment]
It should be fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
