### ISSUE TITLE
FFmpeg error22

### ISSUE THREAD

**Issue by rolandau2013** [gyroflow/gyroflow#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-rc5 (gh378)

### What operating system are you using?

OS 10.14.6

### What GPU are you using?

AMD FirePro D500 3 GB

### What happened?

![Screenshot 2022-03-15 at 12 24 52 PM](https://user-images.githubusercontent.com/101617644/158306762-d86c0185-47b2-4e63-a81c-77e947995ac9.png)
export error

**Comment by AdrianEddy** [comment]
Open package contents -> Contents -> macOS -> drag gyroflow file into terminal and press enter. Then after you close the app, upload gyroflow.log file

**Comment by rolandau2013** [comment]
is it ok??

**Comment by rolandau2013** [comment]
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/8251044/gyroflow.log)

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
