### ISSUE TITLE
No_Image

### ISSUE THREAD

**Issue by EladZa** [gyroflow/gyroflow#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0

### What operating system are you using?

win 10

### What happened?

After clicking on an EXE file, an empty window opens and there is no interface on it.
Just a blank screen.

### Relevant log output

11:48:59 [INFO] [MDK] MDK 0.14.0 (git da2fab7) - Multimedia Development Kit. Copyright (c) 2016-2022 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600 x86_64; MSVC1931; MSVCRT14.31.31103.0/msvcp140.dll; 15:20:47 Mar  6 2022
11:48:59 [DEBUG] (1) mdk: [MDK] 3mdk verify key signature ok
11:48:59 [DEBUG] (1) mdk: [MDK] 3mdk license key restrictions: OpenSource,
11:48:59 [DEBUG] (1) mdk: [MDK] user module: C:\Users\Elad\Downloads\gyroflow\Gyroflow.exe
11:48:59 [DEBUG] (1) mdk: [MDK] user module: C:\Users\Elad\Downloads\gyroflow\Gyroflow.exe
11:48:59 [DEBUG] (1) mdk: [MDK] 3mdk license key for app: gyroflow
11:49:02 [INFO] Lens profiles directory: "\\\\?\\C:\\Users\\Elad\\Downloads\\Gyroflow\\camera_presets"
11:49:02 [INFO] Loaded 1293 lens profiles in 42.802ms
11:49:02 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("NVIDIA CUDA") ["Quadro FX 580"]
11:49:02 [INFO] OpenCL Platform: NVIDIA CUDA, Device: NVIDIA Corporation Quadro FX 580
11:49:02 [INFO] Latest version: v1.0.0-rc5, current version: 1.0.0-rc5
11:49:02 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: create AV_HWDEVICE_TYPE_CUDA
11:49:02 [DEBUG] (1) gyroflow::rendering: Failed to create specified HW device: AV_HWDEVICE_TYPE_CUDA

11:49:02 [WARN] Failed to create vertex shader: Error 0x80070057: The parameter is incorrect.
11:49:02 [WARN] Failed to build graphics pipeline state

**Comment by AdrianEddy** [comment]
Update your NVIDIA drivers

**Comment by AdrianEddy** [comment]
Can you try latest dev build?
https://gyroflow.xyz/devbuild/?autodownload

If that doesn't help, try different GUI backend by editing `Gyroflow_with_console.bat` and adding this as a second line:
`set QSG_RHI_BACKEND=opengl`
or
`set QSG_RHI_BACKEND=vulkan`

**Comment by EladZa** [comment]
New problem...
gyroflow.exe - entry point not found

**Comment by AdrianEddy** [comment]
Closing this as it's most likely something wrong with your system rather than Gyroflow. Make sure you have latest GPU drivers, maybe looks for DirectX updates or something like that. Other than that the `set QSG_RHI_BACKEND=opengl` and `vulkan` options should allow you to run it. There's nothing else we can do about it here
