### ISSUE TITLE
Can t open gyroflow

### ISSUE THREAD

**Issue by teletof** [gyroflow/gyroflow#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

The last one

### What operating system are you using?

Windows 10

### What happened?

When i try to start gyroflow i have an error 0xc000007b.
The only version that works is the bêta version.
Thank you for your great work.

**Comment by AdrianEddy** [comment]
did you install https://aka.ms/vs/17/release/vc_redist.x64.exe ?

**Comment by teletof** [comment]
Yes or is done to.

**Comment by teletof** [comment]
![Uploading 16482181742032707773949828804544.jpg…]()

**Comment by AdrianEddy** [comment]
Also install all windows updates and latest gpu drivers

**Comment by teletof** [comment]
yes everything is ok

**Comment by AdrianEddy** [comment]
so is gyroflow working now?

**Comment by teletof** [comment]
no the same thing

**Comment by AdrianEddy** [comment]
how about 
Settings -> Apps -> Optional features -> Add a feature -> enable Media Feature Pack

**Comment by teletof** [comment]
it is ok and still not working

**Comment by AdrianEddy** [comment]
Closing this as it's most likely something wrong with your system rather than Gyroflow. You can google for the errors you're getting, they are system errors.
