### ISSUE TITLE
Rotate orientation to portrait mode instead of landscape

### ISSUE THREAD

**Issue by larsinka** [gyroflow/gyroflow#293]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Maybe it is already possible. 

I tried: 
1. change "rotation" in the file import section -> footage is rotated but aspect ratio isn't.
2. change "pitch" angle in the motion data -> changes just the IMU data
3. rotate footage before -> IMU data gets lost

I'm using my GoPro in portrait mode most of the time. It would be great to have portrait mode made possible / easier.

**Comment by AdrianEddy** [comment]
1. You can change aspect ratio in export settings
2. That's correct
3. You can always load the original file in just Motion Data panel to use original IMU for the processed video
