### ISSUE TITLE
Batch processing multiple files

### ISSUE THREAD

**Issue by fremebondo** [gyroflow/gyroflow#295]
### Is there an existing feature request for this?

- [x] I have searched the existing requests

### Description

Hi everyone, I've googled for it but found nothing. 

Is a batch processing mode supported or will be in the future? A command line interface could be used as well to achieve the same result.

If already existing, really sorry but did not find anywhere in the doc.....

**Comment by fremebondo** [comment]
I relize that "gyroflow batch" query on google did not find these. And, my fault, I did not used github search. Sorry for that!

**Comment by AdrianEddy** [comment]
Done in 07ff17372c3d305b106eee791939450f36e89d04 and cec97ec1f750b5e85f4246034827fd0e854d4c7c

**Comment by stigla610** [comment]
Is there a way to batch export project files with gyro data?
This would be useful in projects containing many smaller videos which are later stabilized with the Gyroflow OFX plugin. It would help with the final quality by skipping encoding in the Gyroflow app

**Comment by AdrianEddy** [comment]
There's no way do to that, but you still need to do the syncing in Gyroflow etc, so I'm not sure this is useful. If you're working with syncless GoPro files, then it's a pretty quick process: drag & drop the video and 2 clicks to export the project file, so you can do a lot of files quickly by just positioning your explorer window next to gyroflow and dragging the files.

**Comment by stigla610** [comment]
I am indeed working with GoPro files and the process is rather quick but I have around 4000 videos (3 years worth of recording) and most of them never got stabilized due to lack of storage.
Drag and drop method you mentioned is still way faster than anything available in other apps!
