### ISSUE TITLE
GoPro Hero 10: Horizon lock flips 180 degree on acceleration or direction changes

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

gh418

### What operating system are you using?

Win 10

### What GPU are you using?

RTX 3090

### What happened?

GoPro 10 placed on gimbal with roll and pitch axis fixed / stabilized. On quick acceleration or direction changes (e.g. running, chasing something) it repeatedly flips 180 degree over back and forth.

I wonder if the the correct sensor field is used?

**Comment by hdosys** [comment]
Sorry for the delay. If more sample footage is required, please let me know and I will upload it. I forgot to mention that the GoPro is always mounted on my gimbal with a 180 degree rotation.

**Comment by hdosys** [comment]
Yes, I have exactly the same issues as [Marcus-Zhu](https://github.com/Marcus-Zhu). It also starts with a 90-degree rotation and then flips back and forth.

**Comment by AdrianEddy** [comment]
@User-3090 and @Marcus-Zhu - this should be fixed in latest dev build for Hero 9 and 10, please check. https://gyroflow.xyz/devbuild/?autodownload

Hero 8 doesn't have gravity vector in metadata so it probably won't work, but you can also try

**Comment by hdosys** [comment]
The issue is fixed and works well.

One request: could you pre-populate "Roll angle correction" with the "Rotation" angle from the video information panel? Otherwise, the video flips for anyone with a non-zero rotation angle as soon as Lock horizon is enabled.

Thank you very much!
