### ISSUE TITLE
Make loop behaviour consistent (always?)

### ISSUE THREAD

**Issue by ghuser123321** [gyroflow/gyroflow#302]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Currently it only seems to loop when a trim section is selected and the section end is not the clip end. Can we have it loop always?

**Comment by AdrianEddy** [comment]
@wang-bin How to loop at end when `player->setProperty("continue_at_end", "1");` is set?

**Comment by wang-bin** [comment]
try the latest build

**Comment by hdosys** [comment]
I tried gh425, and the behavior appears unchanged:

- No loop when no trim range exists.
- No loop when a trim range exists but ends at the end of the clip.
- Looping occurs when a trim range exists and ends before the end of the clip.

**Comment by AdrianEddy** [comment]
@ghuser123321 wang-bin meant the mdk-sdk build, not gyroflow build, it's not updated yet in gyroflow. You can replace the mdk by yourself by downloading from https://sourceforge.net/projects/mdk-sdk/files/nightly/ and replacing in gyroflow directory. 

I didn't test it myself yet

**Comment by ghuser123321** [comment]
Thanks. It's fixed.

There is still some sort of play head jump or slowdown when it reaches the last frames of the clip, but I'd consider that a cosmetic issue :)

**Comment by ghuser123321** [comment]
Fixed.
