### ISSUE TITLE
Gyroflow can't read magnetometer data

### ISSUE THREAD

**Issue by Sixlain** [gyroflow/gyroflow#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.0-rc5

### What operating system are you using?

Windows 10

### What GPU are you using?

GTX1050

### What happened?

I use format gcsv and with the offical guide, but I see no magnet data input. 
offical format:
GYROFLOW IMU LOG
version,1.1
id,custom_logger_name
orientation,YxZ
note,development_test
fwversion,FIRMWARE_0.1.0
timestamp,1644159993
vendor,potatocam
videofilename,videofilename.mp4
lensprofile,potatocam_mark1_prime_7_5mm_4k
tscale,0.001
gscale,0.00122173047
ascale,0.00048828125
mscale,0.00059875488
t,gx,gy,gz,ax,ay,az,mx,my,mz
0,39,86,183,-1137,-15689,-2986,123,345,546
1,56,100,202,-1179,-15694,-2887,124,344,560

I input them to gyroflow. I can see g and a are correctly input but not m.
This will cause shift of the centre because no magnet data to control intergral error.

### Relevant log output

```shell
15:14:10 [INFO] Lens profiles directory: "\\\\?\\D:\\二级软件\\Gyroflow-windows64\\camera_presets"
15:14:10 [INFO] Loaded 1293 lens profiles in 44.892ms
15:14:10 [INFO] Latest version: v1.0.0-rc5, current version: 1.0.0-rc5
15:14:11 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("NVIDIA CUDA") ["GeForce GTX 1050"]
15:14:11 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("Intel(R) OpenCL HD Graphics") ["Intel(R) HD Graphics 630"]
15:14:11 [INFO] OpenCL Platform: Intel(R) OpenCL HD Graphics, Device: Intel(R) Corporation Intel(R) HD Graphics 630
[src\rendering\mod.rs:47] gpu_type = Intel
15:14:17 [DEBUG] (10) MDKPlayer: [in m_player->onEvent] "reader.buffering" ""
15:14:17 [DEBUG] (11) MDKPlayer: [in m_player->onEvent] "thread.video" ""
15:14:17 [DEBUG] (12) MDKPlayer: [in m_player->onEvent] "thread.audio" ""
15:14:17 [DEBUG] (12) MDKPlayer: [in m_player->onEvent] "decoder.audio" "FFmpeg"
15:14:17 [DEBUG] (12) MDKPlayer: [in m_player->onEvent] "reader.buffering" ""
15:14:17 [DEBUG] (13) MDKPlayer: [in VideoTextureNodePriv::createTexture] QSGRendererInterface::Direct3D11
15:14:17 [DEBUG] (13) MDKPlayer: [in MDKPlayer::sync] created texture QSGPlainTexture(0x26fe492cc10) QSize(1146, 645)
15:14:17 [DEBUG] (11) MDKPlayer: [in m_player->onEvent] "decoder.video" "AVCodec.D3D11"
15:14:17 [DEBUG] (13) MDKPlayer: [in m_player->onEvent] "render.video" "1st_frame"
15:14:17 [INFO] surface size: 1280x720
15:14:18 [DEBUG] (13) MDKPlayer: [in VideoTextureNodePriv::createTexture] QSGRendererInterface::Direct3D11
15:14:18 [DEBUG] (13) MDKPlayer: [in MDKPlayer::sync] created texture QSGPlainTexture(0x26feedef400) QSize(1280, 720)
```

**Comment by AdrianEddy** [comment]
Good catch, fixed in https://github.com/AdrianEddy/telemetry-parser/commit/9fdc46664fa09f7c9b15fef4c500bd0fafffe2b8
Will be available in dev build in ~30 minutes here https://gyroflow.xyz/devbuild/?autodownload
