### ISSUE TITLE
Vertical bias for dynamic zoom

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#305]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

As many I shoot full sensor 4:3 and crop down to 16:9. Currently dynamic zoom always centers vertically. Can we get a slider to set vertical bias? A settings to determine to favor cropping the bottom or top of the frame when zooming.

Obviously full re-framing support with key frames would be amazing, but this alone would help a ton.

**Comment by AdrianEddy** [comment]
Done in a9d984987b3aba0fd0b390a48fa9834b0a21c953 https://gyroflow.xyz/devbuild/?autodownload
