### ISSUE TITLE
reset defaut value

### ISSUE THREAD

**Issue by Francesco-Roma** [gyroflow/gyroflow#307]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Add a new feature for reset all the value of the application as the initial value of the first installation

**Comment by AdrianEddy** [comment]
Windows:
1. Windows+R and type `regedit` or look for `Registry Editor` in Start menu
2. Go to `Computer\HKEY_CURRENT_USER\SOFTWARE\Gyroflow` (enter this in the top bar and hit Enter)
3. Delete the entire key

MacOS:
Open Terminal and enter: `rm -f $HOME/Library/Preferences/com.gyroflow-xyz.Gyroflow.plist ; killall cfprefsd`

Linux:
Open Terminal and enter: `rm -f $HOME/.config/Gyroflow/Gyroflow.conf`

**Comment by AdrianEddy** [comment]
In latest Gyroflow version, there's a button to reset all settings in the Advanced section

**Comment by Francesco-Roma** [comment]
Big Adrian.

Thank you.

**Comment by lukegluke** [comment]
@AdrianEddy is there a possibility to replace default settings with custom ones? For now each time I have to drop setting file just to set usual output resolution and bitrate for my single camera.

**Comment by AdrianEddy** [comment]
@lukegluke  in v1.3.0-rc you can put your preset as `default.gyroflow` in `camera_presets` directory and it will be applied to every video you load
