### ISSUE TITLE
Support for large mp4 files from Caddx Peanut / Insta360 go2

### ISSUE THREAD

**Issue by MikeCswe** [gyroflow/gyroflow#309]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Add support so Gyroflow can read motion data from Caddx Peanut / Insta360 go2 mp4 files that are very large (8gb which is around 14 minutes of video).

If not, an entry in the FAQ could be useful as I have been unable to find any documentation anywhere that there even is an issue with this at all. Am I the only one who would want to use large Peanut / Go2 files in Gyroflow?

**Comment by AdrianEddy** [comment]
it should work, do you have an example file that doesn't work?

**Comment by MikeCswe** [comment]
I'm having troubles finding a site that can host a 6 gig file. They work fine up to just over 4 gig.

**Comment by AdrianEddy** [comment]
> The video files work fine in Gyroflow up to just over 4 gig, the ones I have issues with a larger and I'm having troubles finding a site that can host a 6 gig file. If I find one I'll post a link.

https://mega.co.nz/ should do the trick

**Comment by MikeCswe** [comment]
Thanks for the tip. Uploading.

**Comment by MikeCswe** [comment]
https://mega.nz/file/cjwyRYaA#isSTtUkXvxF6ap4RozVKWyYXK6A0XCt_pgYgKxkZTuw

**Comment by MikeCswe** [comment]
Because you said it should work I did a bench test of 10 minutes which landed on just over 6 gigabytes. This file works in Gyraflow so I am starting to suspect that the camera for some reason did not record valid motion data in the video I uploaded. Are you able to confirm that? I do not know how to check.

**Comment by AdrianEddy** [comment]
> Because you said it should work I did a bench test of 10 minutes which landed on just over 6 gigabytes. This file works in Gyraflow so I am starting to suspect that the camera for some reason did not record valid motion data in the video I uploaded. Are you able to confirm that? I do not know how to check.

You're right, this file doesn't contain gyro data and even Insta360 Studio doesn't recognize it, so there's nothing we can do about it in Gyroflow

**Comment by MikeCswe** [comment]
No, not a Gyroflow issue at all. Thanks for checking for me, much appreciated! I'll try Caddx support.

**Comment by MikeCswe** [comment]
Not a Gyroflow issue at all.
