### ISSUE TITLE
Playhead hard to drag / seek within trim range

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

gh425

### What operating system are you using?

Win10

### What GPU are you using?

3090

### What happened?

For some reason I find the play head quirky to drag -- in general, but particular if it's close to the clip end. It tends to wildly jump somewhere else when dragged near clip end.

**Comment by AdrianEddy** [comment]
Can you show a screen recording of this behavior?

**Comment by ghuser123321** [comment]
Sure:
https://user-images.githubusercontent.com/71881005/163563523-3645a872-e476-41f8-a186-8da30bc29604.mp4

**Comment by hdosys** [comment]
Reproduction video:

https://user-images.githubusercontent.com/71881005/163563673-09a2b093-5b85-4665-a7da-9da667ae0a45.mp4

**Comment by AdrianEddy** [comment]
Hmm, it doesn't behave this way for me, but it will depend on your input file. If you try with a file in intermediate codec like ProRes or DNxHD, you'll see no jumping. The problem is in the way the frames are stored in x264/x265 files and the keyframe distance, some files may have this behavior better and some worse. It's nothing in Gyroflow though, it'll be in ffmpeg or MFT or any underlying decoder which handles the file

**Comment by hdosys** [comment]
I understand that Long-GOP codecs seek more slowly than all-intra codecs. That is not the issue: the playhead jumps elsewhere, and sometimes it is impossible to seek to a specific position. In those cases, I can only play through to that position.

The source file is 200Mbit 4k120p HEVC from a GoPro 10 with Labs firmware and `!MBITR=200` set.

**Comment by AdrianEddy** [comment]
can you send me that file?

**Comment by mycosd** [comment]
I've looked into that one some time ago (happens with my Hero8 HEVC clips too). It somhow comes from the MDK-Player returning weird frame positions while seeking. I don't see this issue related to GOP. In my clips I have a keyframes every second, but the jumps are way bigger and always to the beginning of the trim range.
It also only appear to happen if you have a trim range set.

**Comment by hdosys** [comment]
You are right. The issue occurs within a trim range and is not specific to the end of the clip. It was simply a coincidence that I often trim at the end. I will upload sample footage for this and the other issues.

Thank you again for making this excellent project possible and for doing so with strong technology choices (Rust+QT+ffmpeg, etc.).

**Comment by AdrianEddy** [comment]
Is this still an issue in latest dev build? https://gyroflow.xyz/devbuild/?autodownload

**Comment by mycosd** [comment]
I can't reproduce it anymore, not even with the version I've noticed the issue in. Not sure what's going on, maybe GPU driver update?
