### ISSUE TITLE
Gf keeps crashing on launch, no errors

### ISSUE THREAD

**Issue by Fede163x** [gyroflow/gyroflow#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

rc5, rc4

### What operating system are you using?

windows 10

### What GPU are you using?

nvidia geforce gtx 1050

### What happened?

Gyroflow keeps crashing, without reporting errors, every time i try to open it.
It show only a blank page for about two seconds.
i've already install all updates for graphics, wind and vc.redistr.x64
I've tried rc5 and rc4, same things happened

**Comment by AdrianEddy** [comment]
what happens when you open `Gyroflow_with_console.bat`?

**Comment by Fede163x** [comment]
it says:
12:14:38 [DEBUG] (2) gyroflow::util: Minidump uploaded: OK
12:14:41 [INFO] Lens profiles directory: "\\\\?\\C:\\Users\\skiop\\Downloads\\Gyroflow-windows64\\camera_presets"
12:14:41 [INFO] Latest version: v1.0.0-rc5, current version: 1.0.0-rc5
12:14:41 [INFO] Loaded 1293 lens profiles in 38.202ms
Crashdump written to C:\Users\skiop\Downloads\Gyroflow-windows64/a2a56ee2-ef78-49e0-824d-2d5c76352e71.dmp
Premere un tasto per continuare . . .

**Comment by Fede163x** [comment]
how can i attach the dmp file?

**Comment by AdrianEddy** [comment]
Can you try in the dev build? https://gyroflow.xyz/devbuild/?autodownload

**Comment by Fede163x** [comment]
same thing happened

12:48:23 [DEBUG] (4) gyroflow::util: Minidump uploaded: OK
12:48:26 [INFO] Latest version: v1.0.0-rc5, current version: 1.0.0-rc5 (gh425)
12:48:27 [INFO] Lens profiles directory: "\\\\?\\C:\\Users\\skiop\\Downloads\\gyroflow\\Gyroflow-windows64\\camera_presets"
12:48:27 [INFO] Loaded 1293 lens profiles in 36.733ms
Crashdump written to C:\Users\skiop\Downloads\gyroflow\Gyroflow-windows64/fd6ef335-3341-4494-be70-d19c4a9c85e3.dmp
Premere un tasto per continuare . . .

**Comment by AdrianEddy** [comment]
What's your device? Is that a laptop or PC? do you have two graphic cards? (Intel HD and NVIDIA for example)?

**Comment by Fede163x** [comment]
it's a laptop, yes i have both intel hd and nvidia

**Comment by Fede163x** [comment]
![image](https://user-images.githubusercontent.com/103937801/163812485-8debc225-cae0-4128-920c-ad2dc8001905.png)

**Comment by AdrianEddy** [comment]
looks like there's some issue with the Intel HD graphics driver, did you update it?

**Comment by Fede163x** [comment]
unistall and reinstall all with the intel assistant, now it works! thank u a lot :)))
