### ISSUE TITLE
Export trim range with black frames padded to source file lenght

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#314]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

What is the point? The ability to re-link to Gyroflow stabilized files in Resolve after having assembled a rough cut there already. For that to work they need to have the same play time.

Often less than 5% of source footage is used in a final edit. So the point is to assemble a rough cut in Resolve first. Then process only need files in Gyroflow and re-link to those files in Resolve.

Padding with black frames should bring bit rate close to zero for padded frames. At least for long GOP codecs.

**Comment by AdrianEddy** [comment]
Done in: fa4dbaac512936db039f5390e8d0ab3d3f0858c3
https://gyroflow.xyz/devbuild/?autodownload
