### ISSUE TITLE
i want to run the project in visual studio code

### ISSUE THREAD

**Issue by kxifenger** [gyroflow/gyroflow#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-rc5

### What operating system are you using?

mac os monterey 12.1

### What happened?

how to run this project in visual studio code
i download the project and run in the visual studio code but it do not work.
![L1VzZXJzL2lmZW5nL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy81NDM3ODU4MzdfdjIvSW1hZ2VGaWxlcy8xNjUwODY5NDM2NDIyXzZEODgxRjlDLURBOUEtNDhBOS05OTgwLTI4NTI3NTMzM0VBQS5wbmc=](https://user-images.githubusercontent.com/77945871/165035387-2796f5f1-a97a-407d-9ca5-569175352be8.png)
i need some help. thank you

**Comment by AdrianEddy** [comment]
Follow `Building on MacOS` from the README: https://github.com/gyroflow/gyroflow#building-on-macos
Don't use built-in "Run" and "Debug" options in VS Code, it's hard to setup this

**Comment by kxifenger** [comment]
> Follow `Building on MacOS` from the README: https://github.com/gyroflow/gyroflow#building-on-macos Don't use built-in "Run" and "Debug" options in VS Code, it's hard to setup this

thank you for you reply，i want to know how to debug this project，and what IDE use to develop
