### ISSUE TITLE
Building on MacOS

### ISSUE THREAD

**Issue by kxifenger** [gyroflow/gyroflow#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-rc5

### What operating system are you using?

mac os monterey 12.1

### What happened?

i got this error when Building on MacOS in 4 step  Install dependencies: cd gyroflow/ext && ./install-deps-mac.sh
how to solve it
-- Using community triplet x64-osx-release. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/ifeng/gyroflow/ext/vcpkg/triplets/community/x64-osx-release.cmake
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz -> libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz...
-- Extracting source /Users/ifeng/gyroflow/ext/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at /Users/ifeng/gyroflow/ext/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean
-- Configuring x64-osx-release-rel
-- Building x64-osx-release-rel
-- Fixing pkgconfig file: /Users/ifeng/gyroflow/ext/vcpkg/packages/libjpeg-turbo_x64-osx-release/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: /Users/ifeng/gyroflow/ext/vcpkg/packages/libjpeg-turbo_x64-osx-release/lib/pkgconfig/libturbojpeg.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:615 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/libjpeg-turbo/portfile.cmake:59 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:145 (include)

error: building libjpeg-turbo:x64-osx-release failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
including:
  package: libjpeg-turbo[core]:x64-osx-release -> 2.1.3#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 2ac61f8 2022-04-22 (3 days ago)

Additionally, attach any relevant sections from the log files above.
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:arm64-osx -> 2.1.3#2
  * liblzma[core]:arm64-osx -> 5.2.5#5
  * libpng[core]:arm64-osx -> 1.6.37#17
  * libwebp[core,libwebpmux,nearlossless,simd]:arm64-osx -> 1.2.2
    opencv[core]:arm64-osx -> 4.5.5
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:arm64-osx -> 4.5.5#3
  * protobuf[core]:x64-osx -> 3.19.4
  * protobuf[core]:arm64-osx -> 3.19.4
  * quirc[core]:arm64-osx -> 1.1#2
  * tiff[core,jpeg,lzma,zip]:arm64-osx -> 4.3.0#8
  * vcpkg-get-python-packages[core]:x64-osx -> 2022-04-11
  * zlib[core]:arm64-osx -> 1.2.12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Detecting compiler hash for triplet x64-osx...
Restored 0 packages from /Users/ifeng/.cache/vcpkg/archives in 59.52 us. Use --debug to see more details.
Starting package 1/12: libjpeg-turbo:arm64-osx
Building package libjpeg-turbo[core]:arm64-osx...
-- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/ifeng/gyroflow/ext/vcpkg/triplets/community/arm64-osx.cmake
-- Using cached libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz.
-- Cleaning sources at /Users/ifeng/gyroflow/ext/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/ifeng/gyroflow/ext/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at /Users/ifeng/gyroflow/ext/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean
-- Configuring arm64-osx-dbg
-- Configuring arm64-osx-rel
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Fixing pkgconfig file: /Users/ifeng/gyroflow/ext/vcpkg/packages/libjpeg-turbo_arm64-osx/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: /Users/ifeng/gyroflow/ext/vcpkg/packages/libjpeg-turbo_arm64-osx/lib/pkgconfig/libturbojpeg.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:615 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/libjpeg-turbo/portfile.cmake:59 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:145 (include)

error: building libjpeg-turbo:arm64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
including:
  package: libjpeg-turbo[core]:arm64-osx -> 2.1.3#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 2ac61f8 2022-04-22 (3 days ago)

Additionally, attach any relevant sections from the log files above.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1010    0  1010    0     0   1006      0 --:--:--  0:00:01 --:--:--  1013
100   367  100   367    0     0    188      0  0:00:01  0:00:01 --:--:--   931
100 24.1M  100 24.1M    0     0  1248k      0  0:00:19  0:00:19 --:--:-- 1044k
./install-deps-mac.sh: line 22: 7z: command not found
tar: Error opening archive: Failed to open 'ffmpeg.tar'
./install-deps-mac.sh: line 26: cd: ffmpeg-5.0-macOS-gpl-lite: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavcodec.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavformat.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavdevice.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavfilter.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavutil.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libswresample.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libswscale.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libx264.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libx265.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavcodec.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavformat.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavdevice.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavfilter.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libavutil.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libswresample.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libswscale.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libx264.a (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: lib/libx265.a (No such file or directory)
cp: include: No such file or directory
cp: include: No such file or directory
ifeng@ifengdeMacBook-Pro ext %

**Comment by AdrianEddy** [comment]
it says in the message, please read the messages carefully:
```
Could not find pkg-config. Please install it via your package manager:

  brew install pkg-config
  ```
