### ISSUE TITLE
New lens profile.  Wrong resolution after saving the profile

### ISSUE THREAD

**Issue by YeppAFpv3** [gyroflow/gyroflow#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

Rc5

### What operating system are you using?

Windows 11

### What happened?

I have tried many times to create a lens profile for a 5472x2328 resolution camera (insta360 one rs with Leica lens).  Once the file has been loaded, the resolution of the newly created profile changes to 5471x2328.  It therefore loses one pixel horizontally.  So Gyroflow warns that the aspect ratio between profile and video are different.

**Comment by AdrianEddy** [comment]
This has been fixed in latest dev build, please confirm and close https://gyroflow.xyz/devbuild/?autodownload
