### ISSUE TITLE
rendering % not shows up correctly in taskbar

### ISSUE THREAD

**Issue by WizzX-FPV** [gyroflow/gyroflow#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.0.0-RC5 (gh465)

### What operating system are you using?

Windows 10

### What GPU are you using?

Intel UHD 620

### What happened?

During rendering I can see correct percentage of how much of video is already rendered on main screen.
But Gyroflow icon in the taskbar looks like percentage value is different as on main window (I suppose it should be the same).
![percentage](https://user-images.githubusercontent.com/40316777/166214829-46e34630-b378-46e5-b5a0-ff9be1630ad4.png)

**Comment by AdrianEddy** [comment]
And what items do you have in the render queue?

**Comment by WizzX-FPV** [comment]
not using render queue, only single file

**Comment by AdrianEddy** [comment]
Yes but even single file is added to the render queue, it's probably showing progress of the entire render queue (which includes already rendered items)

**Comment by WizzX-FPV** [comment]
I can confirm that with last automated build it works OK, thank you Adrian, good job!
