### ISSUE TITLE
When dragging files into render queue, it overwrites output path without asking

### ISSUE THREAD

**Issue by MiniGod** [gyroflow/gyroflow#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

gh471

### What operating system are you using?

Windows 10

### What happened?

When dragging a file into the render queue if gets the default `_stabilized.mp4` filename without checking if that file already exists.
Pressing "Start exporting" overwrites the file without asking. It only warns me if I `Edit` & `Save`.

**Comment by AdrianEddy** [comment]
Fixed in c42a2a9d29175dad1c49070ebe2bb6335c5700a5
