### ISSUE TITLE
operational suggestions

### ISSUE THREAD

**Issue by victorlysak** [gyroflow/gyroflow#328]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I am unable to use Gyroflow in Windows 8.1. The program simply doesn't start. Just creates a new dump file every time I load it.
So, I am currently trying it in Ubuntu 20.04 on laptop dell lat. 5480 with Intel UHD 620, and it works well. No hw encoding, but I can live with it.

Here a few points that I would wish to have in Gyroflow, mainly relating to stabilizing multiple files, one after another.

1. Remember my Last chosen lens profile. - When loading new video file, Gyroflow doesn't remember my last Lens profile. Instead it is loading the one for my camera (Hero 6 black 4k wide). BUT I have Hero 6 black with non-stock linear lens (4k Linear), and such profile (4K 50fps Linear) does not exist in Gyroflow, therefore I choose Hero8 black 3840x2160 Linear NO-EIS). 
So I would like Gyroflow to **remember my last Lens Profile**.

2. **Remember my last chosen bitrate**. I choose 150 mbps (with x264). Every time I load new file, Gyroflow gives me 75 mbps, and I have to change it back to 150 because I save it in x264 (original file is in x265).

3. **Remember my last Use GPU encoding settings**. Because my card doesn't have hw acceleration, every time I load a new file, I have to uncheck this option because Gyroflow doesn't remember it.

Also note, that Gyroflow doesn't remember the above options even when I am not closing it. In other words, every time I load new clip, it resets the above options back to defaults and I have to set them up again. I believe this is much less efficient if one has many short clips, and may also forget to set them again on a new file.

All the other options Gyroflow remembers well.

Thank you very much for your hard work. This soft is great. For me it is much better than Reelsteady.

**Comment by AdrianEddy** [comment]
Windows 8.1 is not supported, is there any reason you won't upgrade to 10 or 11?

1. I'm confused, you record in linear mode, but Gyroflow loads Wide lens? I don't think Gyroflow should auto-load custom profiles if it detects a valid profile automatically. Please provide more details about your use case here.
2. Gyroflow sets the bitrate based on the input file, how do you see it being remembered? What if you load files with different input bitrate? I don't think it should enforce one bitrate regardless of the video file.
3. Looks like a bug, I'll fix it

Also, you should be able to use GPU encoding on linux with NVIDIA, what's the issue? did you install all recommended packages from README? did you try latest dev build? https://gyroflow.xyz/devbuild/?autodownload

**Comment by victorlysak** [comment]
The reason I don't want 10 or 11 is that I like to have lesss rubbish. My 8.1 is fully customized to my nees. It always starts in less than 20 sec and shuts down in under 10 secs, and I have no more than 60 processes running. :)

1. My Hero 6 is not standard. It has linear lens (physical lens - not original GoPro's). This allows me to record true (non-cropped) linear 4k 50/60fps videos.
Now, if I try to stabilize 20 or more short clips, you can imagine how much time I spend searching and changing the Lens profile for every newly loaded clip. This makes me feel like I am my laptop's slave, not vice versa. :)

2. The same applies to bitrate. The original clip is in x265 (~80mbps). But I want to save it in x264, and that means that to get the same quality I have to increase the bitrate to at lease around 130 mbps. And that is also for every newly loaded clip.

3. The GPU encoding doesn't work in Gyroflow for me because I am using Intel UHD gr. 620.
I can make ffmpeg to partly use my GPU to encode video (with vaapi) but for that I need to add more parameters to ffmpeg (like h264_vaapi).
I did try Gyroflow with Nvidia GPU and it works very well. But I also need to do this on my laptop and therefore I don't use GPU's accel, unless you will add some option to customize ffmpeg parameters later.

Thank you for your reply.
