### ISSUE TITLE
Betaflight blackbox extraction dialog in Gyroflow

### ISSUE THREAD

**Issue by B-nutze-RR** [gyroflow/gyroflow#332]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Since Betaflight creates a combined .bbl file, it's currently necessary to use Betaflight Blackbox Explorer to export  the individual logs as CSV. In my case i often have more than 40 logs and it takes a significant amount of time to export and organize them all if i don't need just 1 specific out of 40.

A workflow inside Gyroflow would be very convenient.
I think a bout a dialog that pops up when loading a all.bll file as gyro source, and it should inform you that you selected a Log file that contains N individual logs. The user can now select to export all included logs or just specific ones ( fast workflow ).
In both cases it would be handy to show the list of logs with flight/log duration and log number - that allows the user to pick one or more specific ones, based on duration or recording number.  That list could also have checkboxes for each log to select it for export. A button to select all should also be available.  

The exported files should contain log number and duration in the file name - that seems the most easy way to have at least some level of file management option in this process. 
It may also be a good idea to allow the user to choose a specific location to extract the logs - usually it's SDcard or USB mass storage used to handle the logs , so extracting them only to the source location might cause issues. Extracting them directly to the directory that holds the matching video files would be the best choice. For that reason, it might be the best in terms of  workflow to take the source directory of the source video that the user loaded in gyroflow and suggest that location for the log extraction.

**Comment by AdrianEddy** [comment]
Done in 0cedf318f182cae977de12bd72714ae7cb9f1cc9
