### ISSUE TITLE
unable to export the video

### ISSUE THREAD

**Issue by postwood** [gyroflow/gyroflow#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.1

### What operating system are you using?

macOS Monterey 12.3.1

### What GPU are you using?

Radeon Pro 560 4 GB

### What happened?

When I start exporting the file，I get stuck at this interface
![start export](https://user-images.githubusercontent.com/3336797/167132740-c6d42555-e937-44cc-a4f6-90608e47f3fc.png)

then get this error
![error](https://user-images.githubusercontent.com/3336797/167131408-82da9000-698f-4eee-8676-9b07c0af5535.png)

**Comment by postwood** [comment]
> Did you try other codec?

thanks! I got the issue in x265 codec，now it works on other codec

**Comment by AdrianEddy** [comment]
so Radeon Pro 560 apparently doesn't support x265 hardware encoding
