### ISSUE TITLE
Timelapse/Hyperlapse

### ISSUE THREAD

**Issue by maxbl4** [gyroflow/gyroflow#334]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Implement stabilization of speed up video. Like Insta 360 studio, where you can set target speed, e.g. 4x, the result will be played 4x faster and stabilization will take the speed into account and stabilize with longer intervals

**Comment by AdrianEddy** [comment]
This is already available in latest dev build https://gyroflow.xyz/devbuild/?autodownload
