### ISSUE TITLE
Trims batch export file overwriting

### ISSUE THREAD

**Issue by andreikantsidaylo** [gyroflow/gyroflow#337]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

When adding a few trims to que, files getting the same names and overwriting each other after starting the export
![Screenshot 2022-05-08 at 16 01 01](https://user-images.githubusercontent.com/85390015/167297412-93f973cf-fe1a-447f-88f6-e8bf2feee2f7.png)
.

**Comment by AdrianEddy** [comment]
Fixed in 102e4c8d8b2ec05a4f50dd03ed6468c8a101d76d. Download latest dev build https://gyroflow.xyz/devbuild/?autodownload
