### ISSUE TITLE
Rendering from Macbook Pro 2012 Always Force Close

### ISSUE THREAD

**Issue by christiantojimmy** [gyroflow/gyroflow#345]
Trying to export stabilized footage from my Gopro Hero 6 Black with Superview & EIS off but always force close on Gyroflow 1.0.1.
I'm trying to use x264 and x265 codecs but still no luck
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/8706396/gyroflow.log)
.

**Comment by AdrianEddy** [comment]
Try this: 
Open Terminal and enter:
`export NO_OPENCL=1 && /Applications/Gyroflow.app/Contents/MacOS/gyroflow`

let me know if that worked and provide the log file

**Comment by christiantojimmy** [comment]
It works!
Thanks!
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/8713133/gyroflow.log)
