### ISSUE TITLE
 QQmlApplicationEngine failed to load component with Release #514

### ISSUE THREAD

**Issue by robustini** [gyroflow/gyroflow#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

 Release #514

### What operating system are you using?

Windows 10 Pro x64

### What GPU are you using?

RTX3070

### What happened?

More than a bug it does not find that component:

09:50:36 [WARN] QQmlApplicationEngine failed to load component
09:50:36 [WARN] qrc:/src/ui/main_window.qml: No such file or directory
09:50:36 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("NVIDIA CUDA") ["NVIDIA GeForce RTX 3070"]
09:50:36 [INFO] OpenCL Platform: NVIDIA CUDA, Device: NVIDIA Corporation NVIDIA GeForce RTX 3070
09:50:36 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: create AV_HWDEVICE_TYPE_CUDA
09:50:36 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: created ok AV_HWDEVICE_TYPE_CUDA
[src\rendering\mod.rs:50] gpu_type = NVIDIA

Release #507 work fine here.

**Comment by AdrianEddy** [comment]
Fixed in 516
