### ISSUE TITLE
Gyroflow closes by muting the sound during play (Release #516)

### ISSUE THREAD

**Issue by robustini** [gyroflow/gyroflow#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

Release #516

### What operating system are you using?

Windows 10 Pro x64

### What GPU are you using?

RTX3070

### What happened?

During the play I tried to mute the sound and Gyroflow closed.

### Relevant log output

[gyroflow.zip](https://github.com/gyroflow/gyroflow/files/8752355/gyroflow.zip)

**Comment by AdrianEddy** [comment]
I can't reproduce this on Windows, does it happen with all files or a specific one?

**Comment by AdrianEddy** [comment]
Can you check with other video?

**Comment by AdrianEddy** [comment]
Do you still have this issue?
