### ISSUE TITLE
Gyrodata Sony FDR-X1000v

### ISSUE THREAD

**Issue by Noctaro** [gyroflow/gyroflow#354]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hi all! Thank you for the amazing work. I wonder if it is possible to use gyrodata from the Sony FDR-X1000V to stabilize. 
I can import footage but it does not show me gyro traces. Anyways Gyroflow says it detects data in the video file. Let me know if you need a sample video file or any other data to check it.

![grafik](https://user-images.githubusercontent.com/23296123/170738714-5005b2d2-6f17-43f2-8306-4154cbb512dc.png)

**Comment by AdrianEddy** [comment]
I don't think FDR-X1000V records gyro data.
You can send a sample file though, I'll verify

**Comment by AdrianEddy** [comment]
I'm 99% sure it doesn't record gyro data, if you send me a sample file I'll verify, but there's very little chance for that.
