### ISSUE TITLE
Can't stabilize videos with more than one sync point

### ISSUE THREAD

**Issue by sarfomis** [gyroflow/gyroflow#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.0.1

### What operating system are you using?

windows 10

### What GPU are you using?

nvidia gtx950m

### What happened?

I can't get the program to work with any videoI make. 
camera: Runcam hybrid 4k
gyro: onboard flash iflight succeX Micro F4, betaflight blackbox

When I manually set ONE sync point, the video is correctly stabilized around that sync point.

After some seconds from that sync point the video is not stabilized anymore (as it should be). 
 
 As soon as I add a second sync point (later or sooner) the video will not be anymore stabilized even around the first sync point.
 things get worse if I add more sync point.
 
 no matter what I do, can't get the video to be stabilized with gyroflow.
 
 sample video/blackbox
https://drive.google.com/drive/folders/13-fVqG5XWnLw52i2UKETyIGO0sFPXIdN?usp=sharing

thanks for help
Simone

**Comment by xan86** [comment]
Try to sync with [RC1 version](https://github.com/gyroflow/gyroflow/releases) then:
- export .gyroflow file (including gyro data)
- Close RC1
- Open release 1.0.1
- drag and drop only video file
(Will ask for load .gyroflow file)
- select Yes

You will see that everything will work.

This is the only way I have found to use gyroflow with betaflight blackbox.

Maybe the interpolation algorithm is not working well anymore when gyro and frame rate sampling are from 2 differenti devices. 

I had an open issue on this argument, never solved.
[Issue 230](https://github.com/gyroflow/gyroflow/issues/230)

**Comment by AdrianEddy** [comment]
@xan86 I don't think you're right, I just tested and everything works fine in latest dev build - like I mentioned we now have a new sync algorithm https://gyroflow.xyz/devbuild/?autodownload

@sarfomis Everything works as expected, but you have to make sure you have:
1. Camera angle set correctly (Motion data -> Rotation -> Pitch)
2. Rolling shutter value set correctly
Rough gyro offset is 14s and autosync works fine. Sometimes you have to adjust sync point manually by a few milliseconds, but that's normal with cheaper cameras or blackbox gyro source (large gyro drift)
[RC_0052_1701010005.zip](https://github.com/gyroflow/gyroflow/files/8817994/RC_0052_1701010005.zip)

**Comment by sarfomis** [comment]
another test with that version (gh530):
syncing first point, same thing as my first post. (video around it is stable, becoming unstable as much as time goes on)
added a second sync point towards the end. manually. (right click, add sync point here)
now it is wobbly around 25 secs (where it was super stable without the second SP). same you can see with my .gyroflow data file.

I have manually moved FIRST sync point back by ~50ms. now curves from blackbox and optical flow DOES NOT MATCH, as you can see here ![optical desync](https://user-images.githubusercontent.com/106694848/171499698-d34083ca-2bcb-4c05-97a0-a131eef248da.jpg) but the video is stabilized!
If I can not rely on visual curves, how can I manually sync the points? automatic does not work even with your suggestions.
the only way is really what @xan86 suggested with RC1.

hope you can find the reason and a solution. thanks for what you've done since now, it's an awesome project!

**Comment by AdrianEddy** [comment]
I have apologize to you both @sarfomis and @xan86, it turned out that there was indeed a bug in Gyroflow. While stabilization worked fine, the sync points weren't accurate when the offset was large. The reason it worked in RC1 is because the blackbox offset was not subtracted and so it was much smaller offset value.

Please test latest dev build (gh532) https://gyroflow.xyz/devbuild/?autodownload
1. Set camera angle (Motion data->Rotation->Pitch)
2. Set rolling shutter correction (~15ms in your case)
3. Set initial offset to 7s
4. Do autosync

Let me know if it's any better

**Comment by sarfomis** [comment]
looks like it is working good now! thanks!!

it is only extremely slow to calculate sync points (~1-2 minutes for first point and ~4-5 minutes for the second). but the video now is perfectly stabilized. thank you!

p.s. how do you calculate rolling shutter correction? where do I get that 15ms you suggested on point 2?

**Comment by AdrianEddy** [comment]
In gh534 I added a checkbox to disable searching for positive and negative rough offset - this speeds up the sync if you already know that the offset is positive

> how do you calculate rolling shutter correction?
Record some straight vertical lines and move the camera right to left very fast. Then load that in gyroflow and try to pick such rolling shutter value that the lines become straight.

More scientific approaches need some additional hardware, or you can can  search for rolling shutter value for given camera online or check in sensor datasheet.

This is best to do when doing lens calibration and it'll be saved with your lens profile

**Comment by AdrianEddy** [comment]
Also looks like I get the best results with `Pitch: 10, Roll: 3, Yaw: 8`
Adding 20 sync points takes about 20 seconds on my computer
![image](https://user-images.githubusercontent.com/3849067/171620729-cf48da5c-4af1-40a2-be45-b29ad9eec5e9.png)
