### ISSUE TITLE
能否开发支持松下 S5 录制的视频

### ISSUE THREAD

**Issue by justerwang** [gyroflow/gyroflow#378]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

如题 能否开发松下 S5 的视频，松下 S5 本身自带陀螺仪的 ! 但是这些数据有没有被写进视频里就不知道了

**Comment by AdrianEddy** [comment]
As far as I know, no Panasonic camera writes gyro data to files, so we can't do anything about it. Not even GH6
