### ISSUE TITLE
Gyroflow crashes when exporting project file including processed gyro data

### ISSUE THREAD

**Issue by avsaase** [gyroflow/gyroflow#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

6ff15c4ce05a39c191ff2b3d31c1367d8480f5c1

### What operating system are you using?

Windows 10

### What happened?

The program crashes when selecting `Export project file (including processed gyro data)`. The other two project file export options work normally.

### Relevant log output

```shell
19:24:08 [WARN] Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
19:24:08 [ERROR] Object 0x2040937e830 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.   
This behavior is NOT supported!
qrc:/src/ui/components/Modal.qml:132: function() { [native code] }
error: process didn't exit successfully: `target\release\gyroflow.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by AdrianEddy** [comment]
Fixed in 7e342e840f0d0b6c4821e2e14bee85900149b958
