### ISSUE TITLE
Have rolling shutter correction value more than 16.67ms. 

### ISSUE THREAD

**Issue by amitkattal** [gyroflow/gyroflow#385]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I use magic lantern on my canon eos m and some modes have very high rolling shutter like 36.7 ms. Is it possible to have more high values in rolling shutter correction ?

**Comment by AdrianEddy** [comment]
You can enter any value you want there (in the editable field). In any case it doesn't make sense to have rolling shutter value higher than frame time. It's not technically possible to have 33ms frame readout time when your file is 60fps (because then each frame lasts 16ms)
