### ISSUE TITLE
Blackmagic pocket cinema camera gyro support

### ISSUE THREAD

**Issue by OlegStelmakh** [gyroflow/gyroflow#390]
Since blackmagic design released v7.9 firmware for all their bmpcc cameras (4k/6k/6k pro/6kg2) with gyrodata written into files, could gyroflow get a support to stabilize bmpcc footages?

**Comment by AdrianEddy** [comment]
yes, this is being worked on

**Comment by adinbied** [comment]
I'm sure some of this has already been figured out but figured I'd share what I'd discovered. I've found the data in each BRAW file in a hex editor and narrowed down the gyroscope and acceleration numbers but it's in some unknown hex encoding scheme <img width="1064" alt="2022-06-24 21_32_46-HxD -  C__Users_adinb_Desktop_motion" src="https://user-images.githubusercontent.com/17117986/177022329-afd161de-5253-4e04-902c-3d8cf743f336.png">
I've figured out the 'mogy' (14 6D 6F 67 79)data is from the gyroscope and the 'moac' is from the accelerometer.
For the gyroscope data, theres a couple of interesting patterns that lead me to think its 3 sets of 3 byte values, seperated by 1 byte of header/padding - although could be off base.

**Comment by AdrianEddy** [comment]
It's done in https://github.com/AdrianEddy/telemetry-parser/commit/f79d089038ce25f1f22af77ec56431ddf24621de
Available already in latest dev build: https://gyroflow.xyz/devbuild/?autodownload

**Comment by shaheedmalik** [comment]
So will it load Braw files? I tried to open one in program and the File Picker wouldn't show them.

**Comment by AdrianEddy** [comment]
@shaheedmalik did you download latest dev build? Also braw is only supported in Motion data section, not the video section

**Comment by shaheedmalik** [comment]
> @shaheedmalik did you download latest dev build? Also braw is only supported in Motion data section, not the video section

I downloaded the latest build and tried to open the Motion data section but it sat there with the spinning wheel.

**Comment by AdrianEddy** [comment]
Yes, you need to load the video first
