### ISSUE TITLE
Horizon Lock being enabled when applying settings across items in render queue

### ISSUE THREAD

**Issue by mrnocreativity** [gyroflow/gyroflow#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.1.0

### What operating system are you using?

Mac OS Montery 12.4.0

### What GPU are you using?

Apple M1 Max

### What happened?

Steps to reproduce:

1. Open Gyroflow v1.1.0
2. Drag/drop a gopro file (5.3K, 4:3, 30fps, no hypersmooth) from your local hard drive (desktop folder) into the window. 
3. The file preview appears and stabilization is detected and applied. (OK)
4. Hit the combobox in the export button and select "add to render queue"
5. The render queue appears with your file in it (OK)
6. In finder, select your other gopro files from that same folder and drag them onto the render queue
7. The new files get added to the render queue (OK)
8. Right click one of the items in the render queue, select 'Edit'
9. The selected file preview appears (OK)
10. On the right hand side, look for the "horizon lock" field. It is selected (Not OK)
11. Unselect it
12. On the 'save button', hit the combobox and select "apply selected settings to other items in render queue"
13. A dialog appears to select which settings you want to copy over to the other items in the render queue. Almost all items are selected. Confirm that 'horizon lock' is selected. 
14. Hit apply
15. Hit the button to view the render queue
16. The render queue appears (OK)
17. Right click yet another item from the render queue, and select "Edit"
18. The file preview appears (OK)
19. On the right hand side, look for the 'Horizon lock' field. It is selected (Not OK)
20. Go back to the render queue and repeat steps 17-18-19

My conclusions 

1. It appears the horizon lock gets selected by default (something that I never used so I'm not sure why it would do that
2. When applying settings across the rest of the render queue, it seems the horizon lock values don't get carried over or they are ignored/overwritten
3. I'm not 100% sure if this is not a user error. Perhaps my understanding of how the 'apply settings to other items in the render queue' works is incorrect. If such is the case, feel free to correct me. 

Thanks for your hard work. I hope this helps.

**Comment by AdrianEddy** [comment]
Thanks, good catch! Fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
