### ISSUE TITLE
Non-symmetric lens option causes edges in frame when lens correction strength is 0%

### ISSUE THREAD

**Issue by avsaase** [gyroflow/gyroflow#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

599ab50515087bce9ba39118a709973693a92047

### What operating system are you using?

Windows 10

### What happened?

With the new asymmetrical lens option, there is a zoom bias to the lower left:
![image](https://user-images.githubusercontent.com/880421/178121947-47f76f3f-b59c-4a76-a59b-234249bc3a82.png)

When lens correction strength is set to 0%, black borders come into frame:
![image](https://user-images.githubusercontent.com/880421/178122184-9ad9b408-8951-4b32-bb4b-1338c0d23157.png)

This example is from a video from the Runcam 5 Orange using the XV setting and corresponding lens profile but I also tried it with `"input_horizontal_stretch": 1.0,` and the dimensions as if it was a normal 4K video, with the same result.

Here's a clip and `.gyroflow` file with synced gyro data: https://drive.google.com/drive/folders/1II7j7cD8n304s1ZmVXIiKFHtL8jGUE0w?usp=sharing

**Comment by avsaase** [comment]
Actually, I think the off-center zooming with 100% lens correction strength is not a bug and is just the result of the asymmetric lens. 

Stabilization toggled off:
![image](https://user-images.githubusercontent.com/880421/178124190-a61c8fd1-8f4e-4721-8f2c-753bdc7a227a.png)


Stabilization toggled on:
![image](https://user-images.githubusercontent.com/880421/178124198-c4d5f357-1767-4248-a09b-c0b8d980e857.png)

With zooming center offset X=10% and Y=-10% to use as much of the frame as possible and get the effect I expected when I opened this issue:
![image](https://user-images.githubusercontent.com/880421/178124233-74f4455f-7891-425a-91a3-2cadc88db791.png)

On the last still, there is a lot more FOV on the right and top but that's because the camera actually has more FOV in those directions (assuming the lens profile is correct). I guess the tolerances on this optics of the camera are terrible and everyone should make their own profile instead of using someone else's.

**Comment by VladimirP1** [comment]
Can confirm with 100% correction strength.

![image](https://user-images.githubusercontent.com/10977352/180457409-77fd26f3-0a70-422e-ae53-fdbcd67284a4.png)

Will upload the files soon

**Comment by VladimirP1** [comment]
Here's the link to the files https://drive.google.com/drive/folders/1VSRTcXCLzYgNRkPW5h3ndOUrJ8LaPz2R?usp=sharing

**Comment by VladimirP1** [comment]
I am stupid, I had no zooming selected

**Comment by AdrianEddy** [comment]
Fixed in 024755d13fd9c3fadcc55006067b07f7782a04a4
