### ISSUE TITLE
Allow batch exact placement of the sync points for auto sync.

### ISSUE THREAD

**Issue by ondrascz** [gyroflow/gyroflow#399]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Current situation: While using the auto sync Gyroflow puts given number of sync points evenly distributed across the video

To be situation: User is allowed to use a list of timestamps (or frame numbers) i.e. in form of .json file. Gyroflow will use those sync points for auto sync.

Why: This will mainly help Runcam 5 Orange users to mitigate the duplicate frames bug. I've been trying lots of methods to pre-process the video file to get rid of the duplicates, nothing gives as satisfying results as cleverly put sync points.

**Comment by AdrianEddy** [comment]
Done, here's a sample file, save with extension `.gyroflow` (it's a preset, so you can combine with other settings):
```
{
    "version": 2,
    "synchronization": {
        "custom_sync_timestamps": [
            1001.0,
            2002.0,
            5000.0,
            10010.0
        ]
    }
}
```
Will be available in gh599 once it finishes building
