### ISSUE TITLE
Crash if timestamp in "custom_sync_timestamps" is out of range of processed video file

### ISSUE THREAD

**Issue by ondrascz** [gyroflow/gyroflow#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.1.0 (gh600)

### What operating system are you using?

Windows 10

### What GPU are you using?

gtx 1050 Ti

### What happened?

First of all thank you for quickly adding feature request #399. It works almost perfectly as intended

I've prepared a .gyroflow with "custom_sync_timestamps" section.

```json
{
  "version": 2,
  "synchronization": {
    "custom_sync_timestamps": [
      29466,
      30500,
      62833,
      63866,
      96200,
      97233,
      129566,
      130600,
      162933,
      163966,
      196300,
      197333,
      229666,
      230700,
      263033,
      264066,
      296400,
      297433,
      329766,
      330800,
      363133,
      364166,
      396500,
      397533,
      429866,
      430900,
      463233,
      464266
  ]
  }
}
```

Once there is a timestamp that is outside of the processed video length Gyroflow crashes during auto sync. Gyroflow should ignore the timestamps not relevant for current video. The thing is that RC5 video files might be up to 8 minutes long, so I prepared timestamps covering the longest possible video. Of course most of the times the videos are shorter and I'd have to prepare the timestamps .gyroflow file manually.

One additional feature request (nice-to-have): Gyroflow should somehow indicate that the custom_sync_timestamps are loaded correctly. I.e. in the advanced section of the Synchronization panel (something like "12 custom sync points loaded") or in the chart by showing sync points "ghosts" before they are actually used for auto sync.

**Comment by AdrianEddy** [comment]
Fixed in latest dev build
