### ISSUE TITLE
Nvidia GeForce MX230 not supported?

### ISSUE THREAD

**Issue by mimixtz** [gyroflow/gyroflow#403]
Hi guys,

I'm trying to use Nvidia GeForce MX230 for rendering / exporting.
No matter which option I select, there is always a message ''GPU encoder failed to initialize..... rendering is done on the CPU.....''.
Is my graphic card just to bad / too low budged / too old?
Thank you very much in advance for any answer / opinion.

**Comment by AdrianEddy** [comment]
Yes, it's not supported. It uses GP108 chipset: https://www.notebookcheck.net/NVIDIA-GeForce-MX230-Graphics-Card.382351.0.html and it doesn't have any HW acceleration available
https://en.wikipedia.org/wiki/Nvidia_NVENC
