### ISSUE TITLE
Watch folder for automated processing

### ISSUE THREAD

**Issue by markifi** [gyroflow/gyroflow#404]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Implementing a "hot folder" or watch folder, where gyroflow automatically processes the files dropped into said folder using a previously set preset would be a good idea. For times when pristine manually adjusted footage is not necessary. It would esentially make stabilising an "invisible" step, even going so far that it could be done remotely with a NAS and a phone, once your configuration for your camera is okay-ish.

**Comment by AdrianEddy** [comment]
Done in f1df5a03c8ba5962adf56323f04845b7f3d94c17 
https://gyroflow.xyz/devbuild/?autodownload

Usage from CLI:
`Gyroflow.exe --watch "C:/test_folder/" --preset "C:/test_preset.gyroflow"`
or eg.
`Gyroflow.exe --watch "C:/test_folder/" --preset "{ 'version': 2, 'stabilization': { 'fov': 1.5 }, 'output': { 'codec': 'H.264/AVC', 'bitrate': 100 } }"`
