### ISSUE TITLE
one session only (Linux)

### ISSUE THREAD

**Issue by nightflasher** [gyroflow/gyroflow#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.1.0 (gh570)

### What operating system are you using?

ubuntu 22.04 LTS

### What GPU are you using?

AMD ATI Radeon R7 530 | INTEL UHD 620

### What happened?

After editing/stabilizing a video (runcam thumb v1), i can't open another video for editing. Have to close the Programm after every edited video.

**Comment by JoshuaNitschke** [comment]
@AdrianEddy this is my next one, starting it next weekend.

**Comment by JoshuaNitschke** [comment]
So i am able to reproduce the issue.  It seems you have to have started playing a video for the issue to occure as I can switch videos mulitple time.

Steps to reproduce
1) Load 
2) Click play and let the video play
3) Observe you cannot load another vidoe, it just hangs.

The process dies here:
https://github.com/AdrianEddy/qml-video-rs/blob/2c642501b7704ee278331f272f9c0efd66e630f4/src/video_player.rs#L41

**Comment by AdrianEddy** [comment]
@wang-bin any idea about this?

**Comment by nightflasher** [comment]
I need to play back the video, to see if the result satisfies my desire.

**Comment by JoshuaNitschke** [comment]
@nightflasher obviously, I was just giving better details on how to reproduce the error so that @wang-bin can troubleshoot, the error is occurring from his library.

**Comment by AdrianEddy** [comment]
actually there is one more function between mdk there:
```cpp
void MDKPlayer::setUrl(const QUrl &url) {
    m_overrideFps = 0.0;
    if (!m_item) {
        m_pendingUrl = url;
        return;
    }
    destroyPlayer();
    initPlayer();

    QString path = url.toLocalFile();
    m_player->setMedia(qUtf8Printable(path));
    m_player->prepare();
}
```

can you add logs here and check on which line it hangs there?

**Comment by JoshuaNitschke** [comment]
@AdrianEddy - seems to have something to do with resetting the unique pointer?  I have no experience with C++ and I did some googling, but nothing really stood out to me.  I tried removing it and it seemed to let me switch videos a few times, but then I had the same issue again where it didn't progress passed the assignment `m_player = std::make_unique<mdk::Player>();`

![image](https://user-images.githubusercontent.com/33307206/183268721-35734056-6182-4a36-8b4a-a635cae78aec.png)

**Comment by AdrianEddy** [comment]
So the problem is in the destructor of `Player` in mdk-sdk. @wang-bin?

**Comment by AdrianEddy** [comment]
@JoshuaNitschke can you try adding `m_player->waitFor(mdk::PlaybackState::Stopped);` in `stop()`?
![image](https://user-images.githubusercontent.com/3849067/183291315-2b9cdd98-5100-4eda-bf0c-38ffa9825e15.png)

**Comment by JoshuaNitschke** [comment]
Yes, will do it later today 👍

**Comment by JoshuaNitschke** [comment]
@AdrianEddy unfortunately the issue persists, although it seemed better?  
https://vimeo.com/737429743/7f4489e738

I added the wait on pause and play as well just for fun.  I have yet to see it fail to load a new video while the player is in play mode - might be worth digging into what is happening after clicking pause.

**Comment by wang-bin** [comment]
gh570 crashes before showing the main window on my laptop, the log says no opencl. So I tested the nightly build, open a video, export, then open another file, it works fine

**Comment by AdrianEddy** [comment]
It could be related to a particular distro or decoder. @JoshuaNitschke can you post entire gyroflow.log file? after this happens? we need to see which "video.decoder" mdk used etc. also what linux distro are you using?

**Comment by AdrianEddy** [comment]
@nightflasher  and @JoshuaNitschke  please check the latest build https://gyroflow.xyz/devbuild/?autodownload

**Comment by JoshuaNitschke** [comment]
@AdrianEddy I'll check on the weekend, sorry that I didn't have time to get you the logs - I checked your changes, you were able to verify it was an issue with releasing the pointer?

**Comment by nightflasher** [comment]
AppImage doesn't work for me (dry start ./Gyroflow-linux64.AppImage and dedicated grfx card DRI_PRIME=1 ./Gyroflow-linux64.AppImage - see attached dumps) the extracted .tar.gz does work, but after playback of a video (loaded .gyroflow file) it crashes - no it locks up/freeze and i force quit.
[gyroflow_crash_dumps.zip](https://github.com/gyroflow/gyroflow/files/9303623/gyroflow_crash_dumps.zip)

**Comment by AdrianEddy** [comment]
Does this still happen in latest dev build? https://gyroflow.xyz/devbuild/?autodownload
