### ISSUE TITLE
Adobe plugin

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#41]
As a first version it can just load the .gyroflow file, with a button to open a separate Gyroflow app with that file so user can adjust all settings he wants in the UI and then pass the processing to the video editor. Later we can add fancier native UIs for the plugin

https://github.com/virtualritz/aftereffects-sys

**Comment by AntoineFacq** [comment]
Hey @AdrianEddy, thanks for all the work you push for this, the community is so grateful to you guys! Is there any roadmap defined for the premiere plugin?

**Comment by AdrianEddy** [comment]
Adobe plugin is in progress and is already somewhat functional (although only in After Effects)
The development is slow, because Adobe plugin API is very hard to work with

you can download the binary for AE from this repo, in Actions tab
https://github.com/gyroflow/gyroflow-plugins

**Comment by SebDrewett** [comment]
Thanks so much Adrian for putting in this hard work, I'm super excited for this to become available to Adobe, is the above a beta?

**Comment by AdrianEddy** [comment]
it's not even an alpha, but it works

**Comment by AdrianEddy** [comment]
just copy the Gyroflow.aex to the adobe plugins folder (`C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore`)

**Comment by iagvisuals** [comment]
Hi AdrianEddy,

First of all, thank you for your work !

I am sorry, I'm new here... I just don't find the file Gyroflow.aex... 

I downloaded the file at this link : https://github.com/gyroflow/gyroflow-plugins

But nothing inside, so I guess it's somewhere else, can you please help me ?

I wish you a nice day !

**Comment by AdrianEddy** [comment]
It's on the "Actions" tab
It's currently only usable in AE, don't expect it working in Premiere yet
It's also not finished, so there will be bugs, but you can already try it in AE

**Comment by AdrianEddy** [comment]
Click the first one ("Update to latest core", last week) and files to download will be on the bottom

**Comment by iagvisuals** [comment]
The only thing I didn't check on the whole website...

Thanks a lot for your time, appreciate it !

Wishing you the best, again !

**Comment by AdrianEddy** [comment]
Give the adobe plugin a try, it's almost finished

https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-windows.zip
https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-macos.zip

**Comment by iagvisuals** [comment]
Hi @AdrianEddy !

Thanks again for your work, it's really good !

Just to let you know and it's just for information, I'm working with vertical video (9:16) and I got problem to stabilize.

Otherwise and except this little thing, before this version that you just sent, your work was already really good !

Thanks and have a nice day !

**Comment by iagvisuals** [comment]
Yes yes, I checked this aspect about the output. (I mainly work on After Effect)

I shoot in vertical 4K, so 2160 x 3840 with a Sony A 7 IV.

When I edit, my composition is in vertical full HD, cause I export for social networks, so 1080 x 1920. Then I reduce the size of my videos either automatically or manually by modifying the size to 50% to fit in the screen.

The problem, I think, was that Gyroflow thought my videos were landscape when I tried to stabilize them. But it was perfectly working with the App.

I finish to work in an hour, and I will try to send you examples. But i'm gonna test the new version as well !

**Comment by eliasacab** [comment]
Is it still only compatible with After Effects and not Premiere Pro? Copied the plugin to the MediaCore folder but can't get it to show in the Effects panel in Premiere Pro. Thanks

**Comment by eliasacab** [comment]
> Give the adobe plugin a try, it's almost finished
> 
> https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-windows.zip https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-macos.zip

Is it still only compatible with After Effects and not Premiere Pro? Copied the plugin to the MediaCore folder but can't get it to show in the Effects panel in Premiere Pro. Thanks

**Comment by AdrianEddy** [comment]
it works in Premiere too, you should have `C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\Gyroflow-Adobe-windows.aex`

**Comment by eliasacab** [comment]
I'm on Mac. I copied Gyroflow.plugin from the dmg to Library>Application Support>Adobe>Common>Plug-ins>7.0>MediaCore. I've restarted PremierePro (24.5) several times and it doesn't show under effects when I search for Gyroflow. It does in After Effects (Mac) but it crashes AE when I apply it to a clip (Braw clip).

**Comment by AdrianEddy** [comment]
indeed there's something wrong on macOS, I'll try to fix it tomorrow

**Comment by AdrianEddy** [comment]
Fixed, same links

https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-windows.zip https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-macos.zip

**Comment by eliasacab** [comment]
YES! It's working now! Blackmagic stabilization in Premiere Pro! Don't have to use Davinci Resolve just for stabilization anymore, thanks a lot!

**Comment by iagvisuals** [comment]
> what's the exact problem? can you share more details? Premiere or After effects? what's the camera and timeline dimensions? Does it stabilize well in the Gyroflow app? Also, check the "Output size" parameter group Vertical video should be supported normally.

Hello @AdrianEddy !

Sorry for the delay, here are an example with your new version :
![image](https://github.com/user-attachments/assets/dba3401d-e972-4ef3-b724-58529037cf6e)

And here when I disabled the FX GyroFlow :
![image](https://github.com/user-attachments/assets/dfd9daf7-0d24-4514-806a-ee56c0798029)

And I did many tests on the settings, but nothing to do. 
Here is when I disabled the stab overview :
![image](https://github.com/user-attachments/assets/0a5fc647-2c19-444c-b9e6-f9a9de20b924)

Tell me if I can give your more information and help you !

**Comment by AdrianEddy** [comment]
Download latest one https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-Adobe-windows.zip
after applying the plugin click "Reload project" button
Then you will also probably need to set "Video rotation" to 90 or -90, and maybe "Input rotation" needs to be adjusted too. In general I tested vertical Sony videos and they work, you just have to set the rotation values correctly

**Comment by AdrianEddy** [comment]
I consider the Adobe plugin finished, download from here https://gyroflow.xyz/devbuild/ and please report any bugs you encounter
