### ISSUE TITLE
Feature request: Actions after rendering is done

### ISSUE THREAD

**Issue by p-masek** [gyroflow/gyroflow#413]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Is it possible to add Gyroflow actions after rendering is done? I mean especially after long renderings would be nice to have similar options as we can see in eg. Handbreak... like Shutdown of computer.
![image](https://user-images.githubusercontent.com/105239360/182041360-d1bd0040-ba8c-4c05-9d08-d38f0b0ca3da.png)

**Comment by AdrianEddy** [comment]
Done in f14dca51c3a3f49082622441a5a4ef380617950f
https://gyroflow.xyz/devbuild/?autodownload
