### ISSUE TITLE
Video does not load on M1 since rc5 (shows and renders only black screen with sound)

### ISSUE THREAD

**Issue by leitmanr** [gyroflow/gyroflow#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [x] I have tried the latest build

### Gyroflow version

1.1.0 and also last build

### What operating system are you using?

macOS Monterey 12.4

### What GPU are you using?

M1

### What happened?

Since 1.1.0 release GF does not load GP10 video files. Sound is playing but video is black. 1.0 rc5 works fine.
1.1.0 and also last build shows the same bad behaviour see screenshot
<img width="1440" alt="Screenshot 2022-08-03 at 23 03 19" src="https://user-images.githubusercontent.com/99039827/182713120-c460037c-aef2-461d-97ee-fd9b8fd63efc.png">

**Comment by AdrianEddy** [comment]
Change smoothing method to "Default" (methods were changed since rc5 and it checks the wrong one by default)
