### ISSUE TITLE
CinemDNG support

### ISSUE THREAD

**Issue by toferzim** [gyroflow/gyroflow#424]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hello! Is there a way to include a CinemaDNG support?

**Comment by AdrianEddy** [comment]
I can get CinemaDNG playback somewhat working, but ffmpeg doesn't support rendering CinemaDNG and it doesn't support RAW formats (so no rendering of any kind), so the only use case would be to combine with DaVinci Resolve plugin

**Comment by AdrianEddy** [comment]
CinemaDNG playback is supported in latest dev build. The colors are not accurate, but that's an issue in ffmpeg. It works for the autosync and you should use it with DaVinci Resolve plugin.
