### ISSUE TITLE
Quitting/crashing after clicking 'export'

### ISSUE THREAD

**Issue by Iroquoi5pliskin** [gyroflow/gyroflow#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.1.0

### What operating system are you using?

macOS Catalina 10.15.7

### What happened?

Gyroflow's worked fine for me in the earlier version, but just updated to 1.1.0 & now after I select 'export' after importing video, setting lens, importing motion data, auto-syncing. All other settings left standard.

As soon as I press export, it looks like it's going to start rendering - but freezes & closes the application instead.

**Comment by AdrianEddy** [comment]
Please include gyroflow.log (Open package contents->Contents->MacOS) and try the latest dev build https://gyroflow.xyz/devbuild/?autodownload

**Comment by Iroquoi5pliskin** [comment]
Thanks.

I've downloaded that version. Still getting the same issue. Log attached.

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/9331136/gyroflow.log)

**Comment by AdrianEddy** [comment]
Can you please test if this also happens when you uncheck `Advanced` -> `Use GPU decoding`
Please also try to choose different devices in `Advanced` -> `Device for video processing` and `Export` -> `Device for rendering` and let me know

**Comment by Iroquoi5pliskin** [comment]
Absolutely fantastic.

The GPU decoding setting still crashed the program, but changing the device for rendering setting sorted the crashing issue.

All working fine now. Thanks so much for your help.
