### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by Magadeev** [gyroflow/gyroflow#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.1.0

### What operating system are you using?

Windows 10 x64

### What GPU are you using?

Intel 4400

### What happened?

does not start
![error](https://user-images.githubusercontent.com/11613346/185397134-22671e7b-b3cd-4a18-b075-9793d3f077a6.JPG)

### Relevant log output

```shell
12:37:54 [INFO] Could not load the Qt platform plugin "windows" in "" even though it was found.
12:37:54 [ERROR] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: windows.

Для продолжения нажмите любую клавишу . . .
```

**Comment by AdrianEddy** [comment]
Install https://aka.ms/vs/17/release/vc_redist.x64.exe and install all windows updates. Can you show me a screenshot of System info from control panel?

**Comment by Magadeev** [comment]
vc_redist.x64.exe installed. The update cannot be installed because the corporate version of Windows
![system](https://user-images.githubusercontent.com/11613346/185401123-d557bf2f-4126-4257-8c57-a5ea75597e92.JPG)

**Comment by Magadeev** [comment]
1511 version =D

**Comment by AdrianEddy** [comment]
Yeah so it's not supported, you have to upgrade the Windows version or use a different computer.
