### ISSUE TITLE
Filter gyro data locally

### ISSUE THREAD

**Issue by 5ur3** [gyroflow/gyroflow#436]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Sometimes my old Gopro hero 5 session writes crappy gyro data, which makes stabbing inapplicable. On these regions with bad gyro data, I would rather prefer no stabilization at all, because stabilized footage looks worse than raw. I could cut the footage into parts and stabialize only those with good gyro data, but dynamic cropping makes seamless concatenation of those parts almost impossible. 

I would like to set gyro lowpass filter locally for such bad gyro regions (e.g. stab more or less on a specific region of footage), or zero gyro data on a local region completely. I believe this would allow me to choose what parts of footage I want stabilized and what parts I want rather more raw. 

On the screenshot I have trim-selected a region with bad gyro data that I don't want to be stabbed:

![image](https://user-images.githubusercontent.com/43802815/186536072-ba23f1d4-b2c7-4bbc-9bec-e8b3dc34fb64.png)

Here is the same trim before stabilization:

https://user-images.githubusercontent.com/43802815/186536250-a8b0f629-49d8-4512-9f1b-16015f7770df.mp4

And here is the trim with after stabilization:

https://user-images.githubusercontent.com/43802815/186536301-e2f700be-b451-494c-ba87-7555bce968a1.mp4

Other than this particular moment in the video, stabilization works well as intended.

Such regions are usually about 5 seconds long, but I think this may vary from gyro source to gyro source. 

I believe that this issue exists for other gyro sources, not just for Gopro hero 5 session.

**Comment by AdrianEddy** [comment]
That's exactly what keyframes are for,
You can simply keyframe the Smoothness on that part to 0, then bring it back up right after that part.
Right click on the slider-> Enable keyframing, and then change value at the video time you want

Use latest dev build: https://gyroflow.xyz/devbuild/?autodownload
