### ISSUE TITLE
Normalize speed

### ISSUE THREAD

**Issue by eortegaz** [gyroflow/gyroflow#438]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Is there a way to control speed based on telemetry data? Automatic speed ramping to make speed constant. It'd be an incredible feature.

**Comment by AdrianEddy** [comment]
I believe this is the same as #142, it may be implemented in the future but it's not trivial and we need to do #31 first.
Please follow #142 for the progress

**Comment by eortegaz** [comment]
> I believe this is the same as #142, it may be implemented in the future but it's not trivial and we need to do #31 first. Please follow #142 for the progress

Thanks for your quick reply. Looks like #31 is now done. Speed normalization is still low-priority but I hope it's a feature we'll see in the future.
