### ISSUE TITLE
High Sierra Support?

### ISSUE THREAD

**Issue by kapsolas** [gyroflow/gyroflow#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.2.0

### What operating system are you using?

macOS High Sierra 10.13.6

### What GPU are you using?

ATI Radeon HD 4850 512 MB

### What happened?

The application did not run successfully.
Per the Info.plist file any MacOS starting with 10.11 and after are supported.

My OS is 10.13. I received this error when executing directly the gyroflow executable via the command line.

Looks like it is looking for a library that is not available on 10.13?? Dark/Light mode related?

/Applications/Gyroflow.app/Contents/MacOS/gyroflow ; exit;
dyld: Symbol not found: _NSAppearanceNameDarkAqua
  Referenced from: /Applications/Gyroflow.app/Contents/MacOS/../Frameworks/QtCore.framework/Versions/A/QtCore (which was built for Mac OS X 10.14)
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Gyroflow.app/Contents/MacOS/../Frameworks/QtCore.framework/Versions/A/QtCore

**Comment by AdrianEddy** [comment]
It's out of our control, minimum supported MacOS is 10.14
