### ISSUE TITLE
Gopro Hero 8 Linear footage starts with zoom in

### ISSUE THREAD

**Issue by B-nutze-RR** [gyroflow/gyroflow#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.2 and up to gh711 tested but 1.1 is fine

### What operating system are you using?

win10

### What GPU are you using?

Nvidia

### What happened?

Hero a sample starts fully zoomed in and the quaternions graph shows a dip - in 1.1 the dip is not present
<img width="1651" alt="Screenshot 2022-08-28 011122" src="https://user-images.githubusercontent.com/49525731/187051070-8d71bfdf-9527-462d-8783-b9fe7e4d102c.png">
<img width="1667" alt="Screenshot 2022-08-28 011153" src="https://user-images.githubusercontent.com/49525731/187051071-3245f784-c92d-471b-b5bd-bb52393e959d.png">
.

### Relevant log output

```shell
video:
https://disk.yandex.ru/i/-pfZh7_vVUnGsA
```

**Comment by AdrianEddy** [comment]
@VladimirP1 I believe this is due to QuaternionConverter, can you take a look? If it's too hard to fix, we can disable quaternion converter when horizon lock is not being used

**Comment by VladimirP1** [comment]
Should be fixed in #445
