### ISSUE TITLE
Zoom percentage doesn't update if experimental Zero-copy GPU preview is enabled

### ISSUE THREAD

**Issue by Pavelo77** [gyroflow/gyroflow#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.2.0

### What operating system are you using?

Window 10 Pro 64bit

### What GPU are you using?

GTX 1080

### What happened?

If experimental zero-copy GPU preview is enabled the zoom percentage on the bottom left of the image freezes and doesn't update while playing the video, quite useful to see where the highest zoom is to tweak the smoothing and get away with least zoom possible. It worked some builds ago (not remember which) but since 1.1.0 it's broken again.

**Comment by AdrianEddy** [comment]
Fixed in 9ed3da9ff2fde637ab8f23b653c5892577d34de0 https://gyroflow.xyz/devbuild/?autodownload
