### ISSUE TITLE
DJI AVATA Combining multiple files over 3.5GB

### ISSUE THREAD

**Issue by twtps0328** [gyroflow/gyroflow#448]
Hi there,

If working with DJI AVATA split files , How can we Combining .mp4 or .gyroflow ?

**Comment by AdrianEddy** [comment]
If your file is split at 6:00, Gyroflow should detect it automatically if you load the first file.
If it's not, you can merge the files manually using https://github.com/gyroflow/mp4-merge (download exe and drag&drop your videos on the mp4_merge exe)

We're working with DJI to provide a better way to automatically detect the files

**Comment by AdrianEddy** [comment]
In latest dev build, you can simply drag&drop all parts of the video into Gyroflow, and it will ask if you want to merge them
https://gyroflow.xyz/devbuild/?autodownload
![image](https://user-images.githubusercontent.com/3849067/187494977-77789bf5-ffcd-4aa8-86f1-33d2e2c7a659.png)
