### ISSUE TITLE
aac TYPE_FIL: Input buffer exhausted before END element found

### ISSUE THREAD

**Issue by B-nutze-RR** [gyroflow/gyroflow#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

GH720

### What operating system are you using?

Win10

### What GPU are you using?

Nvidia 3070

### What happened?

2 "Auto joined" DJI Action 2 4K 30 clips  ( renamed to DJI_0001_001.....0001_002 ) do not export in H254/H265 with audio.
Ther render process ends with this Error:
<img width="896" alt="aac_export_joined" src="https://user-images.githubusercontent.com/49525731/187976445-e00d8bcd-a804-4a4c-8001-e6ac31230f78.png">

Single files export with audio works fine and the Audio in the joined file seems also fine.

### Relevant log output

```shell
16:50:29 [DEBUG] (2) gyroflow::rendering: video_codec: Some("h264_nvenc"), processing_order: PreConversion
16:50:29 [DEBUG] (2) gyroflow::rendering: start_us: 26508999, render_duration: 267217, render_frame_count: 16017
16:50:29 [DEBUG] (2) gyroflow::rendering::ffmpeg_processor: Codec formats: [YUV420P, NV12, P010LE, YUV444P, P016LE, YUV444P16LE, BGRZ, BGRA, RGBZ, RGBA, X2RGB10LE, X2BGR10LE, GBRP, GBRP16LE, CUDA, D3D11]
16:50:31 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Hardware transfer formats from GPU: Some([NV12])
16:50:31 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: hw_device_type: Some(AV_HWDEVICE_TYPE_CUDA), encoder_pixel_format: Some(NV12)
16:50:31 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Setting output pixel format: NV12, color range: MPEG
16:50:31 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: hw_device_type Some(AV_HWDEVICE_TYPE_CUDA)
16:50:31 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: Setting hw_device_ctx 0x21aecd054c0
[h264_nvenc @ 0000021AEB953540] Loaded Nvenc version 11.1
[aac @ 0000021BB0783C80] TYPE_FIL: Input buffer exhausted before END element found
[aac @ 0000021BB0780880] Qavg: 65503.062
[aac @ 0000021BB0780880] 2 frames left in the queue on closing
```

**Comment by AdrianEddy** [comment]
Fixed in https://github.com/gyroflow/mp4-merge/commit/9ef7e9973bbe1a9f8ae5694a904c08d3d523202b
https://gyroflow.xyz/devbuild/?autodownload
