### ISSUE TITLE
Bug d'affichage prévisualisation

### ISSUE THREAD

**Issue by siegtophe** [gyroflow/gyroflow#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.2.0

### What operating system are you using?

Windows

### What happened?

Lorsque j'ouvre un fichier vidéo, l'écran est noir et lorsque je bouge le curseur sur le time code, la valeur de zoom change et passe à 100000%
Même en changeant le FOV le zoom ne change pas.

**Comment by AdrianEddy** [comment]
Change smoothing method to `Default`, or use `Advanced`->`Reset all settings to default`.
![image](https://user-images.githubusercontent.com/3849067/188677417-09d89f4e-da9f-48dc-be1d-76ae86553239.png)
![image](https://user-images.githubusercontent.com/3849067/188677589-e8212e91-5423-4bdd-93f6-102f891663d5.png)
If that doesn't help, try the latest dev build https://gyroflow.xyz/devbuild/?autodownload

**Comment by siegtophe** [comment]
Merci pour ton aide. Il a fallu que je fasse un reset de tous les paramètres car le premier conseil n'a pas fonctionné.
