### ISSUE TITLE
Use Gyroflow for hand held cam stabilization? 

### ISSUE THREAD

**Issue by morbificagent** [gyroflow/gyroflow#457]
Hi there,
Actually I am trying to use Gyroflow to stabilize footage from an dslr which was hand held, using an runcam as source for the gyro data.

In general its working but the results are not like I hoped.

All micro wobble are Still there and only big movements are respected.

Is the source of gyro data to bad?

Can't the software used for this?

Many thanks

**Comment by AdrianEddy** [comment]
It can be used, but you need to make sure your gyro data corresponds to the actual movement. There's a lot that goes into this:
- Make sure your mount is absolutely rigid and as close as possible to the camera
- Disable any OIS and/or other stabilization in DSLR
- You didn't specify which Runcam, but Thumb is not a great quality, Thumb Pro will work better, or ideally one of DIY gyro loggers like [esp-gyrologger](https://github.com/VladimirP1/esp-gyrologger) or [flowshutter](https://github.com/gyroflow/flowshutter)
- Make sure you use rolling shutter correction with correct value, make sure your lens profile is accurate (ideally make your own) and make sure your offsets are correct. Also you can play with gyro rotation, as it's likely your gyro source is not 100% perfectly aligned with the dslr sensor. All of these you can do/adjust manually using the gyro chart, zooming in and making sure the gyro lines match with visual analysis lines


It's not an issue with Gyroflow so I'm closing this, you can get more help and details in the [Discord](https://discord.gg/WfxZZXjpke) server
