### ISSUE TITLE
Several translations need correction

### ISSUE THREAD

**Issue by lukegluke** [gyroflow/gyroflow#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1062cc5d81e6a252e311820b684ad8b03c5e142e

### What operating system are you using?

Doesn't matter

### What happened?

While contributing to translation notice several related issues in code:

Here:
https://github.com/gyroflow/gyroflow/blob/1062cc5d81e6a252e311820b684ad8b03c5e142e/src/ui/VideoArea.qml#L144
and here:
https://github.com/gyroflow/gyroflow/blob/1062cc5d81e6a252e311820b684ad8b03c5e142e/src/ui/VideoArea.qml#L166
qsTr format strings have two arguments, but get only one.

@AdrianEddy, I don't know your original intents in this parts, so post it as an issue.

**Comment by AdrianEddy** [comment]
They are correct, first is replaced in these lines, and that replaces %2 with %1. This second one is then replaced in src/ui/components/LoaderOverlay.qml:78

It's not clear from the source that it does that, you're right, but it's working correctly
