### ISSUE TITLE
Gyroflow desktop icon not visible on dark wallpaper

### ISSUE THREAD

**Issue by WizzX-FPV** [gyroflow/gyroflow#467]
If dark (black) wallpaper is used, Gyroflow icon is not visible as it is black on transparent.
![unknown](https://user-images.githubusercontent.com/40316777/190991796-d32f32f1-e41a-4e1c-8300-17bdd61d4438.png)

I recommend to add white glow or border around it.
See possible icon example attached

[gyroflow1.zip](https://github.com/gyroflow/gyroflow/files/9597829/gyroflow1.zip)

**Comment by AdrianEddy** [comment]
thanks, updated in 8705680cdeab25cc3be204033312470fcafb0c7d
