### ISSUE TITLE
Fix filename when joining videos

### ISSUE THREAD

**Issue by dngrlux** [gyroflow/gyroflow#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

Gyroflow v1.2.0 (gh764)

### What operating system are you using?

macOS Monterey 12.5.1

### What GPU are you using?

Apple M1 Max Integrated

### What happened?

When joining multiple video clips together, the resulting filename is
FILENAME.MP4_joined.mp4

The original filename extension should be stripped prior to appending the "_joined.ext", resulting in
FILENAME_joined.mp4

It appears that when _not_ joining files, there is already code in use to do this properly for "_stabilized.ext".

**Comment by AdrianEddy** [comment]
Fixed in 7bd6982bc099665f4644977426a9fa8eac5217d0
