### ISSUE TITLE
Add (dynamic) zoom graph to XYZ(W) plots

### ISSUE THREAD

**Issue by sassysander** [gyroflow/gyroflow#471]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Adding a (dynamic) zoom graph to the XYZ(W) plots would help tremendously with determining exactly where the most amount of zoom is applied.

**Comment by AdrianEddy** [comment]
Done in c122792481f0d862e1884e13be7b6204f7607ebb https://gyroflow.xyz/devbuild/?autodownload
