### ISSUE TITLE
3D Depth sensing cameras / Lidar sensor / ToF sensor

### ISSUE THREAD

**Issue by eirasys** [gyroflow/gyroflow#475]
The stabilizations are so astonishing that it's impossible not to think the possible results if we use a camera with 3D depth sensing technology, with lidar or ToF. Imagine that instead of rendering the stabilized video you can be rendering an animated colorful and stabilized 3D surface of whatever you point the camera. Gyroflow can surely evolve to a 4D scanner?! A 3D scanner with animation. Just a suggestion to think of.

**Comment by AdrianEddy** [comment]
Thanks for the suggestion but I'm afraid that's not going to happen, it would have to be a completely different app, the whole stabilization process and algorithms would be totally different. I don't have a need for anything like this and I won't be working on it. Unless someone contributes a PR to do that, it's not going to be implemented in Gyroflow.
