### ISSUE TITLE
Rendering on CUDA returns an error

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#48]
CUDA sometimes fails to initialize the GPU encoder. Usually restarting the app works so the recommended workaround is to export `.gyroflow` file, restart the app, load the gyroflow file and try rendering again. Restarting a computer might also help as a last resort

Need to investigate why that happens and if there's a way to prevent it

**Comment by pkbannutz** [comment]
I tried this.. I still cannot export.. or i just don't know who to load the gyroflow file. but if i add the video. it says it detecs a gyroflow file and if i wanna use it. i press yes. i hope that's what you mean by "load gyroflow file" but after still i cannot render.. same problem. I restarted the computer too.. I also moved the folder in Program files and opened it with Run as Administrator. not sure why is happening or what else to try. I only work if i export on prores.. but that take 3h for a 2m clip
