### ISSUE TITLE
Rendering timers reset if options adjusted

### ISSUE THREAD

**Issue by neutronstorm** [gyroflow/gyroflow#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.3.0-rc (gh805)

### What operating system are you using?

Window 11

### What happened?

Minor Issue. When rendering with the "Elapsed" and time "Remaining" in the center of the window, if you click on something in the left pane such as "Low pass filter", the Elapsed time and Remaining time reset.

**Comment by AdrianEddy** [comment]
Fixed in e996d548258eb8c782f45780e2ff8d214f699565
