### ISSUE TITLE
PC crashes on exporting using GPU

### ISSUE THREAD

**Issue by avib99** [gyroflow/gyroflow#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.3.0

### What operating system are you using?

Win 10

### What GPU are you using?

RTX 2080Ti

### What happened?

PC crashes while exporting using GPU, causing a black screen and pc fans running full blast.

**Comment by AdrianEddy** [comment]
Do you have latest GPU drivers installed and latest windows updates? Does it happen with all export codecs?

**Comment by AdrianEddy** [comment]
Please include gyroflow.log file (created next to Gyroflow.exe) after it crashes

**Comment by AdrianEddy** [comment]
I believe this is fixed in latest dev build, please reopen if it still happens https://gyroflow.xyz/devbuild/?autodownload
