### ISSUE TITLE
zoom center offset adds black bars to the output

### ISSUE THREAD

**Issue by dronotron** [gyroflow/gyroflow#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3.0

### What operating system are you using?

mac os Big Sur

### What GPU are you using?

Mac M1 

### What happened?

changing the zooming centre offsets looks as expected on the preview but on the output it shows a black bar as the offset. In this example I added 6% offset to the Y axis and in shows a black bar at the bottom on the output. on the preview it looks fine
![Captura de Pantalla 2022-11-06 a la(s) 23 37 37](https://user-images.githubusercontent.com/69435329/200228330-488cf127-aa8e-43c5-83c5-40e2132bff96.jpg)

**Comment by AdrianEddy** [comment]
Fixed in 34e85fc8d54b5fa6d3923ea8a96e4bee370b657c. Use latest dev build https://gyroflow.xyz/devbuild/?autodownload
