### ISSUE TITLE
Please add Yes/Rename/No ALL button in render queue

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#502]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

While a valuable feature it becomes a bit impractical with hundreds of file in the queue. Could we get a preset or apply to all feature? Thanks.

![image](https://user-images.githubusercontent.com/71881005/200941215-29bdab73-c099-4492-9a1b-fed6da6264da.png)

**Comment by hdosys** [comment]
In the meantime, a hidden "don't ask for overwrite confirmation" flag in `default.gyroflow` would be very helpful. Thank you for your time and work.

**Comment by AdrianEddy** [comment]
Done in e3dfd4782c03bcfafdab5fd8bb6bf0729dfc58f4 https://gyroflow.xyz/devbuild/?autodownload

**Comment by User-3090** [comment]
You're such an amazing dev. I just though about how to best implement it UI wise and that we need a way to specify the default export mode as well and you just nailed it overnight.

Thanks man!

![image](https://user-images.githubusercontent.com/71881005/201529472-e9c7393c-ea1b-4846-b979-65d267468ea2.png)
