### ISSUE TITLE
Allow render queue to be cleared

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#506]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Maybe it's obvious, but I haven't found an easy way to clear the render queue when a previous render has been paused. Contents are then persistent during app restart without an obvious way (for me) to reset the queue and start over.

**Comment by AdrianEddy** [comment]
Done in cf3fa23a82e57c12c380f8bfa9a1178fc455f278
