### ISSUE TITLE
Allow home/end keys to reliably navigate to trim range boundaries

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#507]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

On Windows, End key works most of the time, but sometimes also jumps to the start of the trim range. Home key seems to do nothing. It's would be convenient in particular for setting key frames at the trim range boundaries.

**Comment by AdrianEddy** [comment]
Fixed in 2f194e5f177e1dd23c53712a206fed21a581d3c9

**Comment by User-3090** [comment]
Works perfect
