### ISSUE TITLE
Allow auto/default easing of keyframe transitions

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#508]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Easing key frame transitions for a larger set of clips is currently a bit tedious. Could we get a auto/default ease in/out option and or a keyboard shortcut to add or remove easing for all existing key frames?

**Comment by AdrianEddy** [comment]
I just enabled them by default, I think it makes more sense to ease all keyframes and then only uncheck the ones which you don't want

**Comment by User-3090** [comment]
Thanks!
