### ISSUE TITLE
Lock horizon ignored in default.gyroflow

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

867

### What operating system are you using?

Win10

### What GPU are you using?

3090

### What happened?

Lock horizon ignored in default.gyroflow. Please provide a way to enable it by default.

**Comment by AdrianEddy** [comment]
It works fine for me, can you double check and attach your `default.gyroflow` file?

**Comment by AdrianEddy** [comment]
Fixed in 2b358e48a0d750f930809f1d0984b2827bcfb7fc
