### ISSUE TITLE
Allow modal "OK" dialogs to be disabled.

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#513]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

There are some modal UI dialogs that confirm that things went OK, such as saving a project file. Please provide a way to disable these or display them in a non blocking way or allow them to be acknowledged using the keyboard (enter key).

**Comment by AdrianEddy** [comment]
Done in 822b1a0d04e207f5e4a7d7a8bfe056283297a132
