### ISSUE TITLE
Change video output file name to match .gyroflow file when renaming .gyroflow file

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#515]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

![image](https://user-images.githubusercontent.com/71881005/202757407-40b1cf12-ca03-4566-8fd5-96d4fc535165.png)

The most common use case for having multiple .gyroflow files per input file is probably having multiple trim ranges that should render to separate files. Currently output files have to be adjusted manually when renaming the .gyroflow file.

**Comment by AdrianEddy** [comment]
Done in 250d120158fd97aacbb33f6dbcfb00e251939a58
