### ISSUE TITLE
gh885+ makes it hard to create project files as it always assumes it's working of default.gyroflow

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

gh886

### What operating system are you using?

Win10

### What GPU are you using?

3090

### What happened?

Export project file and CTRL+S now always try or do overwrite default.gyroflow. The only way to create a new project is to click choose different location.

![image](https://user-images.githubusercontent.com/71881005/202869795-b01af96f-2c78-4737-a27a-1bd14d3d5acc.png)

**Comment by AdrianEddy** [comment]
Fixed in 238aa6ab40291d721b0c1b4fb1220f9442402119
