### ISSUE TITLE
BRAW playback bug v1.3.0 MacOS 

### ISSUE THREAD

**Issue by elazer666** [gyroflow/gyroflow#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3.0

### What operating system are you using?

macOS Monterey 12.6 and macOS Catalina 10.15.7

### What GPU are you using?

RX570 4GB and RX5700 8GB

### What happened?

I tested importing and playing BRAW footage in Gyroflow v1.3.0 and there was gyro data available but no image playback. Afterwards I tried it on the earlier version (Gyroflow 1.2.0) and the playback video BRAW works perfectly. Can you correct this issue please, so that the community can benefit from your amazing work ?!

**Comment by AdrianEddy** [comment]
It's already fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
