### ISSUE TITLE
Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

### ISSUE THREAD

**Issue by lattice0** [gyroflow/gyroflow#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3

### What operating system are you using?

ubuntu 22.10

### What GPU are you using?

Iris Xe from intel i7 11thgen or 12th gen can't remember

### What happened?

```
./Gyroflow-linux64.AppImage 
MDK 0.17.0 (git 37eca09) - Multimedia Development Kit. Copyright (c) 2016-2022 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux x86_64; Clang15.0.3 GCC4.2.1; libc++15003; 15:08:54 Oct 17 2022
mdk plugin 'mdk-braw': 0x560b3155a4e0

(gyroflow:25399): GLib-GIO-ERROR **: 18:22:49.802: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Crashdump written to /home/lz/Downloads/a6137b4b-9637-4cc1-55ca73a6-117d272c.dmp
Trace/breakpoint trap (core dumped)

```

**Comment by AdrianEddy** [comment]
Already fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
