### ISSUE TITLE
Rendering error when exporting video

### ISSUE THREAD

**Issue by newnood** [gyroflow/gyroflow#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3.0

### What operating system are you using?

Windows 10 Version 22H2

### What GPU are you using?

GeForce GTX960M

### What happened?

Rendering error when exporting video
![gyroflow2](https://user-images.githubusercontent.com/45100064/205433288-eefdb85f-2461-4a51-8f75-3bd831a2b29c.PNG)

**Comment by AdrianEddy** [comment]
Your device doesn't support hardware accelerated encoding for HEVC. It may support H.264/AVC codec, so try that one and also update your NVIDIA driver to the newest one
