### ISSUE TITLE
[Bug]: Instantly crash when opening CSV gyro file

### ISSUE THREAD

**Issue by kennydorion** [gyroflow/gyroflow#53]
### Gyroflow version

1.0.0

### What operating system are you using?

MacOs Big Sur 11.4

### What GPU are you using?

AMD Radeon Pro 5600M 8 Go

### What happened?

Issue whe I try to open a CSV gyro file, it instantly crash and close the app. Working perfectly on 0.0.3 version.

### Relevant log output

```shell
Invalid float 
Invalid float 
Invalid float 
Invalid float 
Invalid float 
Invalid float 
Invalid float 
Invalid float 
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/git/checkouts/telemetry-parser-19821e7ac6d09f51/802bb36/src/blackbox/mod.rs:142:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
zsh: abort      /Applications/Gyroflow.app/Contents/MacOS/gyroflow
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]
```

**Comment by AdrianEddy** [comment]
Please attach the file that causes it to crash

**Comment by kennydorion** [comment]
[P1000180.csv](https://github.com/gyroflow/gyroflow/files/8004262/P1000180.csv)

**Comment by Amzd** [comment]
This one too (both in bbl and csv form but i can't attach bbl here)

[btfl_001.bbl.csv](https://github.com/gyroflow/gyroflow/files/8007956/btfl_001.bbl.csv)

**Comment by AdrianEddy** [comment]
Both fixed, check latest build in Github Actions

**Comment by kennydorion** [comment]
Solved! Thanks!
