### ISSUE TITLE
Quits unexpectedly when use AKAZE optical flow method.

### ISSUE THREAD

**Issue by toferzim** [gyroflow/gyroflow#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3.0

### What operating system are you using?

MacOS 12&6

### What GPU are you using?

M1 Pro

### What happened?

GyroFlow quits unexpectedly when use AKAZE optical flow method with a CinemaDNG file. It works ok till 43% and the crashes. 

### Relevant log output

```shell
Can be found here: https://disk.yandex.ru/d/fLQVfXrtp5V-DQ
```

**Comment by AdrianEddy** [comment]
AKAZE is very compute-intensive and RAM demanding, probably you ran out of memory. Can you try with lower Processing resolution? (Synchronization -> Advanced)
Also please include gyroflow.log

Also, AKAZE doesn't really have any advantage at this point, and will probably be removed in future versions

**Comment by toferzim** [comment]
The thing is that any optical flow goes crazy when try to sync gyro data for a footage shot on a Helios 44-2 lens which is a 58mm lens. No idea why but it shows huge amplitude while the gyro data is  quite narrow.  In the same time with a 24mm lens optical flow works fine. I was thinking if AKAZE can do it better for a Helios footage.

**Comment by AdrianEddy** [comment]
Latest dev build contains multiple `Pose method`s, for longer focal lengths `Almeida` seems to be better
https://gyroflow.xyz/devbuild/?autodownload

**Comment by toferzim** [comment]
This built doesn't open my csv files( saying the format is not supported.

**Comment by toferzim** [comment]
> The thing is that any optical flow goes crazy when try to sync gyro data for a footage shot on a Helios 44-2 lens which is a 58mm lens. No idea why but it shows huge amplitude while the gyro data is quite narrow. In the same time with a 24mm lens optical flow works fine. I was thinking if AKAZE can do it better for a Helios footage.

Even 480p doesn't work

**Comment by AdrianEddy** [comment]
> This built doesn't open my csv files( saying the format is not supported. While the official build opens it just fine.
> 
> CSV is here: https://disk.yandex.ru/d/8YZ5I73zGVX6cQ

Rename to .gcsv

**Comment by toferzim** [comment]
> > This built doesn't open my csv files( saying the format is not supported. While the official build opens it just fine.
> > CSV is here: https://disk.yandex.ru/d/8YZ5I73zGVX6cQ
> 
> Rename to .gcsv

Unfortunately neither this method of syncing is working.

**Comment by AdrianEddy** [comment]
Can you share the footage, gyro and lens profile you're trying to stabilize?

**Comment by toferzim** [comment]
Here it is:

https://disk.yandex.ru/d/8YZ5I73zGVX6cQ

**Comment by toferzim** [comment]
Sorry^ have you managed to make it? By the way I've forgotten to mention the right orientation is ZXY

**Comment by toferzim** [comment]
Well, if the built in Davinci stabilizer can stabilize can it mean it is possible to get an optical flow?  The right orientation is ZXY. It is fixed rigidly and 24mm footage with the same setup works ok with gyrofow. An offset is about 40mm from the sensor's center point up and same forward.

**Comment by AdrianEddy** [comment]
I meant the time offset between gyro and video.
Davinci stabilizer works in a different way, it doesn't reconstruct the camera motion but simply moves pixels around in 2d.
The issue here is to reconstruct the physical camera motion, and DaVinci's stabilizer doesn't do that at all.

You can successfully stabilize this video is you have accurate time offset, optical flow is just a tool to calculate that offset

**Comment by toferzim** [comment]
Unfortunately I have no idea about the offset, cause it is a different device with a separate trigger button. Seems like I need to think about syncing the start.

**Comment by AdrianEddy** [comment]
If you just start recording together the offset should be within 1 sec, that's enough knowledge to then sync manually in Gyroflow

**Comment by AdrianEddy** [comment]
I'm closing this because I don't know what else can be done to improve optical flow at large focal lengths, so there's nothing I can do here
