### ISSUE TITLE
[HEVC_videotoolbox] Error constant_bit_rate true not supported by the encoder with v1.4.0

### ISSUE THREAD

**Issue by AlexeyZatsepin** [gyroflow/gyroflow#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.4.0

### What operating system are you using?

Mac OS 13.0.1

### What GPU are you using?

AMD Radeon Pro 5300M 4 GB

### What happened?

hello after trying new version of software found issue: 
<img width="1260" alt="Screenshot 2022-12-20 at 10 42 37" src="https://user-images.githubusercontent.com/10632284/208579108-6bdbf979-5827-4570-9ebd-b9a85d8a0349.png">

**Comment by AdrianEddy** [comment]
Known issue on older MacOS than Ventura. Either upgrade to Ventura or wait a few days for v1.4.1. or just use 1.3.0 for now

**Comment by AlexeyZatsepin** [comment]
ok, thank you for answer!

**Comment by AlexeyZatsepin** [comment]
but I have Ventura btw

**Comment by AdrianEddy** [comment]
Huh, that's interesting then, can you post `gyroflow.log`? Show package contents -> Contents -> MacOS folder

**Comment by AlexeyZatsepin** [comment]
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10269594/gyroflow.log)

also I found that there are no preview for DJI Action2 videos, just black screen

**Comment by soukron** [comment]
Same issue here: Ventura 13.0.1 (22A400) + Gyroflow 1.4.0 + DJI Action 2 video being exported to h264 and/or h265. 

Attaching gyroflow.log just in case it helps to double-check the behavior.

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10272977/gyroflow.log)

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload

@AlexeyZatsepin about black preview - make sure to reset all settings to defaults (in the Advanced section on bottom right)

**Comment by AlexeyZatsepin** [comment]
thank you @AdrianEddy
