### ISSUE TITLE
[HEVC encode]v1.3 and v1.4 GPU accleated encoder does't support this pixel format(YUV420P10LE),but v1.2 is fine

### ISSUE THREAD

**Issue by TierraErde** [gyroflow/gyroflow#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4 and 1.3

### What operating system are you using?

Mac OS Ventura 13.1

### What GPU are you using?

Radeon PRO VEGA 20 and RX 5700XT

### What happened?

this is v1.2, it's rendering with gpu(10bit hevc)
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/121114763/208704484-78f03750-e71a-40e3-863b-b02e032cf99c.png">
this is v1.3, the same video, same gpu
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/121114763/208704517-c2d8b02d-d778-412a-be13-b2dc2e1b4ca1.png">

**Comment by AdrianEddy** [comment]
Please post gyroflow.log file from both versions after rendering (can be just a few seconds), Show package contents -> Contents -> MacOS

**Comment by AdrianEddy** [comment]
go to Advanced panel and check `Use GPU decoding` (or if it's checked: uncheck and check again)

**Comment by TierraErde** [comment]
> go to Advanced panel and check `Use GPU decoding` (or if it's checked: uncheck and check again)

it work,thanks. ^ ^
