### ISSUE TITLE
RunCam 4K, iFlight Protek, CSV file unsupported

### ISSUE THREAD

**Issue by Nikoliche** [gyroflow/gyroflow#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.0

### What operating system are you using?

Windows 11 home

### What GPU are you using?

NVIDIA,

### What happened?

I'm using drone iFlight Protek pusher with Runcam 4K, I've selected the lens profile but as soon as I try to apply my motion data with a .csv file I receive an error unsupported file format. CSV and screenshot attached. 

CSV file 
[gyroDate0035.csv](https://github.com/gyroflow/gyroflow/files/10270402/gyroDate0035.csv)

Screenshot
![Снимок экрана 2022-12-20 204900](https://user-images.githubusercontent.com/121119468/208721175-94a3571f-fa76-4f80-ac4c-8b4b326c9a60.jpg)

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
