### ISSUE TITLE
[Bug]: " Sensor Logger" Android app unsupported format error.

### ISSUE THREAD

**Issue by TirusTrinity** [gyroflow/gyroflow#54]
### Gyroflow version

1.0

### What operating system are you using?

Mac OS 12.1

### What GPU are you using?

M1 integrated

### What happened?

I tried to import sensordata from the "Sensor Logger" app on android. The zip file is greyed out so it can't be imported. If I unzip I can only choose one data stream. If i choose gyroscope.csv I get the error message"An error occured: Unsupported file format". Is I export to json instead of csv it is grey out and cannot be imported.

### Relevant log output

```shell
Sorry I don't know how to do this.
```

**Comment by AdrianEddy** [comment]
Please attach that recorded file

**Comment by TirusTrinity** [comment]
[Test-2022-02-04_14-34-25.zip](https://github.com/gyroflow/gyroflow/files/8004183/Test-2022-02-04_14-34-25.zip)

**Comment by TirusTrinity** [comment]
and here is the json
[Test-2022-02-04_14-34-25.json.zip](https://github.com/gyroflow/gyroflow/files/8004193/Test-2022-02-04_14-34-25.json.zip)

**Comment by spaceby** [comment]
It seems that the data from the Sensor Logger android version and the data from the Sensor Logger that your application expects have a completely different format.

**Comment by TirusTrinity** [comment]
Thank you! Apparently there are two sensor logger apps on the play store. Maybe I was just using the wrong one! I Was using the one from the developer "Kelvin Tsz Hei Choi" but I will try tomorrow with  the one from "birfincankafein".

**Comment by spaceby** [comment]
Unlikely. That app hasn't been updated in 5 years.

**Comment by TirusTrinity** [comment]
Yeah I just realized... It crashed on me :( So what do you think is going on? Maybe it was only made for IOS.

**Comment by qubic** [comment]
I have tried the Sensor Logger iOS version, same result: 
An error occured: Unsupported file format.

**Comment by xtrul** [comment]
Hi, i have same issue on android with "sensor loger
[Gyroscope.csv](https://github.com/gyroflow/gyroflow/files/8027560/Gyroscope.csv)
"

**Comment by SoulReav** [comment]
I got this error. I'm upset because it seems to be the only officially supported Android app

**Comment by jiangbo212** [comment]
@qubic me too. But I was able to import it using the ios app "gyro". This should be the problem with the csv file header. You can also refer to my problem to adjust the file header should be fine. I import a successful csv file like this
```
Time, Rotation Rate (X), Rotation Rate (Y), Rotation Rate (Z)
1644463471.79379,0.0047486824914813,0.0428342819213867,-0.0507968664169312
```

**Comment by SoulReav** [comment]
@jiangbo212 Could you attach an example of a file "gyro"?

**Comment by AdrianEddy** [comment]
Please attach all files that are unsupported and let us know from which app it is, we'll try to implement support for all

**Comment by pixelistik** [comment]
Additional remark: It would be helpful if the [documentation](https://docs.gyroflow.xyz/logging/general/) and [README](https://github.com/gyroflow/gyroflow/blob/9391491d9ebc48b3a77f06b58ee6e9c6a81e0728/README.md) would not only list the supported mobile apps by name

> ### Supported gyro sources

> Mobile apps: Sensor Logger, G-Field Recorder, Gyro

but rather provide links the the respective app store pages. Then it would be clearer which apps a user can expect to work.

**Comment by lyizhuo** [comment]
> 

I encountered the same problem when importing the gyroscope data recorded by this software[https://play.google.com/store/apps/details?id=com.kelvin.sensorapp](app)
[Gyroscope.csv](https://github.com/gyroflow/gyroflow/files/8049348/Gyroscope.csv)

**Comment by bananafan2015** [comment]
I encountered the same problem when importing the gyroscope data recorded by Sensor Logger 
[Gyroscope.csv](https://github.com/gyroflow/gyroflow/files/8053619/Gyroscope.csv)
r

**Comment by AdrianEddy** [comment]
Ok, all files you provided here are correctly parsed and loaded in the latest dev build. 

Now we need to figure out IMU orientation for each app, with one standard way of "holding the phone", but this will also depend on what you want to stabilize - internal phone camera, or external camera and how you will mount the phone there.

If you want it figured out, I'll need video file, gyro log and a photo of how the phone was mounted relative to the camera.

Feel free to still comment here with video files, but I'll close this issue as the parsing itself is fixed.

**Comment by SoulReav** [comment]
@AdrianEddy 
![photo_2022-02-16_17-35-47](https://user-images.githubusercontent.com
[Gyroscope.csv](https://github.com/gyroflow/gyroflow/files/8079997/Gyroscope.csv)
/1070506/154266380-843dae1a-7f08-4699-960c-d96d2dd7f5b2.jpg)
![DSCF0066](https://user-images.githubusercontent.com/1070506/154266385-7a1cf6eb-36d7-41f4-a776-4dcb396afebe.jpg)

Video file: https://drive.google.com/file/d/1nf4U_ryOAsuv774kqt5dDTLPx21Y8qb_/view?usp=sharing

**Comment by xtrul** [comment]
till a more permanent solution is fixed @Aphobius made this quick way how to sort it out

https://colab.research.google.com/drive/1Nwd5beXejtrZcXOUEmT5NDbErJKdlMtu?usp=sharing

how to do it:
https://drive.google.com/file/d/1afIPQA7EckofMQ0M-U64dSkKqNLWjk6j/view?usp=sharing

**Comment by AdrianEddy** [comment]
> till a more permanent solution is fixed @Aphobius made this quick way how to sort it out
> 
> https://colab.research.google.com/drive/1Nwd5beXejtrZcXOUEmT5NDbErJKdlMtu?usp=sharing
> 
> how to do it: https://drive.google.com/file/d/1afIPQA7EckofMQ0M-U64dSkKqNLWjk6j/view?usp=sharing

This is no longer needed, because all parsing is already implemented natively

**Comment by AdrianEddy** [comment]
> oh nice! is on rc 3?

no, in latest dev build https://gyroflow.xyz/devbuild/?autodownload

**Comment by xtrul** [comment]
thanks
