### ISSUE TITLE
Add support for MTLPixelFormatBGRA8Unorm

### ISSUE THREAD

**Issue by latenitefilms** [gyroflow/gyroflow#540]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Please considering add support for Ordinary format with four 8-bit normalized unsigned integer components in BGRA order ([`MTLPixelFormatBGRA8Unorm`](https://developer.apple.com/documentation/metal/mtlpixelformat/mtlpixelformatbgra8unorm)) to `gyroflow_core`. This is used by Apple's Final Cut Pro and Motion in some circumstances.

**Comment by AdrianEddy** [comment]
Added, use `BGRA8`

**Comment by latenitefilms** [comment]
Legend, THANK YOU!
