### ISSUE TITLE
Add ability to send pointer to MTLTexture in gyroflow_core

### ISSUE THREAD

**Issue by latenitefilms** [gyroflow/gyroflow#543]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

As discussed on Discord, it would be amazing if we could just pass a pointer of an `MTLTexture` to `gyroflow_core`, and it does the "rendering" on that `MTLTexture`, for more seamless third party Metal processing.

**Related:** https://github.com/latenitefilms/GyroflowToolbox/issues/6

**Comment by AdrianEddy** [comment]
Done in latest gyroflow_core
