### ISSUE TITLE
Unable to export video on a MAC after updating to 1.4

### ISSUE THREAD

**Issue by Phiqtional** [gyroflow/gyroflow#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4

### What operating system are you using?

MacOS Monterey 12.6

### What happened?

Tried to export video but an error popped up. 

Never had any issues on 1.3 only started experiencing this right after updating to 1.4

This is the error that popped up. 

<img width="1142" alt="Gyroflow14_error" src="https://user-images.githubusercontent.com/56556701/209063153-189e6063-9493-4792-99e0-3721b391f3b9.png">

Any help would be greatly appreciated. Thank you.

**Comment by AdrianEddy** [comment]
It's already fixed https://gyroflow.xyz/devbuild/?autodownload

**Comment by Phiqtional** [comment]
Thank you so much AdrianEddy!
