### ISSUE TITLE
Export not working: ffmpeg / Nvenc version error

### ISSUE THREAD

**Issue by PaWi20** [gyroflow/gyroflow#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4

### What operating system are you using?

Windows 10

### What GPU are you using?

NVIDIA GeForce GTX 1650 Ti

### What happened?

I updated to version 1.4. Now, it's not possible to stabilize the footage anymore in H.265 with GPU encoding. It works without GPU encoding (H.265) and H.264 (with GPU encoding). 

I'm not sure if it worked in H.265 with GPU encoding in a previous version. But I assume this, as I didn't change the settings after the upgrade.

You can see the errors in the attached screenshot:
![2022-12-21 19_18_14-Gyroflow v1 4 0](https://user-images.githubusercontent.com/121219709/209080374-78fcb006-6148-4712-8964-6d22eb04dcc2.jpg)

**Comment by PaWi20** [comment]
I'm not sure how to provide a log file.

**Comment by mdj36** [comment]
the same error nvidia geforce gtx 1060 the same error please fix earlier was pretty well working.

**Comment by AdrianEddy** [comment]
Did you try different `Device for rendering`? It's in Export settings -> Advanced. Also please provide logs after rendering from both 1.3 and 1.4 (gyroflow.log file is created next to Gyroflow.exe after you close Gyroflow) if it doesn't, run Gyroflow as administrator

**Comment by mdj36** [comment]
I used 1.3rc it was working fine.:
![Screenshot from 2022-12-22 13-35-59](https://user-images.githubusercontent.com/75546869/209126404-027ef450-c132-4226-a65a-5767e41e4a95.png)
![Screenshot from 2022-12-22 13-36-40](https://user-images.githubusercontent.com/75546869/209126440-a68ce1a6-8e08-404a-8c35-408d9a5f4a82.png)

On 1.4 with same settings:
![Screenshot from 2022-12-22 13-31-45](https://user-images.githubusercontent.com/75546869/209126547-ee2f029e-f17f-4e57-b75d-704b9870e989.png)
![Screenshot from 2022-12-22 13-32-14](https://user-images.githubusercontent.com/75546869/209126602-e8766605-675a-44ea-9b64-a0e7a1e48170.png)

**Comment by AdrianEddy** [comment]
Please upload logs

**Comment by mdj36** [comment]
1.4 not working:
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10286858/gyroflow.log)

**Comment by mdj36** [comment]
1.3 working:
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10286958/gyroflow.log)

**Comment by AdrianEddy** [comment]
Should be fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload

**Comment by PaWi20** [comment]
Thanks a lot, also to @mdj36 for providing the log files. I was really busy yesterday and couldn't reply.
