### ISSUE TITLE
Error when exporting GoPro Hero 11 footage

### ISSUE THREAD

**Issue by mikepostons** [gyroflow/gyroflow#548]
Getting this error when exporting GoPro Hero 11 footage on a M1 Macbook.  Footage was shot in 4:3 at 4K 25fps.  GyroFlow settings below:

<img width="535" alt="Screenshot 2022-12-23 at 18 23 31" src="https://user-images.githubusercontent.com/5993953/209391620-269e1d6f-c90d-4044-838c-c96d3ec032d2.png">

<img width="250" alt="Screenshot 2022-12-23 at 18 25 37" src="https://user-images.githubusercontent.com/5993953/209391670-c5bf2678-1fd2-476b-a497-059cabb9ef47.png">

**Comment by AdrianEddy** [comment]
It's already fixed https://gyroflow.xyz/devbuild/?autodownload

**Comment by mikepostons** [comment]
Ah amazing.  Downloaded the latest version just before and didn't see the issue/resolution on GitHub.  Thanks
