### ISSUE TITLE
View R3D Footage

### ISSUE THREAD

**Issue by jim89457** [gyroflow/gyroflow#550]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Would it be able to view the R3D clips directly from RED cameras instead of having to go through the extra step of converting them to a different format prior?

**Comment by AdrianEddy** [comment]
Probably yes at some point

**Comment by jim89457** [comment]
How can we get it sooner / accelerate it?

**Comment by AdrianEddy** [comment]
See this answer for a bit more info how this works: https://github.com/gyroflow/gyroflow/issues/443#issuecomment-1229459504
Basically @wang-bin needs to implement that in mdk and he needs to get paid for it, so to accelerate it community needs to raise money to pay him for his work

**Comment by jim89457** [comment]
How much money do you think for R3D?

**Comment by danielhager** [comment]
Yes, please.
And please donate to them.

**Comment by AdrianEddy** [comment]
R3D playback is coming soon, you can donate here:
https://donate.stripe.com/5kAaGv6ky5mU1s44gg
https://buymeacoffee.com/adrianeddy
https://paypal.me/AdrianEddy

**Comment by AdrianEddy** [comment]
R3D playback is available in the latest dev build now https://gyroflow.xyz/devbuild/?autodownload
