### ISSUE TITLE
Anamorphic Desqueeze

### ISSUE THREAD

**Issue by jim89457** [gyroflow/gyroflow#551]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Would it be possible to load a video clip and provide the option to de-squeeze the footage directly in gyroflow (without needing to do it separately)? 2X, 1.5X, 1.8X, etc. 
So that it's less steps to work with anamorphic footage...

**Comment by AdrianEddy** [comment]
it's already there, when doing lens calibration use "Input horizontal stretch" before starting calibration
