### ISSUE TITLE
DJI Action2 footage have some bad not smooth moves 

### ISSUE THREAD

**Issue by AlexeyZatsepin** [gyroflow/gyroflow#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

macOS Ventura 13.0.1

### What GPU are you using?

AMD Radeon Pro 5300M 4 GB

### What happened?

https://user-images.githubusercontent.com/10632284/209819124-8abda077-acfc-41c5-abea-c8b5acc31e52.MOV

https://user-images.githubusercontent.com/10632284/209819145-3673fbec-b394-4fe9-87b6-9f6b230d95ea.MOV

**Comment by AlexeyZatsepin** [comment]
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10314421/gyroflow.log)

**Comment by AdrianEddy** [comment]
was it 4k 50fps mode by any chance? can you share the original video file?

**Comment by AlexeyZatsepin** [comment]
it's too big for github, how can I share it to you?

**Comment by AdrianEddy** [comment]
wetransfer, dropbox, google drive, or mega.co.nz

**Comment by AlexeyZatsepin** [comment]
internet is so bad, trying to upload

**Comment by AlexeyZatsepin** [comment]
@AdrianEddy finally manage to upload here: https://fex.net/ru/s/ynn8vea

**Comment by hzjianglf** [comment]
I find this bug，too，pls  see video： https://pan.baidu.com/s/1wKRk9OK5q8cQX2ecFncAkQ?pwd=4444    pwd: 4444

**Comment by hzjianglf** [comment]
> [AlexeyZatsepin](/AlexeyZatsepin)

@AlexeyZatsepin

**Comment by AdrianEddy** [comment]
it's a bug in DJI Action 2 firmware, I reported it to DJI.

There's nothing you can do about this file unfortunately, it will likely be fixed in the next firmware version, but this video will remain like that. You can add some small amount of Warp Stabilizer in Premiere or Resolve

**Comment by AlexeyZatsepin** [comment]
Ah, unfortunately, thanks for figuring this out!

**Comment by AdrianEddy** [comment]
This is fixed in latest Action 2 firmware - v01.04.0420

**Comment by AlexeyZatsepin** [comment]
thank you!
