### ISSUE TITLE
Video from DJI Action2 exported as just black screen

### ISSUE THREAD

**Issue by AlexeyZatsepin** [gyroflow/gyroflow#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

macOS Ventura 13.0.1

### What GPU are you using?

AMD Radeon Pro 5300M 4 GB

### What happened?

Video from DJI Action2 exported as just black screen, by link you can see before and after gyroflow: 

https://fex.net/s/kndcnmv

**Comment by AdrianEddy** [comment]
do you see the preview in Gyroflow or is it also black? Try resetting Gyroflow to defaults (Advanced -> Reset all settings to defaults, on bottom right)

**Comment by AlexeyZatsepin** [comment]
also black, already tried to reset to defaults - not worked

**Comment by AdrianEddy** [comment]
Please show me a screenshot of Gyroflow with your settings

**Comment by AlexeyZatsepin** [comment]
<img width="1792" alt="Screenshot 2023-01-03 at 21 06 22" src="https://user-images.githubusercontent.com/10632284/210372993-4bbb6493-8586-4831-9e14-4e79eab1bbbe.png">
