### ISSUE TITLE
DJI O3 video downsize a lot and Y rotate 180 degree.

### ISSUE THREAD

**Issue by Spielben** [gyroflow/gyroflow#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

Mac OS Monterrey 12.16

### What GPU are you using?

Intel UHD Graphics 630 1536 MB

### What happened?

When I drag or upload a video from DJI O3 Air Unit, at first all seems ok.
Gyro datas are found and all file info are correct.
Then when I toggle stabilisation the picture reduce more than X10 and rotate 180.
I tried 2 different video footage with the same issue. and when export the problem is the same.
I have shot without IES and in wide field of view.
<img width="1792" alt="Screen Shot 2023-01-06 at 16 04 33" src="https://user-images.githubusercontent.com/122087123/210971481-e3923e9a-70b4-4294-85c9-31e11e5d847a.png">
<img width="1792" alt="Screen Shot 2023-01-06 at 16 04 41" src="https://user-images.githubusercontent.com/122087123/210971548-32e88d37-4265-4b9e-b54e-cdb5dc9a0fb2.png">

thank you for your help

### Relevant log output

```shell
https://drive.google.com/file/d/1vtOYLnSQpf8iUr-8TG0EnxxJCAjulZDz/view?usp=sharing
```

**Comment by AdrianEddy** [comment]
Did you try to reset all settings to defaults? (bottom right in Advanced panel)

**Comment by B-nutze-RR** [comment]
The O3 clip shows,  a lot of vibrations make it into the camera ( and don't show up in video). You need to check if your RPM filters are configured correctly - using high PWM frequency for your ESCs is recommended.  You may also need a TPU mount for the camera.

**Comment by Spielben** [comment]
That was the missing step.
The “Damned” reset option.
Thanks a lot,

Cheers,

Ben SPIELBEN

Spielben & Co.

✆ +66 91790 44 41
***@***.***
w: https://spielben.com

**Comment by maxartgym** [comment]
Please I have the same problem with my djo ao3, did you resolve this issue, explain me please what did you reset to the Solution.... Thanks alot

**Comment by AdrianEddy** [comment]
> Please I have the same problem with my dji ao3, did you resolve this issue... , explain me pleaseee what did you exactly do for Solution...Thanks alot...

Open Advanced panel on bottom right and click "Reset all settings to defaults"

**Comment by maxartgym** [comment]
> > Please I have the same problem with my dji ao3, did you resolve this issue... , explain me pleaseee what did you exactly do for Solution...Thanks alot...
> 
> Open Advanced panel on bottom right and click "Reset all settings to defaults"

Hi Adrián, Advance panel in the my googles  for change de 03 settings, or in gyroflow... Thanks agan
