### ISSUE TITLE
Automatically synchronize gyro data with Sony files and rolling shutter

### ISSUE THREAD

**Issue by VBK7** [gyroflow/gyroflow#566]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Correct me if I'm wrong, but how does catalyst browse and prepare stabilize Sony footage. I'm pretty sure there's a set offset amount between when the video file and the gyro data starts recording for each Sony camera(maybe its the same for all of them). I shoot on the a7s3 and it seems like that number is right around -20 ms. Whenever I use auto sync, it's right around that number or way off in which case I just manually offset it to -20 ms. Gyroflow should know the offset amount for all cameras that record this way and automatically offset the Gyro data, the proper amount, when you open a video with metadata that the software recognizes is from one of these cameras. Also, would be great if we could apply the same concept to rolling shutter correction. The data is all out there on the read out speeds of basically all camera sensors so why not assign all this data to each camera and automatically apply rolling shutter correction to the proper amount as soon as a video file is opened. To simplify it, Gyroflow knows a certain amount of information about each camera when it recognizes it, gyro data offset amount and sensor readout speed should be two extra pieces of information assigned to each camera profile that Gyroflow should know. There could then be an option to turn on or off whether Gyroflow should automatically adjust everything to this information. last question, will Gyroflow ever be able to apply lens correction to Sony files just based off of the video file metadata and videos with zoom lenses where I zoom in and out?

**Comment by AdrianEddy** [comment]
Sure, I wish we could support that, but it needs reverse engineering, there's no documentation.
It's already tracked in #44 
Sony metadata likely contains:
- Lens correction
- IBIS movements
- Active stabilization (EIS) data
- Gyro offset
- Rolling shutter value

This means in theory all shooting modes should be supported for post-stabilization

None of these are figured out, but you can use `gyro2bb --dump` to dump all the metadata. Help figuring this out is very much needed. Let's keep this all in #44
