### ISSUE TITLE
GPU encoder failed (don`t work with Nvidia GeForce MX350

### ISSUE THREAD

**Issue by irosko** [gyroflow/gyroflow#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v 1.4.2 (gh1015)

### What operating system are you using?

Windows 10

### What GPU are you using?

Nvidia GeForce MX350

### What happened?

I have a problem with GPU when I try to export video using the lastest version of GyroFlow and lastest version of Nvidia driver.
Screen attached, logfile attached.
Can you help me with this ?
![Gyroflow v1 4 2_230109005629](https://user-images.githubusercontent.com/115148125/211221196-93ee0e88-18a0-4835-b899-c7a7c177fd27.png)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10369591/gyroflow.log)

**Comment by AdrianEddy** [comment]
Unfortunately your GPU doesn't support video encoding, see here: https://en.wikipedia.org/wiki/Nvidia_NVENC
> In laptop graphics, NVIDIA MX Graphics do not include NVENC as they are based on a [Maxwell](https://en.wikipedia.org/wiki/Nvidia_Maxwell)-generation GM108 or a Pascal-generation GP108 chip.[[12]](https://en.wikipedia.org/wiki/Nvidia_NVENC#cite_note-12) The GeForce MX350 is a GP107 chip whose NVENC encoder is disabled during manufacture.
