### ISSUE TITLE
DJI ACTION2 GF1.4.2  horizon locking function

### ISSUE THREAD

**Issue by hzjianglf** [gyroflow/gyroflow#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

win10

### What happened?

Set the horizon locking function in GF, and the horizon after locking is more inclined .  I use dji action2 the newest firmware: 01. 04.04.20

![no](https://user-images.githubusercontent.com/31354398/213905159-672e4548-f820-4491-9559-acb402278d11.png)

![yes](https://user-images.githubusercontent.com/31354398/213905169-b50d1d98-e320-48d3-897c-7fb066798f64.png)

**Comment by AdrianEddy** [comment]
Can you share the original video file?

**Comment by hzjianglf** [comment]
> Can you share the original video file?

I will upload video later。Thank you。

**Comment by hzjianglf** [comment]
> Can you share the original video file?

PLS SEE THIS video @baidu netdisk .   file size is about 1.2G . Thank You.

https://pan.baidu.com/s/1ENcJKQAqqWxsImyc9gx2hQ?pwd=1234

**Comment by hzjianglf** [comment]
> > Can you share the original video file?
> 
> PLS SEE THIS video @baidu netdisk . file size is about 1.2G . Thank You.
> 
> https://pan.baidu.com/s/1ENcJKQAqqWxsImyc9gx2hQ?pwd=1234

@AdrianEddy

**Comment by hzjianglf** [comment]
VIDEO is uploaded 。 I Looking forward to the results of your analysis。Thank You.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyroflow/gyroflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月22日(星期天) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyroflow/gyroflow] DJI ACTION2 GF1.4.2  horizon locking function (Issue #575)





 
Can you share the original video file?

**Comment by jesuslg123** [comment]
Hello,

I think I facing the same issue on the latest build of Gyroflow with the same firmware. I think the horizon lock does not fail all the time, only in some part of the video.


<img width="1509" alt="Screenshot 2023-01-28 at 21 54 32" src="https://user-images.githubusercontent.com/7817064/215290869-634a6bd8-bd01-4995-9fc4-a54f23ded462.png">
<img width="1512" alt="Screenshot 2023-01-28 at 21 54 39" src="https://user-images.githubusercontent.com/7817064/215290873-0395d293-5e0d-4a2b-820a-0b03dc3d4688.png">

**Comment by hzjianglf** [comment]
> Hello,
> 
> I think I facing the same issue on the latest build of Gyroflow with the same firmware. I think the horizon lock does not fail all the time, only in some part of the video.
> 
> <img alt="Screenshot 2023-01-28 at 21 54 32" width="1509" src="https://user-images.githubusercontent.com/7817064/215290869-634a6bd8-bd01-4995-9fc4-a54f23ded462.png">
> 
> <img alt="Screenshot 2023-01-28 at 21 54 39" width="1512" src="https://user-images.githubusercontent.com/7817064/215290873-0395d293-5e0d-4a2b-820a-0b03dc3d4688.png">

BUT when i use gopro, No similar situation will occur。

**Comment by AdrianEddy** [comment]
Yes, it's a bug in DJI Action 2 firmware, I sent your file to DJI, I hope they will fix it in the next firmware

**Comment by AdrianEddy** [comment]
I'm closing this, as there's nothing in Gyroflow that I can do to fix it. Hopefully it's fixed in the latest DJI Action 2 firmware.
