### ISSUE TITLE
ffmpeg error when starting an H.264/AVC or H.265/HEVC export 

### ISSUE THREAD

**Issue by loloshadow** [gyroflow/gyroflow#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.4.2

### What operating system are you using?

Windows 10 Version 22H2 pour x64

### What GPU are you using?

NVIDIA 940MX

### What happened?

This error appears when starting an export, GPU pilot is updated. Any idea ?  

![Error_export_in_H_264_AVC](https://user-images.githubusercontent.com/123324483/213933838-996b600e-2273-4a33-b8b6-72c2806f27d3.JPG)

**Comment by AdrianEddy** [comment]
Your GPU doesn't support accelerated rendering. Uncheck "Use GPU encoding"

**Comment by loloshadow** [comment]
Works well now, thanks a lot !!!
