### ISSUE TITLE
ffmpeg error with GPU export 

### ISSUE THREAD

**Issue by djtonysky** [gyroflow/gyroflow#577]
hello! I get an error when I try to export a file using a graphics card. Rendering happens on the processor.
Video card: nvidia mx450 (notebook)
gyroflow 1.4.2

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10477512/gyroflow.log)
![error](https://user-images.githubusercontent.com/55946840/213985584-dab52abd-de0a-4d62-9805-a98923bdff20.png)

**Comment by AdrianEddy** [comment]
Your GPU doesn't support accelerated encoding, you have to use CPU. Uncheck "Use GPU encoding"
