### ISSUE TITLE
rotate video support

### ISSUE THREAD

**Issue by yafinewbie** [gyroflow/gyroflow#580]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

can gyroflow have features for rotating video when recorded on portrait mode (rotated 90 deg)

**Comment by AdrianEddy** [comment]
It's already there: Rotation in Video information tab

**Comment by yafinewbie** [comment]
it only rotate the video source but broke the aspect ratio and motion data when importing from runcam 5 orange
![image](https://user-images.githubusercontent.com/5406777/215330996-d234e358-62f3-4a73-8a04-a2adbb64ca47.png)
and export resolution is limited (can't even go 2.7k on portrait)

**Comment by AdrianEddy** [comment]
What exactly do you want to do? Did you film horizontally or vertically? Do you want to export horizontal or vertical? The output resolution limitation is a limitation of H264 encoder and I can't do anything about it. You can use H265 or ProRes

What do you mean it broke the aspect ratio?

**Comment by AdrianEddy** [comment]
Depending on your use case, you can also rotate the motion data, using Motion data -> Rotation -> Roll angle
