### ISSUE TITLE
Gyroflow 1.3.0and 1.4.2 can not render multiple videos at the same time

### ISSUE THREAD

**Issue by TierraErde** [gyroflow/gyroflow#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.3.0 and 1.4.2

### What operating system are you using?

Mac OS 13.1

### What GPU are you using?

Radeon Pro VEGA 20

### What happened?

Gyroflow 1.3.0and 1.4.2 can not render multiple videos at the same time.
If i render one video one time,it will success，if i change video when it rendering last video,it will failed,both i can't render the new video with GPU.

![76221674566372_ pic_hd 1](https://user-images.githubusercontent.com/121114763/215660175-f5410796-4abd-4215-a91b-d6ed9e03f04f.jpg)
![76321674567465_ pic_hd](https://user-images.githubusercontent.com/121114763/215660207-24937899-7211-4850-aa7f-7839d52ff91d.jpg)
![80201675138066_ pic_hd](https://user-images.githubusercontent.com/121114763/215660634-fe78804b-2ab7-4347-964c-6d0f5c128e9e.jpg)
![80161675137997_ pic_hd](https://user-images.githubusercontent.com/121114763/215660646-69b81121-8e7a-4398-a904-4e085fc63303.jpg)

![80151675137983_ pic_hd](https://user-images.githubusercontent.com/121114763/215660656-5d10f2ef-fd72-4337-81c8-bfe1b9d7e6b7.jpg)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/10542638/gyroflow.log)

**Comment by AdrianEddy** [comment]
I can't reproduce this on M1 and M2 mac, please send me a log from latest dev build ( https://gyroflow.xyz/devbuild/?autodownload ) when it shows the error and then you close the app (the log will be complete after you close the app)

**Comment by AdrianEddy** [comment]
Do you still have this issue with latest dev build? https://gyroflow.xyz/devbuild/?autodownload

**Comment by AdrianEddy** [comment]
I don't think there's anything I can do about it on my side, I think it's a limitation of the GPU encoders in Intel Mac devices
