### ISSUE TITLE
The preview issue

### ISSUE THREAD

**Issue by ghostkcleung** [gyroflow/gyroflow#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.4.2(gh972)

### What operating system are you using?

Intel® Core™ i7-7700HQ

### What GPU are you using?

NVIDIA GeForce GTX 1050 Ti 

### What happened?

Can not play preview. The following is the screen capture.

https://drive.google.com/file/d/1KyAeRF7j-1aIJncEsYXSZKaSNPe4U_sF/view?usp=sharing

**Comment by AdrianEddy** [comment]
1. Install latest driver from https://www.nvidia.com/download/driverResults.aspx/199654/en-us/
2. Does the preview work if you toggle stabilisation off? (S key)
3. Does anything change if you select different Preview pipeline under Advanced?

**Comment by AdrianEddy** [comment]
Do you still have this issue?

**Comment by ghostkcleung** [comment]
> Do you still have this issue with latest dev build? https://gyroflow.xyz/devbuild/?autodownload

It's OK with the latest nightly build. Thank you.
