### ISSUE TITLE
Files stitcher is limited at 20 files

### ISSUE THREAD

**Issue by temp-64GTX** [gyroflow/gyroflow#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

Win 10 x64 1809

### What happened?

Hello. Me again. 
I noticed that built-in footage-stitcher is limited at only 20 files. And resulting joined footage are come out without all segments above 20. Can you please increase this limit? I think 99 will work fine.
![limited](https://user-images.githubusercontent.com/107313519/218179267-ca5d217e-b600-48d7-ba74-691871217a26.png)

**Comment by AdrianEddy** [comment]
Updated in latest dev build https://gyroflow.xyz/devbuild/?autodownload
