### ISSUE TITLE
it doesnt center on the camera

### ISSUE THREAD

**Issue by jeraldpunx** [gyroflow/gyroflow#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

Windows 11

### What GPU are you using?

RX570

### What happened?

the camera is not on the center...  tried every settings here :(
here is sample 
https://youtu.be/YK-RyEIeaCI

### Relevant log output

```shell
I want to center it but the screen is just rotating and not following it.
```

**Comment by AdrianEddy** [comment]
Change `Fixed camera` to `Default` in Stabilization tab and enable Dynamic zooming or expand the Advanced tab and click red "Reset all settings to default"
