### ISSUE TITLE
[Bug]: Image orientation wrong on initial load

### ISSUE THREAD

**Issue by sweebee** [gyroflow/gyroflow#59]
### Gyroflow version

v1.0.0-rc1

### What operating system are you using?

MacOS 12.1

### What GPU are you using?

AMD Radeon Pro 5300M

### What happened?

When opening an Insta360 go2 file the orientation is set to 180 degrees, which seems good. But the image is upside down. When i set the orientation to 0 and then back to 180 it looks good.

<img width="214" alt="Schermafbeelding 2022-02-04 om 18 01 30" src="https://user-images.githubusercontent.com/10496485/152570938-e3071c2d-ce4e-43bf-b20d-69ce8c17358b.png">

**Comment by sweebee** [comment]
made a video of the orientation bug on load: https://www.youtube.com/watch?v=QcMTATE5AO0 in the beginning i have to set the orientation to 0 and then back to 180.

**Comment by ElvinC** [comment]
Fixed with https://github.com/gyroflow/gyroflow/pull/109
