### ISSUE TITLE
Green screen preview

### ISSUE THREAD

**Issue by Mielotxin** [gyroflow/gyroflow#591]
Well, it was working great, but after the update I only get green screens on my gopro 8 and 10 previews. The BMPCC and the gopro11 are working great tho...
Gyro reading, sound and export are working fine. Did I mess any setting?
TIA

![Gyroflow v1 4 2 - Green screen](https://user-images.githubusercontent.com/97285729/219369654-7f69514e-6752-4f66-936f-ce0a6395e41e.png)

**Comment by AdrianEddy** [comment]
Did you try latest dev build? https://gyroflow.xyz/devbuild/?autodownload

**Comment by Mielotxin** [comment]
Not yet, but I managed to make it work in a strange way. I first load a GP11 clip and then the GP8 one loads perfectly.
It seems to be some random bug? Thank you Eddy!

**Comment by AdrianEddy** [comment]
Please test the latest dev build from the link I provided, I think it should be fixed there

**Comment by AdrianEddy** [comment]
Do you still have this issue?

**Comment by Mielotxin** [comment]
Yes! I'm sorry for the late reply...
Thank you for your time Eddy, and the v1.5 it's looking solid too!

**Comment by AdrianEddy** [comment]
Yes as in "yes it's fixed" or "yes, I still have the green screen issue"? :)

**Comment by Mielotxin** [comment]
Yes, it's fixed.
