### ISSUE TITLE
Black screen on preview when try to stab action 2 video

### ISSUE THREAD

**Issue by ctfire** [gyroflow/gyroflow#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

Windows 10

### What GPU are you using?

Geforce gtx960

### What happened?

Preview of vodeo works only on 1.0.1 version , but in this version not working gyrodata from dji action 2.
In last version of gyroflow gyrodata works, but when i turn on stabilize button preview become black

**Comment by AdrianEddy** [comment]
Go to Advanced and **Reset all settings to defaults**
