### ISSUE TITLE
ffmpeg error (30: Read-only file system)

### ISSUE THREAD

**Issue by manyoruss1** [gyroflow/gyroflow#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.4.2

### What operating system are you using?

macOS Ventura 13.2.1

### What GPU are you using?

AMD Radeon Pro 5500 XT 8GB

### What happened?

When attempting to render/export file, I receive the following error msg: 
"An error occurred: ffmpeg error: ffmpeg:: Error(30:Read-only file system)"

I have also attempted to use previous releases and unchecked "Use GPU encoding"but still unable to export/render.

See screenshot. Please help, thank you!
![Image 2-21-23 at 12 16 AM](https://user-images.githubusercontent.com/12244116/220254117-a0a21771-ead4-416d-a623-a696e83a6f28.jpg)

**Comment by AdrianEddy** [comment]
Read-only file system means that the program can't write the output file either because the file system is read only or you don't have permissions to write to it. Change the output path to a folder where you can write files
