### ISSUE TITLE
Automatic Video Speed Adjustment

### ISSUE THREAD

**Issue by jakubsz123** [gyroflow/gyroflow#597]
It often happens for drone FPV videos that the flying speed is changing often due to wind or a pilot's mistake. Even though the video is perfectly stabilized the speed changes makes it not smooth at all. Happens mostly when I shoot indoors. 

Retiming it in a video editing software can often be simply impossible. It would be amazing if the gyro data could be used to create a constant smooth speed. 

Thanks.

Uploading gyroflow.mp4…

**Comment by AdrianEddy** [comment]
Unfortunately gyro data is not useful for this as it can't be used to determine speed. GPS could in theory be used, but also only if you're flying in a straight line. In general this is not something I'm planning to implement, and it also was already requested in #142
