### ISSUE TITLE
v1.5 Lens calibration with R3D file not finishing

### ISSUE THREAD

**Issue by leitmanr** [gyroflow/gyroflow#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5

### What operating system are you using?

Windows 10 Pro 22H21 9045.2604

### What GPU are you using?

EVGA RTX 3080ti FTW3

### What happened?

When trying to perform a lens calibration in v1.5 and using a .r3d file, the lens calibration will not finish the progress bar but the "wheel" will keep spinning forever.. in v1.4.2(gh1028) it works fine with the same file - see attached video of the issue

[https://youtu.be/u9h0BfQU2_4](url)

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/?autodownload
