### ISSUE TITLE
GoPro 5K footage not importing

### ISSUE THREAD

**Issue by MasonMarcGitHub** [gyroflow/gyroflow#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.0

### What operating system are you using?

Windows 11

### What GPU are you using?

NVDIA GeForce RTX 3050

### What happened?

I'm attempting to upload 5.3K/60 FPS footage from a GoPro Hero 10 black and after 30 minutes it still has bot uploaded. What can I do? I am using the latest 1.5.0 version.

**Comment by AdrianEddy** [comment]
Do you have latest GPU driver installed? do you have latest windows updates installed? Do other files work? Please send gyroflow.log file (it's created next to the exe)

**Comment by AdrianEddy** [comment]
Any update?
