### ISSUE TITLE
Problem with rendering

### ISSUE THREAD

**Issue by luizmariojr** [gyroflow/gyroflow#601]
[gyroflow.log](https://github.com/gyroflow/gyroflow-ofx/files/10924969/gyroflow.log)
![Erro Render GPU](https://user-images.githubusercontent.com/127348365/223841720-40ce7a58-ab21-4640-a6f8-2d53d41af06f.png)
Nvidia Geforce MX250 video card the application is unable to render video using this GPU.

Information is attached

**Comment by AdrianEddy** [comment]
MX250 doesn't support any GPU encoding, so this is expected.
see the support matrix here https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
It's using GP108 chipset, which doesn't have any encoders: 
https://en.wikipedia.org/wiki/Nvidia_NVENC?useskin=vector

https://www.techpowerup.com/gpu-specs/geforce-mx250.c3353
