### ISSUE TITLE
Multiple video file join can select target folders location

### ISSUE THREAD

**Issue by hzjianglf** [gyroflow/gyroflow#602]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Generally, the original video taken by the camera is saved on the SD card. The location of the target folder cannot be selected for the join of multiple videos, but can only be saved on the SD card. Therefore, we can only copy the SD file to the computer and then connect it, which brings us inconvenience. If we can select the location of the target folder, we can directly save the joined files on the hard disk, and finally increase the stability.

**Comment by AdrianEddy** [comment]
Done in [c0a2cfe](https://github.com/gyroflow/gyroflow/commit/c0a2cfe5ddf096ecb62a443e97b95c41425c1334)
