### ISSUE TITLE
gyroflow::rendering: Failed to create specified HW device: AV_HWDEVICE_TYPE_QSV

### ISSUE THREAD

**Issue by ojoojoo** [gyroflow/gyroflow#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5

### What operating system are you using?

Windows 11

### What GPU are you using?

NVIDIA Quadro K4200

### What happened?

![2023-03-15 13_27_48-Gyroflow v1 5 0](https://user-images.githubusercontent.com/56216880/225309365-6727babb-07fc-4f34-8b14-0fa4c92bbb31.png)

[gyroflow.zip](https://github.com/gyroflow/gyroflow/files/10979831/gyroflow.zip)

**Comment by AdrianEddy** [comment]
Use latest dev build and select "Device for rendering" in Export settings -> Advanced to the Quadro card.
Also make sure you have latest NVIDIA driver installed
https://gyroflow.xyz/devbuild/?autodownload

**Comment by ojoojoo** [comment]
Yes, now it's working with the nightly, with version 1.5 the application crashes en quits. In the export settings I already selected the Quadro.
