### ISSUE TITLE
Auto-sync hangs @57.98%

### ISSUE THREAD

**Issue by csomyy** [gyroflow/gyroflow#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.0

### What operating system are you using?

Windows 10 

### What GPU are you using?

Geroce GTX 950M

### What happened?

In the 50% of the time Auto-sync progress hangs at 57.98%. I can see, that when it doesn't hang, it finishes after ~60%, so something at the end of the process should be the problem.
I tried many configuration alternatives in the auto-sync settings and even disabled the dedicated display card. Same behaviour. Even on nigtly build gh1144. 
In this cases the Auto-sync configuration section of the Gyroflow windows stays grayed out. The whole program works, but cannot access these settings.

**Comment by AdrianEddy** [comment]
What camera are you using? Does it have gyro data? The synchronization is grayed out when the gyro data is not loaded or not available. Can you send a sample file?

**Comment by csomyy** [comment]
I'm using the Walksnail Avatar Micro camera (ground saved) 1080p60fps and Arduplane log (not yet properly configured).
I will upload my data for you.

The Auto-sync is usable, until processing. After that becomes grayed...

**Comment by csomyy** [comment]
Here you are
https://drive.google.com/drive/folders/1kxblLNttCbGG2ThJ-XHdBtGCrYPTR-hQ?usp=sharing

**Comment by csomyy** [comment]
![image](https://user-images.githubusercontent.com/85110866/226609495-c12da0f1-cdf7-4c5d-b76f-3c360310aa61.png)
