### ISSUE TITLE
[Bug]: Color shift in ProRes export of the stabilized footage

### ISSUE THREAD

**Issue by leitmanr** [gyroflow/gyroflow#62]
### Gyroflow version

1.0

### What operating system are you using?

Windows 10 Pro 21H2 19044.1466

### What GPU are you using?

EVGA RTX 3080ti FTW3

### What happened?

There seems to be a slight color shift issue with the prores encoder of the GF.
I have exported a EBU chart from resolve and run it through GF
Then I have imported the original file and the"stabilized" one above it and isolated the colors and compared various exports from GF with the original file.
![EBUbar_unstab_original](https://user-images.githubusercontent.com/99039827/152577364-92fbe4fd-dc61-4c1e-8eca-99bc299ec55d.png)

here is a pic of how the isolated regions of the "stabilized" footage looked 
![example_of_bars_used](https://user-images.githubusercontent.com/99039827/152577255-969e9c86-d01e-4d18-95ba-c58ca00e8883.png)

and here are some comparisons h.264/265 gpu or cpu encoded looked exactly the same but with prores exports there is a slight color/value shift in white, yellow, cyan, green and magenta bars. PNG's are way off but I am really not worried about them (I assume it's a colorspace tag issue with the PNG's)
here are the tests of both Prores and png's
Prores 4444
![prores4444](https://user-images.githubusercontent.com/99039827/152577650-d9884a31-ccd7-41fd-95e7-a9c2fc7c455e.png)

Prores 4444XQ 1000Mbps
![prores4444xq1000](https://user-images.githubusercontent.com/99039827/152577657-2492400b-8761-46da-a63e-737aac7d8cff.png)

PNG8bit
![png](https://user-images.githubusercontent.com/99039827/152577669-3e516c36-bbdf-4549-93e7-9d8d9fe67208.png)

PNG16bit
![png16bit](https://user-images.githubusercontent.com/99039827/152577674-768aac8e-3b53-43f0-adc2-3990a172db1c.png)

**Comment by AdrianEddy** [comment]
Thanks for testing, we'll look into it. Probably an issue with setting correct color parameters for the encoder. PNG also needs to be fixed, so that's for that comparison too

**Comment by AdrianEddy** [comment]
Was the input file 4:2:2 10-bit prores? The exactly the same pixel format as the export?

**Comment by leitmanr** [comment]
After downloading a build with fixed prores export speed I've did the color shift test again and the slight color/value shift in white, yellow, cyan, magenta, red and blue colors is still present.. it is minor (from 1 to 2 value change in channels) , but it's still there...

![prores_color_shift_1 0 0-rc1(gh189)](https://user-images.githubusercontent.com/99039827/153019455-538200ea-6caa-4612-81e9-051b56db83f8.png)


The output values of RGB channels change in
white from 255/255/255 to 254/254/254
yellow from 192/191/-1 to 191/191/-1
cyan from -1/192/191 to -1/191/190
magenta from 192/0/193 to 191/0/192
red from 192/0/0 to 191/0/0
blue from -1/0/192 to -1/0/190

this might be a negligible difference for 99,9% of users but when those colors combine and the footage is graded, it can grow and result in slight and noticeable difference in color of the output.

**Comment by AdrianEddy** [comment]
Can you do a test with 4:2:2 10-bit input, and another one 4:2:0 10-bit input? There is a difference in implementation for these two and I want to see if it's any different

**Comment by leitmanr** [comment]
the input file was h.265 (I am on windows, therefore I can't export prores, I'll try exporting DNxHR and test it with that...

**Comment by AdrianEddy** [comment]
try 4:2:2 10-bit h265 as well

**Comment by leitmanr** [comment]
well just ran into weird issue, GF would not open DNxHR HQX 10bit 422 file. shall I open it as a new issue?
![image](https://user-images.githubusercontent.com/99039827/153024665-758cc862-9325-4886-8e01-735ef15ab61a.png)


from quick test with h265 10bit 420 -> proresHQ the color shift is only in the yellow color 
it goes from 192/191/0 to 191/191/0
![image](https://user-images.githubusercontent.com/99039827/153024166-09db4042-32fa-4d21-bec9-52652c189ae9.png)![image](https://user-images.githubusercontent.com/99039827/153024190-0c34b512-517c-4865-ade7-a0907b08b10a.png)

![image](https://user-images.githubusercontent.com/99039827/153024555-b770345c-eb19-4e5c-aa1c-ca58f0413e41.png)

**Comment by leitmanr** [comment]
same behaviour on the yellow in the h265 10bit 422
![image](https://user-images.githubusercontent.com/99039827/153026875-693e91fe-77a0-4898-b2f1-a16b455da7aa.png)

**Comment by AdrianEddy** [comment]
`DNxHR HQX 10bit 422 file. shall I open it as a new issue?`
Yes and upload that file

**Comment by AdrianEddy** [comment]
ok one more test, can you reencode this file just using ffmpeg? with `-c:v prores_ks -pix_fmt yuv42210ple -profile hq`

**Comment by AdrianEddy** [comment]
Hmm if this still looks the same in direct ffmpeg transcode then I'm afraid that's out of our control

**Comment by leitmanr** [comment]
yup, I thought so.. we'll just have to learn to live with it for now I guess.. at least we know about it...

**Comment by AdrianEddy** [comment]
Please test with this version: https://github.com/gyroflow/gyroflow/suites/5296956914/artifacts/164310984

**Comment by AdrianEddy** [comment]
I believe this issue can be closed, all color conversions should be correct now (except for that tiny shift that also happens with ffmpeg)
https://gyroflow.xyz/devbuild/?autodownload
@leitmanr please double check and confirm there's no significant difference

**Comment by leitmanr** [comment]
Will check but I agree. There is just that one minor shift caused by ffmpeg.
H.264/5 is perfect without any shifts.
