### ISSUE TITLE
Interface does not respond to commands during cuts with video running

### ISSUE THREAD

**Issue by rodrigosclosa** [gyroflow/gyroflow#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.0

### What operating system are you using?

Macos Ventura

### What GPU are you using?

M1 Pro

### What happened?

When we are cutting the video with it playing, when marking the end, the video bugs and the interface commands no longer respond.

See the video below:

https://youtu.be/z1EXUt6sC7o

**Comment by AdrianEddy** [comment]
Should be fixed in latest dev build, please check https://gyroflow.xyz/devbuild/?autodownload
