### ISSUE TITLE
[Feature request]: Auto loop replay sync points when zoomed in

### ISSUE THREAD

**Issue by b14ckyy** [gyroflow/gyroflow#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we zoom in to a sync point it would be nice to have an auto loop around the sync point as a center and 1s before and after it. 
This would help to visualize how well the sync is matching even before checking the graphs. 

It is already possible with the Trim feature but doing it automatically would be much easier and quicker, the same way as it is possible in Reelsteady Go. 

As an addition set the Stabilization Algorythm to Fixed camera like RSGO to get best visualization if video is synced with gyro correctly

**Comment by AdrianEddy** [comment]
Anyone still wants this feature? I feel like since we have the new rs-sync algorithm, the need for manual adjusting like that is much lower

**Comment by b14ckyy** [comment]
The autosync works pretty well but sometimes, especially in lower light conditions, manual sync still helps IMHO. Or if it is blurry a bit from the shutter speed.
