### ISSUE TITLE
StabilizationManager::process_pixels should return `Result` or panic

### ISSUE THREAD

**Issue by ralfbiedert** [gyroflow/gyroflow#650]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I've started playing a bit with the core library now. One thing I ran into was that `process_pixels` can fail for a number of reasons, just returning `None`. 

Many of the reasons seem to be "programming errors" (e.g., passing too small buffers) that could only be fixed by changing code. I think it might be better to `panic` instead, or at least return a `Result<ProcessedInfo, Error>`, as either would make debugging easier.

**Comment by AdrianEddy** [comment]
Done in 6a86c623bf34691db554ec4cf09d9b17ff9147d1
