### ISSUE TITLE
SteadXP

### ISSUE THREAD

**Issue by stpfl123** [gyroflow/gyroflow#651]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hi! 
Are there any intentions that Gyroflow will work with SteadXP logger someday? 
Thanks

**Comment by AdrianEddy** [comment]
SteadXP data is encrypted and won't be supported in Gyroflow.

You can use a different gyro logger.
For example this https://shop.m5stack.com/products/atoms3-dev-kit-w-0-85-inch-screen
Firmware from here: https://github.com/VladimirP1/esp-gyrologger/suites/12973845291/artifacts/701827462
esp-gyrologger project: https://github.com/VladimirP1/esp-gyrologger
Pin configuration:
SDA: 38
SCL: 39
Button: 41

I'll add a more detailed documentation on this later to the official docs, but you can always ask on Discord with any questions/issues
