### ISSUE TITLE
translations in dropdown menues are not shown (worked in previous versions)

### ISSUE THREAD

**Issue by 3dkopfkino** [gyroflow/gyroflow#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.0 (gh1232)

### What operating system are you using?

Windows 10 22H2

### What happened?

![image](https://github.com/gyroflow/gyroflow/assets/128091865/7073f266-379a-48f1-bfc6-d044fc5faa35)
when expanding these menus, the english text is shown.
after selection, the field value is the translated text

**Comment by AdrianEddy** [comment]
Not all translations are finished, if you want to help, they are on crodwin https://crowdin.com/project/gyroflow

**Comment by 3dkopfkino** [comment]
these texts are included in resources/translations/de.ts and have been shown in previous builds
![image](https://github.com/gyroflow/gyroflow/assets/128091865/4188ab12-b316-4d92-9853-3c5a8c7c229c)

**Comment by AdrianEddy** [comment]
You're right, sorry. Fixed on latest commit
