### ISSUE TITLE
Changing "Video speed" zooms-in and rotates the video

### ISSUE THREAD

**Issue by Fedess1986** [gyroflow/gyroflow#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5 gh1238

### What operating system are you using?

Windows 10 22H2 19045.2846

### What GPU are you using?

AMD RX6600XT 8GB

### What happened?

When changing "video speed" to any different than 100%, the clips zoom-in a ridicously big amount, and rotates the video 90 degree
![video speed 100](https://github.com/gyroflow/gyroflow/assets/134018336/74eed53e-f43e-47ca-8e61-c5d51a87d008)
![video speed other than 100](https://github.com/gyroflow/gyroflow/assets/134018336/dac99b10-e455-4529-9a07-983e3431650f)

**Comment by AdrianEddy** [comment]
Rotation is fixed in eac4d7ddf4699ccea91b99b35449c3ad9f80627b
Zooming is normal, because you have "Static zoom" selected and changing video speed increases smoothness (you can uncheck these 2 checkboxes next to the speed slider)

**Comment by Fedess1986** [comment]
Ohh ok, I thougth that video speed would just accelerate the video as is, but you considered the smoothing timing/settings. Thank you for the clarification. Makes me think of time-lapse video, which I believe this is targeted to.
