### ISSUE TITLE
Add "Create keyframe" 

### ISSUE THREAD

**Issue by Fedess1986** [gyroflow/gyroflow#655]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

When working with keyframes, it is useful to add a keyframe at a specific point with no change of the slider value, to operate with another keyframe in a specific interval of time.
As it is now, it´s needed to move the slider and then put it´s original value back, to generate the keyframe.

**Comment by AdrianEddy** [comment]
Done in e4236f2e99f3f52f10dcdaddb10407b5cc52299a
