### ISSUE TITLE
Black frames not working

### ISSUE THREAD

**Issue by victorlysak** [gyroflow/gyroflow#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.1

### What operating system are you using?

Windows, Linux

### What GPU are you using?

NVIDIA GeForce RTX 2060 SUPER

### What happened?

Tried to render only the last 20% of a 25 minute video file with the option "Use black frames outside trim range" to preserve the file length as I need to sinc its sound with the sound from another device.

The size of the exported file (dnxhd, dnxhr hq) with 80% of the black frames is exactly the same as the whole rendered file without black frames.

I think the option "Use black frames outside trim range" doesn't work as intended.

Or am I doing anything wrong?

thank you

**Comment by AdrianEddy** [comment]
This only works for Long-GOP codecs like H264 and H265. 

ProRes and DNxHR store each frame idependently and have constant bitrate and the frame content doesn't matter, so it doesn't compress black frames better than normal frames.

**Comment by victorlysak** [comment]
thank you
