### ISSUE TITLE
Issue: 3 Videos and GCSV are joined with file-joiner, but the joined video is not stabilized, while individually each video stabilizes ok

### ISSUE THREAD

**Issue by lesau** [gyroflow/gyroflow#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [x] I have tried the latest build

### Gyroflow version

1.5.1

### What operating system are you using?

Windows 10 Enterprise 19045.3086

### What GPU are you using?

Intel® UHD Graphics for 10th Gen Intel® Processors

### What happened?

Hi, I tried joining 3 video file chapters from the split video made by CadDx Walnut camera using GF 1.5.1. GF joined them successfully and also created a joined .gcsv with the same name as described in https://docs.gyroflow.xyz/app/getting-started/file-joiner. However, the video doesn't get stabilized even around the green labeled sync points. In the GUI, I see 4 red and 2 green labeled sync points, gyro data appears empty/flat in the middle part of the joined video that corresponds to the 2nd gcsv file (see screenshot below), and the video is not stabilized in either of the 3 joined videos time frames. 

Video captured by Walnut camera in 4000x3000, 29.97fps, data rate 100kbps, bit rate 128kbps, flat color, 1/60 exposure, ISO 100. 
GF Settings: FOV 1.0, DEFAULT smoothing, smoothness 0.75, zooming speed 2.5, rolling shutter left at defaults see below. See screenshot.
Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz  

Picture: 3 videos/gcsv files joined, but the you can see that GF doesn't show gyro data for the 2nd video:
![image](https://github.com/gyroflow/gyroflow/assets/7042872/d2ce2046-0970-40ed-98e8-84acc13be011)

Picture: zoomed into one of the sync points in the 1st joined video. Seems to track, but the video preview still looks shaken.
![image](https://github.com/gyroflow/gyroflow/assets/7042872/870d2d63-2e8b-40f5-9916-20046a28165b)

**TEST 2**: In another test, each video stabilizes properly by itself without joining using the same stabilization settings. So, something is iffy with the joining. 

**TEST 3**: I re-run with the nightly build gh1301 - same shaking with the same settings and 5 auto sync points. Increased to 30 auto sync points (doesn't allow to select more), slight improvement in the first video, but lots of wobble after 3:40-5min of the 1st video and similar 2nd video.
![image](https://github.com/gyroflow/gyroflow/assets/7042872/1df190ea-f63c-473f-b35b-298eab5228b1)

**TEST 4**: Changed smoothing to Plain 3D 0.50 & 1.0 - similar wobble.

---
1st gyro file of the 3-part video: https://drive.google.com/file/d/1vRdKt558ULQdTnXYM08-F_TvIxy3vopO/view?usp=drive_link
2nd gyro file of the 3-part video: https://drive.google.com/file/d/1kZA5uyJFaputDoGh7dze65B_bsw6sTrp/view?usp=drive_link
3rd gyro file of the 3-part video: https://drive.google.com/file/d/1pQkdEl-gbhCKtB2Ilh_TWHXniIRxe2N7/view?usp=drive_link

1st video file: https://drive.google.com/file/d/11WcStozQ6yQz325yCKUL5z1w1G28QTI6/view?usp=sharing
2nd video file: https://drive.google.com/file/d/1ykZ4Uvz8gXWzWBlKkn25-61VS6Wd3vcZ/view?usp=sharing

1st/2nd gyro files joined by GF: https://drive.google.com/file/d/11x1_1VhOgubvqTv29mfD1Oo615RvG5QA/view?usp=drive_link
1st/2nd video files joined by GF: https://drive.google.com/file/d/1UMx2_1HxbuXEYz1lqO3q2KmQQ-s3B4Dl/view?usp=drive_link

I can upload the final video if necessary

**Comment by AdrianEddy** [comment]
Should be fixed in 76853f81a0a13ed9f99462fb4de414654314dd72
https://gyroflow.xyz/devbuild/?autodownload

BTW: Is the Walnut on latest firmware?

**Comment by lesau** [comment]
@AdrianEddy , thanks, this fixed the issue! Thanks for the quick turnaround! Yes, used the latest Walnut firmware.
