### ISSUE TITLE
Gyroflow Crash In New Driver Rx550

### ISSUE THREAD

**Issue by dalem-sinten** [gyroflow/gyroflow#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

Gyroflow 1.5.1

### What operating system are you using?

Windows 10

### What GPU are you using?

AMD RX 550

### What happened?

After i launch Gyroflow, and drag my file. Gyroflow start to analyzing file, and usually crash in 20-30%. That crash also make my gpu crash and enter to safe mode (amd safe mode). after i restart my cpu then opening Gyroflow again. I can export my file without analyzing. It's happen in newer driver version of amd rx550 (above 2019).

After i rollback to old driver (12062019), everything perfectly works. No more crash, I make this report with hope it can help other user or maybe for better experience from Gyroflow. Sorry if my english isn't good and thank you Gyroflow for this beautifull apps

**Comment by AdrianEddy** [comment]
Thanks for letting us know, I added this to the documentation here https://docs.gyroflow.xyz/app/hardware-acceleration/amd
I'll close this issue since there's nothing else I can do on my side
