### ISSUE TITLE
G-Force Telemetry with visual output

### ISSUE THREAD

**Issue by GtelemetryPLS** [gyroflow/gyroflow#680]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I would love a feature like the G-force circle you can create on your GoPro cameras. So either create the circle directly when rendering the stabilized video or render a separate video file with the circle and a clear background so that it can be overlayed over a video when editing.

The required data is obviously already there after being multiplied by the ascale value. Maybe you could use the existing gyro filters to make the numbers and the dot in the circle somewhat readable.

In this case, would it be possible to create a G-force circle with a red dot dancing around inside the circle? And maybe a number with one decimal place beside the x and z axis? Displaying the cornering and accelerating force for a car for example.

I really like all the information on this one. (BeamNG Drive)
But having short-term peak values displayed in orange and having two dots with two different gyro filters is probably overkill.
![Screenshot 2023-07-14 105235](https://github.com/gyroflow/gyroflow/assets/139540905/4ccf385e-dcf8-4171-85bd-1db749eafbd7)

Relatively simple but not much information. (GoPro)
![Screenshot 2023-07-14 105926](https://github.com/gyroflow/gyroflow/assets/139540905/b387e638-55d5-4fbc-9cc6-86b635598394)

Unnecessarily complicated and not much data displayed. (F1 Telemetry)
![Screenshot 2023-07-14 112044](https://github.com/gyroflow/gyroflow/assets/139540905/74fbea4a-808a-4fd3-b17d-f7c38b922fdb)

I hope there is no existing request already, but I did my best and did not find one...

**Comment by AdrianEddy** [comment]
This is out of scope of Gyroflow - it doesn't have ability to draw any overlays on the image and I don't think it should.
This is a job for https://goprotelemetryextractor.com/telemetry-overlay-gps-video-sensors
Stabilize the video first, then add the overlay using that
