### ISSUE TITLE
Sync build number with GitHub Repo Count

### ISSUE THREAD

**Issue by latenitefilms** [gyroflow/gyroflow#682]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

As discussed on Discord:

<img width="816" alt="image" src="https://github.com/gyroflow/gyroflow/assets/22286696/521821f5-4d43-47a1-a039-859810198df5">

> It might be worth making the build number tied to the GitHub repo commit number, to make it easier to upload new builds to TestFlight, etc. as each build number will need to be unique.
> Using something like `git rev-list 3c7125c4 --count`.
> 
> Python: 
> 
> ```python
> local BUILD_NUMBER ; BUILD_NUMBER=$(git rev-list "$(git symbolic-ref HEAD | sed -e 's,.*/\\(.*\\),\\1,')" --count)
> ```

**Comment by AdrianEddy** [comment]
This is done in latest CI
