### ISSUE TITLE
End of clip problem

### ISSUE THREAD

**Issue by victorlysak** [gyroflow/gyroflow#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

152

### What operating system are you using?

Win, Linux

### What GPU are you using?

Nvidia RTX2060 SUPER

### What happened?

When in Gyroflow I render 2 or more untrimmed video clips that were shot as one video, I mean like with gopro continuous shooting where it creates many video files, and then try to join them together on my timeline, I get a jump on the border of where one clip ends and the next starts.

No trimming is used in Gyroflow, just full clips.
All the setting for all the clips are exactly the same.
But it looks like some frames at the end of clip are missing or maybe something else?

A few years ego, when I did similar clips with reelsteady there was no interuption visible, no jumping.

So, maybe there is some sort of a bug?

thank you.

**Comment by AdrianEddy** [comment]
Drag 2 files to gyroflow together, it will ask to merge it first, then stabilize
