### ISSUE TITLE
Gyroflow Davinci Plugin problem

### ISSUE THREAD

**Issue by pikkec** [gyroflow/gyroflow#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.2.

### What operating system are you using?

MacOS

### What GPU are you using?

Macbook m2

### What happened?

Hi there.

I have been using gyroflow with Davinci Resolve 18 for a project and it has worked well so far. I've been making project files in gyroflow, and then importing them into Davinci, using the davinci plugin (in open fx), and I always got the same result in Davinci as I did in gyroflow, everything was stabilized with the same kind of settings, and I could then still fine tune it Davinci.
Lately, however, I can't seem to get it to work anymore - and I haven't changed my workflow. I stabilize (auto-sync) the video file in Gyroflow, and when I preview it there, and it works well. Then I export the file (I tried several export types as well) and import it into Davinci and it loads the file, everything looks as it should, but the video file is not stabilized - it is only cropped in. So I can see the settings I have tweaked in gyoflow, and the crop is applied but no other setting seems to be applied to the footage. The footage remains shaky.

Has anyone experienced this? Is it a bug? 

If I use the project files that I stabilized some time ago, it still works. I tried uninstalling gyroflow and nothing changed. Could I be doing something wrong?

Thanks for the help

**Comment by AdrianEddy** [comment]
Have you installed latest Gyroflow plugin v1.2.2? Also which camera are you using?
