### ISSUE TITLE
Add button that opens Troubleshooting page on Error Alert

### ISSUE THREAD

**Issue by latenitefilms** [gyroflow/gyroflow#691]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Any error messages like this:

![image](https://github.com/gyroflow/gyroflow-ofx/assets/22286696/31db117a-e6d8-4cbe-a44a-c49f927b4ff8)

Should have a button that says **Open Documentation** that launches this URL:

https://docs.gyroflow.xyz/app/getting-started/troubleshooting

**Comment by AdrianEddy** [comment]
Done in 4006850
