### ISSUE TITLE
Crash when attempting an export with GPU rendering

### ISSUE THREAD

**Issue by matejkarasek** [gyroflow/gyroflow#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.5.2 gh1324

### What operating system are you using?

Win11 Home, 22H2, build 22621.1992

### What GPU are you using?

nVidia GeForce MX350

### What happened?

When I hit the Export button with 'Use GPU encoding' enabled, Gyroflow crashes.
Pre v 1.5 versions (e.g. 1.4.2) would show an error message about outdated/unsupported driver.

Reproducible with the GoPro 10 example video.

### Relevant log output

11:49:56 [DEBUG] (1) gyroflow::rendering: Possible encoders with Nvidia: [("h264_nvenc", true), ("h264_mf", true), ("libx264", false)]
11:49:56 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: [enc] codec type AV_HWDEVICE_TYPE_CUDA 0, for: h264_nvenc
11:49:56 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: HW formats: [CUDA]
11:49:56 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: SW formats: [NV12, YUV420P, YUVA420P, YUV444P, P010LE, P016LE, YUV444P16LE, BGRZ, RGBZ]
11:49:56 [DEBUG] (2) gyroflow::rendering: ffmpeg_hw::supported_gpu_backends: ["cuda", "dxva2", "qsv", "d3d11va"]
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: [dec] codec type AV_HWDEVICE_TYPE_DXVA2 0
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: HWDevice::from_type AV_HWDEVICE_TYPE_DXVA2, device: None
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_processor: Selected HW backend AV_HWDEVICE_TYPE_DXVA2 (dxva2) with format Some(AV_PIX_FMT_DXVA2_VLD)
11:49:56 [DEBUG] (2) gyroflow::rendering: proc.gpu_device: Some("dxva2")
11:49:56 [DEBUG] (2) gyroflow::rendering: Possible encoders with Nvidia: [("h264_nvenc", true), ("h264_mf", true), ("libx264", false)]
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: [enc] codec type AV_HWDEVICE_TYPE_CUDA 0, for: h264_nvenc
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: HW formats: [CUDA]
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: SW formats: [NV12, YUV420P, YUVA420P, YUV444P, P010LE, P016LE, YUV444P16LE, BGRZ, RGBZ]
11:49:56 [DEBUG] (2) gyroflow::rendering: video_codec: Some("h264_nvenc"), processing_order: PreConversion
11:49:56 [DEBUG] (2) gyroflow::rendering: start_us: 0, render_duration: 23090, render_frame_count: 1384
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_processor: Codec formats: [YUV420P, NV12, P010LE, YUV444P, P016LE, YUV444P16LE, BGRZ, BGRA, RGBZ, RGBA, X2RGB10LE, X2BGR10LE, GBRP, GBRP16LE, CUDA, D3D11]
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_processor: Output metadata: {"major_brand": "mp41", "minor_version": "538120216", "compatible_brands": "mp41", "creation_time": "2022-05-02T09:54:22.000000Z", "firmware": "H21.01.01.20.00"}
11:49:56 [ERROR] [hevc @ 000001A87A77D040] Failed setup for format dxva2_vld: hwaccel initialisation returned error.
11:49:56 [DEBUG] (2) gyroflow_core::stabilization: Setting device 2
11:49:56 [DEBUG] (2) gyroflow_core::gpu::wgpu: WGPU adapter (0): AdapterInfo { name: "NVIDIA GeForce MX350", vendor: 4318, device: 7316, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "511.69", backend: Vulkan }
11:49:56 [DEBUG] (2) gyroflow_core::gpu::wgpu: WGPU initializing adapter #0
11:49:56 [INFO] Initialized wgpu for (1920, 1080, 1920) -> (1920, 1080, 1920) | key: 554466488opencv_fisheye80(1920, 1080)(1920, 1080)
11:49:56 [DEBUG] (2) gyroflow_core::stabilization: Setting device 2
11:49:56 [DEBUG] (2) gyroflow_core::gpu::wgpu: WGPU adapter (0): AdapterInfo { name: "NVIDIA GeForce MX350", vendor: 4318, device: 7316, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "511.69", backend: Vulkan }
11:49:56 [DEBUG] (2) gyroflow_core::gpu::wgpu: WGPU initializing adapter #0
11:49:56 [INFO] Initialized wgpu for (960, 540, 960) -> (960, 540, 960) | key: 4104633768opencv_fisheye80(960, 540)(960, 540)
11:49:56 [DEBUG] (2) gyroflow_core::stabilization: Setting device 2
11:49:56 [DEBUG] (2) gyroflow_core::gpu::wgpu: WGPU adapter (0): AdapterInfo { name: "NVIDIA GeForce MX350", vendor: 4318, device: 7316, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "511.69", backend: Vulkan }
11:49:56 [DEBUG] (2) gyroflow_core::gpu::wgpu: WGPU initializing adapter #0
11:49:56 [INFO] Initialized wgpu for (960, 540, 960) -> (960, 540, 960) | key: 4104633768opencv_fisheye80(960, 540)(960, 540)
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Hardware transfer formats from GPU: None
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: hw_device_type: Some(AV_HWDEVICE_TYPE_CUDA), encoder_pixel_format: None
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: Setting output pixel format: YUV420P, color range: JPEG
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_video: hw_device_type Some(AV_HWDEVICE_TYPE_CUDA)
11:49:56 [DEBUG] (2) gyroflow::rendering::ffmpeg_hw: Setting hw_device_ctx 0x1a8570c7e00
11:49:56 [DEBUG] (2) gyroflow::rendering: [h264_nvenc @ 000001A87A77DC40] Loaded Nvenc version 11.1
11:49:56 [WARN] [h264_nvenc @ 000001A87A77DC40] Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
11:49:56 [WARN] [h264_nvenc @ 000001A87A77DC40] The minimum required Nvidia driver for nvenc is 522.25 or newer
11:49:56 [ERROR] [h264_nvenc @ 000001A87A77DC40] OpenEncodeSessionEx failed: unsupported device (2): (no details)

**Comment by AdrianEddy** [comment]
This should be fixed in latest dev build, please test and let me know https://gyroflow.xyz/devbuild/

**Comment by AdrianEddy** [comment]
Should be fixed in latest dev build https://gyroflow.xyz/devbuild/

**Comment by matejkarasek** [comment]
I confirm the error message now shows up correctly again, thanks!
