### ISSUE TITLE
Export outputs green frames

### ISSUE THREAD

**Issue by matejkarasek** [gyroflow/gyroflow#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

v1.5.2 gh1324

### What operating system are you using?

Win11 Home, 22H2, build 22621.1992

### What GPU are you using?

nVidia GeForce MX350

### What happened?

No matter what settings or file format I use, when I export I only get green frames in the output video/images (png).
The video is correctly stabilized and displayed in the preview window, just the export is not working.

Using default settings, GPU encoding unticked (so CPU encoding used0.

Same result observed in older Gyroflow versions and with various input files (e.g. GoPro Hero 10 example video), so seems to be related to my software and hardware configuration.

Examples of the output are below

https://github.com/gyroflow/gyroflow/assets/10943061/4650e5bb-de56-4990-a29d-5afaefef3c44

![GoPro Hero 10_stabilized_00001](https://github.com/gyroflow/gyroflow/assets/10943061/e1ed22ac-77af-44fa-9695-16773a4a4575)
![GoPro Hero 10_stabilized_00002](https://github.com/gyroflow/gyroflow/assets/10943061/98e4785e-7448-4a93-811d-8badba1e142d)
![GoPro Hero 10_stabilized_00003](https://github.com/gyroflow/gyroflow/assets/10943061/2210891e-6ee8-4c9b-ad4f-543bd66fbcbe)

**Comment by AdrianEddy** [comment]
Your GPU is too old to properly decode this codec. Uncheck "Use GPU decoding" in Advanced. Note that this is different than GPU encoding which is in Export settings.

**Comment by matejkarasek** [comment]
I see, I assumed unchecking "Use GPU encoding" in the export settings will force the use of CPU everywhere...

In any case, this got fixed with the latest drivers. 
Prior to updating the drivers, selecting either the [wgpu] (Dx12) or [OpenCL] device options also fixed the export (so only [wgpu] (Vulcan) gave the green frames). Might be useful for others facing the same issue...

Thanks!
