### ISSUE TITLE
Terrible fonts on Linux

### ISSUE THREAD

**Issue by boris-gu** [gyroflow/gyroflow#698]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

This is more of a "problem" rather than a "feature request". The fact is that on Linux Gyroflow has disgusting fonts.

The font of the interface (the one that is bold) is stretched too much, and the font for the data, on the contrary, is too narrow and difficult to read.

Please fix it or tell me how to fix it yourself on my computer
![Снимок экрана от 2023-08-06 00-38-21](https://github.com/gyroflow/gyroflow/assets/44787162/906ce33b-7d2a-4fe5-95ec-44997a3bcf36)

**Comment by AdrianEddy** [comment]
Hmm, the font of the UI is "Arial" that should be available everywhere by default, but that font on your screenshot doesn't look like it? Maybe you don't have it so it uses some fallback font? please check if you can install Arial on your system

**Comment by boris-gu** [comment]
There is an Arial font in my system

![image](https://github.com/gyroflow/gyroflow/assets/44787162/4f014eea-c898-4a01-ab11-7f4528f84c85)

**Comment by AdrianEddy** [comment]
Try to set some of these environment variables before starting Gyroflow:
`export QML_USE_GLYPHCACHE_WORKAROUND=1`
`export QSG_PREFER_FULLSIZE_GLYPHCACHE_TEXTURES=1`
`export QML_DISABLE_DISTANCEFIELD=1`

I'm not sure why it looks like that on your system, it looks ok on the Linuxes i tested and nobody else reported such issue

**Comment by boris-gu** [comment]
It didn't change anything

![image](https://github.com/gyroflow/gyroflow/assets/44787162/c057804c-faf0-4c40-9d7b-32d2790f456e)

**Comment by AdrianEddy** [comment]
What if you run the .tar.gz package instead of AppImage?

**Comment by boris-gu** [comment]
Without changes

**Comment by AdrianEddy** [comment]
How does English language look like?

**Comment by boris-gu** [comment]
I tried to change the language, first by changing the language of the entire system, then by changing the environment variables. But for some reason Gyroflow did not change the language to English.

If it helps a lot, then I can install a virtual machine with English localization, but it takes time

![image](https://github.com/gyroflow/gyroflow/assets/44787162/8d30d86d-c230-42a3-98b8-64a512a20f28)

**Comment by AdrianEddy** [comment]
The language is in Advanced panel on bottom right

**Comment by AdrianEddy** [comment]
the screenshot you posted now looks better, what did you change? It's not bold and stretched anymore

**Comment by boris-gu** [comment]
Yes, you're right, I just noticed it now  
If I run `LC_ALL=C ./Gyroflow-linux64.AppImage`, then the fonts come back to normal

**Comment by boris-gu** [comment]
So, this could be called a hack rather than a fix, but I'm quite happy with it. I'll just create a shortcut to run Gyroflov properly.

Thank you very much for the reply
