### ISSUE TITLE
Add minimum width and height to application window on Mac

### ISSUE THREAD

**Issue by latenitefilms** [gyroflow/gyroflow#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.2

### What operating system are you using?

macOS 12.6.6

### What GPU are you using?

Apple M1 Max

### What happened?

There's currently no limits on the size of the main Gyroflow window on Mac.

This means you can drag it so small it becomes usable:

<img width="525" alt="image" src="https://github.com/gyroflow/gyroflow/assets/22286696/dd384f20-9042-494e-916a-8cef097df607">

There should be some minimum width and height limits added. Something like this:

<img width="1174" alt="Screen Shot 2023-08-06 at 7 04 52 pm" src="https://github.com/gyroflow/gyroflow/assets/22286696/3d15da4b-8b82-4ba0-94c7-3e9c1afb5595">

This might also tie into making the Gyroflow UI more friendly on mobile devices and tablets.

**Comment by AdrianEddy** [comment]
Added in aa11e55
