### ISSUE TITLE
Automatically detect Runcam gyro files when loaded video

### ISSUE THREAD

**Issue by minzukas** [gyroflow/gyroflow#70]
### Gyroflow version

V1.0.0

### What operating system are you using?

Ubuntu 20.04 LTS

### What GPU are you using?

-

### What happened?

Using appimage on ubuntu and selecting Runcam Orange 5 video does not automatically upload .csv gyro. Manual selection not possible as movement file type does not show .csv extension.

**Comment by minzukas** [comment]
Workaround is drag and drop .csv ;)

**Comment by minzukas** [comment]
Found a working solution

**Comment by AdrianEddy** [comment]
let's keep this open, it can be improved

**Comment by AdrianEddy** [comment]
Done in https://github.com/AdrianEddy/telemetry-parser/commit/71dd89241ac931f88020bf929f70a347fb7c1252
