### ISSUE TITLE
About Default Video Output Path

### ISSUE THREAD

**Issue by hzjianglf** [gyroflow/gyroflow#701]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

After opening Gyroflow, when the first video specifies a custom output path, can the second video file default to the output path of the previous video? This will be much more convenient.

**Comment by AdrianEddy** [comment]
Done in latest dev build, you can active it under `Export settings -> Advanced -> Preserve export parameters` 
https://gyroflow.xyz/devbuild/

**Comment by hzjianglf** [comment]
Thank you, the development version has been downloaded, but the output video has no content ，all green screen。

**Comment by AdrianEddy** [comment]
Please upload log file

**Comment by AdrianEddy** [comment]
That should be fixed now, try downloading again from the same link

**Comment by hzjianglf** [comment]
Often, we default to the same bitrate as the source material when gyroflow outputting。

**Comment by AdrianEddy** [comment]
In latest dev build, these two parameters are separated
