### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by junior-pl** [gyroflow/gyroflow#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

1.5.2

### What operating system are you using?

Windows 10 Home 22H2

### What happened?

The program crashes while uploading the file

### Relevant log output

```shell
13:14:08 [INFO] [MDK] 0.21.1 (git eee6bb2) - Multimedia Development Kit. Copyright (c) 2016-2023 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600/10.0.19045 x86_64; MSVC1935; MSVCRT14.35.32215.0/msvcp140.dll; 17:06:00 Jul 12 2023
13:14:08 [DEBUG] (1) gyroflow: [in main] Qt version: 6.5.1
13:14:08 [DEBUG] (1) gyroflow: Gyroflow 1.5.2
13:14:08 [DEBUG] (1) mdk: [MDK] 3mdk verify key signature ok
13:14:08 [DEBUG] (1) mdk: [MDK] 3mdk license key restrictions: OpenSource,
13:14:08 [DEBUG] (1) mdk: [MDK] key time: -1
13:14:08 [DEBUG] (1) mdk: [MDK] check version
13:14:08 [DEBUG] (1) mdk: [MDK] user module: C:\Program Files\Gyroflow-windows64\Gyroflow.exe
13:14:08 [DEBUG] (1) mdk: [MDK] user module: C:\Program Files\Gyroflow-windows64\Gyroflow.exe
13:14:08 [DEBUG] (1) mdk: [MDK] 3mdk license key for app: gyroflow
13:14:08 [DEBUG] (2) gyroflow::util: Minidump uploaded: OK
13:14:09 [WARN] qrc:/src/ui/main_window.qml:28:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:09 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("Intel(R) OpenCL") Ok("OpenCL 1.2") ["Intel(R) HD Graphics 4600"]
13:14:09 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("NVIDIA CUDA") Ok("OpenCL 1.1 CUDA 6.5.51") ["GeForce GT 220"]
13:14:09 [INFO] OpenCL Platform: NVIDIA CUDA, ext: Extensions { inner: "cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d9_sharing cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts" } Device: NVIDIA Corporation GeForce GT 220
13:14:09 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: create AV_HWDEVICE_TYPE_CUDA
13:14:09 [DEBUG] (1) gyroflow::rendering::ffmpeg_hw: HWDevice::from_type AV_HWDEVICE_TYPE_CUDA, device: None
13:14:09 [ERROR] [AVHWDeviceContext @ 000001B8EC361B40] Cannot load cuDevicePrimaryCtxRetain
13:14:09 [ERROR] [AVHWDeviceContext @ 000001B8EC361B40] Could not dynamically load CUDA
13:14:09 [DEBUG] (1) gyroflow::rendering: Failed to create specified HW device: AV_HWDEVICE_TYPE_CUDA

13:14:09 [DEBUG] (1) gyroflow::rendering: GPU type: Nvidia, from name: nvidia corporation geforce gt 220
13:14:09 [WARN] D3D11 smoke test failed (failed to create vertex shader)
13:14:09 [WARN] qrc:/src/ui/menu/Synchronization.qml:17:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:09 [WARN] qrc:/src/ui/menu/Stabilization.qml:25:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:10 [WARN] qrc:/src/ui/menu/Export.qml:76:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:10 [WARN] qrc:/src/ui/menu/Advanced.qml:15:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:10 [INFO] GPU list: ["[OpenCL] Intel(R) OpenCL Intel(R) HD Graphics 4600: 1.2", "[OpenCL] NVIDIA CUDA GeForce GT 220: 1.0", "[wgpu] Intel(R) HD Graphics 4600 (Dx12)"]
13:14:10 [WARN] qrc:/src/ui/components/Timeline.qml:161:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:10 [INFO] Lens profiles directory: "\\\\?\\C:\\Program Files\\Gyroflow-windows64\\camera_presets"
13:14:11 [WARN] qrc:/src/ui/App.qml:64:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
13:14:11 [INFO] Latest version: v1.5.2, current version: 1.5.2
13:14:14 [INFO] Loaded 7460 lens profiles in 3361.070ms
```

**Comment by AdrianEddy** [comment]
Update your GPU drivers: https://downloadmirror.intel.com/30196/a08/win64_15.40.5171.exe
https://www.nvidia.com/content/DriverDownloads/confirmation.php?url=/Windows/342.01/342.01-desktop-win10-64bit-international.exe&lang=us&type=GeForce

GeForce GT 220 is very old and it will not support GPU encoding, so make sure to select Intel in "Device for rendering" or disable GPU encoding

**Comment by junior-pl** [comment]
Drivers updated, settings changed - unfortunately did not help
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12329369/gyroflow.log)

**Comment by AdrianEddy** [comment]
Can you try if it works in latest dev build? https://gyroflow.xyz/devbuild/

**Comment by junior-pl** [comment]
Unfortunately still the same
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12369400/gyroflow.log)

**Comment by AdrianEddy** [comment]
Can you also share the video file you're trying to load?

Also, try to replace these 3 .dll files in the latest dev build directory and let me know if that worked
[mdk.zip](https://github.com/gyroflow/gyroflow/files/12370572/mdk.zip)

**Comment by junior-pl** [comment]
Next still the same
![gf-plik](https://github.com/gyroflow/gyroflow/assets/141840374/2b7fe85d-af60-45fb-acd2-cfee53c900e5)

**Comment by junior-pl** [comment]
did not help
https://www.krystianszczypka.pl/projekty/GH012502.MP4

**Comment by AdrianEddy** [comment]
What if you replace these dlls?
[ffmpeg.zip](https://github.com/gyroflow/gyroflow/files/12373692/ffmpeg.zip)

Also try this: Move the Gyroflow folder from Program files to some writable location, like to desktop
Then after you run it and it crashes, there should be *.dmp file created, please send it

**Comment by AdrianEddy** [comment]
Ok, please do this: Download latest dev build from here https://nightly.link/gyroflow/gyroflow/workflows/release/master/Gyroflow-windows.zip, extract it somewhere with write permissions like on Desktop, open it and try to load the file. After it crashes, a *.dmp file should be created, please upload it

**Comment by junior-pl** [comment]
The program launched on the desktop, then crashes
[Gyroflow-windows64-pliki.zip](https://github.com/gyroflow/gyroflow/files/12375841/Gyroflow-windows64-pliki.zip)

**Comment by AdrianEddy** [comment]
Please check latest dev build now and let me know if it works https://nightly.link/gyroflow/gyroflow/workflows/release/master/Gyroflow-windows.zip

**Comment by AdrianEddy** [comment]
czyli teraz program się nie wyłączył, ale nie wczytuje też pliku do końca?
Wrzuć też plik gyroflow.log

**Comment by junior-pl** [comment]
Program się wyłacza, ale przez moment widać taki bład
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12401826/gyroflow.log)

Dzięki za cierpliwość

**Comment by junior-pl** [comment]
Jest jedna różnica co do poprzednich wersji, teraz mogę bez problemu wrzucić pllik MP4 z szachownicą żeby utworzyć nowy profil obiektywu.

**Comment by AdrianEddy** [comment]
Te sterowniki Intela stąd zainstalowałeś? https://downloadmirror.intel.com/30196/a08/win64_15.40.5171.exe
Teraz jest inny błąd niż wcześniej, związany z OpenCL, a OpenCL jest w sterownikach

**Comment by junior-pl** [comment]
Tak, ale zainstaluje jeszcze raz dla pewności

**Comment by AdrianEddy** [comment]
Powinno już wszystko działać w najnowszej https://gyroflow.xyz/devbuild/
Z tym OpenCL może być problem ze względu na sterowniki, ale możesz dodać `set NO_OPENCL=1` do tego pliku `Gyroflow_with_console.bat` i z tego uruchamiać

**Comment by PaxaPavlo** [comment]
The same problem
