### ISSUE TITLE
when does Gyroflow support windows 11

### ISSUE THREAD

**Issue by yaleyip** [gyroflow/gyroflow#706]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Gyroflow cracks down without any warnings when it run in windows 11.
There are some messages found at log file.

---------------------------------------------------------
15:10:00 [INFO] [MDK] 0.21.1 (git eee6bb2) - Multimedia Development Kit. Copyright (c) 2016-2023 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600/10.0.22621 x86_64; MSVC1935; MSVCRT14.35.32215.0/msvcp140.dll; 17:06:00 Jul 12 2023
15:10:00 [DEBUG] (1) gyroflow: [in main] Qt version: 6.5.1
15:10:00 [DEBUG] (1) gyroflow: Gyroflow 1.5.2
15:10:00 [DEBUG] (1) mdk: [MDK] 3mdk verify key signature ok
15:10:00 [DEBUG] (1) mdk: [MDK] 3mdk license key restrictions: OpenSource,
15:10:00 [DEBUG] (1) mdk: [MDK] key time: -1
15:10:00 [DEBUG] (1) mdk: [MDK] check version
15:10:00 [DEBUG] (1) mdk: [MDK] user module: C:\Program Files\Gyroflow\Gyroflow.exe
15:10:00 [DEBUG] (1) mdk: [MDK] user module: C:\Program Files\Gyroflow\Gyroflow.exe
15:10:00 [DEBUG] (1) mdk: [MDK] 3mdk license key for app: gyroflow
15:10:01 [WARN] qrc:/src/ui/main_window.qml:28:5: QML Settings: The Settings type from Qt.labs.settings is deprecated and will be removed in a future release. Please use the one from QtCore instead.
15:10:02 [DEBUG] (1) gyroflow_core::gpu::opencl: OpenCL devices: Ok("NVIDIA CUDA") Ok("OpenCL 3.0 CUDA 12.0.139") ["Quadro K1200"]

**Comment by yaleyip** [comment]
> It works on Windows 11, make sure to install latest GPU drivers from https://us.download.nvidia.com/Windows/Quadro_Certified/536.96/536.96-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe

Hi AdrianEddy,

I have tried to cleanly install the GPU driver but it does not work either.
No warnings and same messages in log file.
Any clues and/ or tips?

Regards,
Yale

**Comment by AdrianEddy** [comment]
what if you also add `set NO_OPENCL=1` there?

**Comment by yaleyip** [comment]
> what if you also add `set NO_OPENCL=1` there?

wow, it works.
I am curious, K1200 should support OPENCL. It looks that it is not compliant with Gyroflow.

**Comment by AdrianEddy** [comment]
Yes, OpenCL should be provided by the NVIDIA drivers, but apparently it's not. That GPU is quite old and the GPU support is problematic on these old devices. Nothing I can do on my side about it, but using Gyroflow without OpenCL is possible so most things should work

**Comment by yaleyip** [comment]
> Yes, OpenCL should be provided by the NVIDIA drivers, but apparently it's not. That GPU is quite old and the GPU support is problematic on these old devices. Nothing I can do on my side about it, but using Gyroflow without OpenCL is possible so most things should work

AdrianEddy, I see. Thanks for support.
