### ISSUE TITLE
Gyroflow не работает в Davinci Resolve Studio

### ISSUE THREAD

**Issue by makarii-kirillov** [gyroflow/gyroflow#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

Gyroflow v1.5.2

### What operating system are you using?

Windows 10

### What GPU are you using?

nvidia geforce gtx 1060 6gb

### What happened?

Когда я в Davinci Resolve пытаюсь стабилизировать файл  через Gyroflow выдаёт вот такой текст: "Unable to find Groflow app path. Make sure to run Gyroflow app at least once and that version is at least v1.4,3" и ничего не изменяется, хотя отдельно программа Gyroflow работает нормально.
![photo1692183967](https://github.com/gyroflow/gyroflow/assets/142400324/98b383bb-3476-4846-8dad-6c93e508da51)

**Comment by AdrianEddy** [comment]
This should be already fixed in latest dev build of the plugin: https://gyroflow.xyz/devbuild/
