### ISSUE TITLE
Add support for Sony VENICE 2

### ISSUE THREAD

**Issue by latenitefilms** [gyroflow/gyroflow#713]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Add support for the Sony VENICE 2, which apparently has gyro data.

**Comment by AdrianEddy** [comment]
Any sample file?

**Comment by latenitefilms** [comment]
Closed in favour of #610 (as Sony VENICE 2 uses Cooke Metadata for Gyro)
