### ISSUE TITLE
Smoothing adjustable per-axis (RPY)

### ISSUE THREAD

**Issue by malinhiles** [gyroflow/gyroflow#720]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Would be great if there was an "advanced option" to split stabilization smoothness settings into individual adjustments for roll pitch and yaw (referenced to the camera). If this option were enabled, the user would be able to selectively increase or decrease the smoothness for an axis.  This is helpful for when one particular axis might require "more smoothness" than others.

**Comment by AdrianEddy** [comment]
There is, "Per axis" checkbox in advanced in Stabilization tab
