### ISSUE TITLE
Crashing Issue

### ISSUE THREAD

**Issue by TutuFPV** [gyroflow/gyroflow#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

V1.5.2

### What operating system are you using?

Windows 11

### What happened?

My softwere is crashing when i am trying to load a video

### Relevant log output

```shell
Crashing, Closing the app
```

**Comment by AdrianEddy** [comment]
It's fixed in latest dev build https://gyroflow.xyz/devbuild
