### ISSUE TITLE
The reasons to use two different alpha values in default smoothing algo

### ISSUE THREAD

**Issue by ysyscool** [gyroflow/gyroflow#724]
alpha_0_1s and alpha_smoothness. Why do we need these two? 
https://github.com/gyroflow/gyroflow/blob/master/src/core/smoothing/default_algo.rs#L388

**Comment by AdrianEddy** [comment]
the general idea of the "Default" algorithm is this:
1. rotation velocity is calculated for every sample and from that, max velocity and min velocity is determined
2. this sets the scale for smoothing - "Max smoothness" (`alpha_smoothness`) value is used to smooth when the rotation velocity is the minimum and "Max smoothness at high velocity" (`alpha_0_1s`) is used when the rotation speed is the maximum (eg. in a sharp turn). Anything in between uses the values interpolated to be between these 2 values
3. main "Smoothness" (`smoothness`) slider is the "scale" - Set it to "1" to have exactly the behavior described in point 2.
Set it to 2 to have double the behavior, and set to 0.5 to have half of the behavior
