### ISSUE TITLE
Anamorphic Lenses Gyroflow

### ISSUE THREAD

**Issue by GabrielAvastye** [gyroflow/gyroflow#725]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I'm using Sony a7siii with Sirui anamorphic lens and it seems the software doesn't work on this lens. Would be great to have this feature or am I missing something?

**Comment by AdrianEddy** [comment]
It's supported, just use the `Input horizontal stretch` https://docs.gyroflow.xyz/app/getting-started/lens-calibration#input-stretch
