### ISSUE TITLE
[Bug]: no stabilisation for Runcam 5 Orange

### ISSUE THREAD

**Issue by krl91** [gyroflow/gyroflow#73]
### Gyroflow version

1.0 rc

### What operating system are you using?

last macos cersion

### What GPU are you using?

Intel

### What happened?

I'm using Runcam 5 Orange, I followed the documentation:
load video
load csv file
load lense profile
add synch (about 10) point
choose Lock horizon
fov about 2.8
select a window to render
then start the render.

no stabilization at all on rendered file

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1216107/152621800-cb84b39b-205e-4eef-a6c9-feb63254eac2.png">

**Comment by AdrianEddy** [comment]
Does the preview look good? stabilized? Does the same happen with other export formats?

**Comment by ElvinC** [comment]
I have seen another user previously with what looks like the same problem. If you open the csv file in a text editor, is everything `0`? If so, it's an issue with the camera as opposed to Gyroflow.

**Comment by krl91** [comment]
the preview is not good...  :(

**Comment by krl91** [comment]
my bad all are set to zero in csv file
