### ISSUE TITLE
gcsv files nor merged in dev build, works in 1.5.2

### ISSUE THREAD

**Issue by bmsleight** [gyroflow/gyroflow#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

devbuild 2023-09-24

### What operating system are you using?

Ubuntu 22.04.3 LTS

### What GPU are you using?

GP107GLM [Quadro P620]

### What happened?

gcvs file is 0 bytes in dev build, 
1.5mb using 1.5.2

Open 20211023124757_000031.MP4 & 20211023124857_000032.MP4 in GUI. 
Dev build has no gyro data and unable to auto-sync
version 1.5.2 has loaded (automatically using sidecar files) and hence able to autosync

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12709367/gyroflow.log)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12709371/gyroflow.log)

Thanks for you hard work.

**Comment by AdrianEddy** [comment]
Good catch, fixed in latest dev build
