### ISSUE TITLE
GoPro12 profile

### ISSUE THREAD

**Issue by kadirbekov** [gyroflow/gyroflow#735]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Can you add profile for GoPro12 black?

**Comment by AdrianEddy** [comment]
Already supported in the dev build https://gyroflow.xyz/devbuils

**Comment by kadirbekov** [comment]
video looks bad and also Lens profile defined as GoPro11.
![image](https://github.com/gyroflow/gyroflow/assets/7033313/ae7f4462-b420-435a-92df-cea5b0f2b2d8)
