### ISSUE TITLE
render cue will not render when preserve other tracks selected

### ISSUE THREAD

**Issue by someTV** [gyroflow/gyroflow#736]
Have tried rendering on both pc and mac after adding files directly to the render queue with preserve tracks selected and get the error seen in attached file
![GYROFLOWERROR](https://github.com/gyroflow/gyroflow/assets/146143230/2ea1227f-65e8-41e3-8b3a-8f12a11355fd)
Help please for this newbie.
Thanks,
Barnaby

**Comment by AdrianEddy** [comment]
Fixed in e2bed40ed0b96466d44524f07224509c7a0e5b03, will be available in https://gyroflow.xyz/devbuild/ once [this](https://github.com/gyroflow/gyroflow/actions/runs/6330600516) finishes building

**Comment by AdrianEddy** [comment]
Just download from here https://gyroflow.xyz/devbuild/

**Comment by someTV** [comment]
great. any chance for windows? Running on two machines...

**Comment by AdrianEddy** [comment]
it's all there

**Comment by someTV** [comment]
just seeing mac, linux iOS and android, no windows build unless I am blind...

**Comment by someTV** [comment]
Must add as well that this is an awesome tool. I accidentally had gopro cameras remove all processing beyond capturing and did not realize that included all the stabilization info.

**Comment by someTV** [comment]
linking to ping...

**Comment by someTV** [comment]
Ah, I can see it momentarily when I am scrolling through the window but it hides behind the iOS link before I can get to it.

**Comment by someTV** [comment]
can get to it by viewing page source...

**Comment by AdrianEddy** [comment]
ok works ok on Windows, but I'll fix the page when viewed from other system

**Comment by someTV** [comment]
thanks

**Comment by someTV** [comment]
Getting error on windows machine please see attached
Barnaby
323.401.8642

**Comment by AdrianEddy** [comment]
Replying to email with attachments doesn't work, you have to attach in github comment

**Comment by someTV** [comment]
Same error message as before...
![GYROFLOWERROR2](https://github.com/gyroflow/gyroflow/assets/146143230/6182c032-f432-41e2-8316-d62d1779bc20)

**Comment by AdrianEddy** [comment]
I just tested and it works as expected for me. Did you re-add these files to the queue? Does it say `(gh1508)` in the window title?

**Comment by someTV** [comment]
tried it again, same problem, this is where I downloaded gyroflow from: "https://nightly.link/gyroflow/gyroflow/workflows/release/master/Gyroflow-windows.zip">Gyroflow dev build

**Comment by AdrianEddy** [comment]
but the screenshot is from mac?

**Comment by AdrianEddy** [comment]
How did you add the file to the queue? Can you write exact steps you're taking?

**Comment by someTV** [comment]
from pc, window title says Gyroflow 1.5.2 if that is what you are asking regards (gh1508)
dragged the file from folder onto queue, dropped gyroflow preset onto queue, checked settings by clicking edit, then the render button followed by that error message

**Comment by AdrianEddy** [comment]
Window title should say `Gyroflow v1.5.2 (gh1508)`
![image](https://github.com/gyroflow/gyroflow/assets/3849067/d068642b-9d8e-4ab9-b993-5b994ff9deca)

**Comment by AdrianEddy** [comment]
Can you attach that preset?

**Comment by someTV** [comment]
nope.
[CLEORGEhorlock.txt](https://github.com/gyroflow/gyroflow/files/12743798/CLEORGEhorlock.txt)

**Comment by someTV** [comment]
i must not have 1.5.2 (gh1508). Could you send me a direct link to download it?

**Comment by AdrianEddy** [comment]
https://nightly.link/gyroflow/gyroflow/workflows/release/master/Gyroflow-windows.zip

that's the one

**Comment by someTV** [comment]
Got from the dev page! Will let you know how it works in a moment

**Comment by someTV** [comment]
hit render button, vaporized, installing again.

**Comment by someTV** [comment]
ddo I need to do anything with the "Gyroflow.msix" file?

**Comment by AdrianEddy** [comment]
no, just extract the Gyroflow-windows64.zip file

**Comment by someTV** [comment]
Worked on one! Will try a batch. Thank you for your help.

**Comment by someTV** [comment]
Weirdness, on mac batch will render 1 file but when I added four files i got this error message:
![Screenshot 2023-09-27 at 5 15 05 PM](https://github.com/gyroflow/gyroflow/assets/146143230/ffee9b1e-5355-4db2-8318-1320b1ec113e)
PC seems to functiong fine.

**Comment by AdrianEddy** [comment]
maybe you don't have write permissions to that directory? are you using the same preset? preset contains output folder, which will be different on mac and windows, so you have to have 2 presets

**Comment by someTV** [comment]
Will play around with the mac more, it just started when I added two to the batch. It still asks me for a directory even when I drop the preset on it.

**Comment by AdrianEddy** [comment]
It should always ask for directory when dropping video files
It shouldn't ask for directory when dropping preset.
Preset applies only to current files in the queue, it doesn't apply to future files

**Comment by someTV** [comment]
is there a way to make a preset that allows me to choose the output directory after the preset is applied to all files in the queue? Not seeing output directory in the preset menu.

**Comment by AdrianEddy** [comment]
`Output path`
![image](https://github.com/gyroflow/gyroflow/assets/3849067/2d926131-cf0c-42ae-ae3a-45ebc1bc4fb4)

**Comment by someTV** [comment]
I'm blind. Need to go to Hollylodz and have my eyes checked.

**Comment by someTV** [comment]
On pc windows 10 the rendered ".mov" file will not play in quicktime (will play in others such as potplayer or windows media player). This is the error message: "Error -2002: a bad public movie atom was found in the movie 0" 
![qterror](https://github.com/gyroflow/gyroflow/assets/146143230/72b34aa3-06df-490a-8e4c-8d1de8fa280b)

**Comment by AdrianEddy** [comment]
I'm afraid it's outside of my control, ffmpeg renders the file

**Comment by someTV** [comment]
Interesting. Why does the file need to be rendered as a .mov and not as its original container when preserving other tracks? In my case mp4s. Must reiterate how much I like the design and function of the ap.

**Comment by AdrianEddy** [comment]
ffmpeg doesn't know how to include custom binary tracks in the mp4 container, it's simply not implemented there and only implemented for mov. This is also outside of my control

**Comment by someTV** [comment]
could the binary tracks including audio just pass through and not be custom?

**Comment by AdrianEddy** [comment]
they are pass through, but that doesn't change anything, ffmpeg mp4 muxer just can't handle them

**Comment by someTV** [comment]
ok, thanks.
