### ISSUE TITLE
Feature request: option to only apply lens correction, no stabilization

### ISSUE THREAD

**Issue by prochac** [gyroflow/gyroflow#737]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I'm interested in this feature
https://github.com/ElvinC/gyroflow/issues/20

Is it achievable with some fake gyro data?

**Comment by AdrianEddy** [comment]
Just set `No smoothing` and `No zooming` in the Stabilization panel

**Comment by prochac** [comment]
Thanks. I'm new to Gyroflow and during my googling I just found the issue. It is still open, so I thought it's not possible yet. Sry for my dumb issue/question.
