### ISSUE TITLE
[Bug]: very slow on MacBook m1 pro

### ISSUE THREAD

**Issue by bendi89** [gyroflow/gyroflow#74]
### Gyroflow version

1.0 rc1 

### What operating system are you using?

OS X 

### What GPU are you using?

M1 pro 

### What happened?

Very slow on this platform. 2,5 hours to stabilize 3 min of 5k gopro 10 file.

**Comment by AdrianEddy** [comment]
Which export codec? ProRes is not hardware accelerated, use x264 or x265

**Comment by bendi89** [comment]
> Which export codec? ProRes is not hardware accelerated, use x264 or x265

I use x265

**Comment by SebastianKumor** [comment]
@AdrianEddy I did experience similar result on intel macbook pro with radeon pro 5500m and x265. 4k 4:3 4 min video took 3 hours to stabilize. I have run the same clip trough reelsteady to test it and it was done under 1 hour.

**Comment by AdrianEddy** [comment]
Fixed in rc3

**Comment by rcragger** [comment]
Seems to still be an issue on my Macbook Pro 16" with rc3. I suspect that Gyroflow is not switching graphics cards to use 5500m card.

**Comment by JRNYC7** [comment]
I encountered the same issue where it took 3 hours to complete a task that should have taken 2 minutes, all because I was using internal memory. However, the speed increased to just 20 minutes when I switched to external storage.
