### ISSUE TITLE
Gyroflow crashes on file export | Intel UHD Graphics 630

### ISSUE THREAD

**Issue by snekras0v** [gyroflow/gyroflow#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.3

### What operating system are you using?

Windows 10

### What GPU are you using?

Intel(R) UHD Graphics 630

### What happened?

Gyroflow crashes after pressing export button. 
Intel latest driver 31.0.101.2115 is installed.
Quick Sync is supported on Intel(R) UHD Graphics 630.

Tried to switch to [wgpu] - didn't help.
![image](https://github.com/gyroflow/gyroflow/assets/117651095/488a3683-01b2-4c5a-b343-f00c0ccc957a)
CPU only option doesnt work either.

Export works only with "Use GPU encoding" unchecked.

logs are attached:
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12908709/gyroflow.log)

**Comment by AdrianEddy** [comment]
Please try latest dev build https://gyroflow.xyz/devbuild/

**Comment by snekras0v** [comment]
![image](https://github.com/gyroflow/gyroflow/assets/117651095/a8f9ceab-2399-4a53-9578-7d874b7215aa)
it works now with a good fps rate

Adrian thanks for such a quick answer!

**Comment by AdrianEddy** [comment]
What if you change to [wgpu] (Vulkan) in `Device for video processing`?

**Comment by AdrianEddy** [comment]
Please attach gyroflow.log file

**Comment by uavquadfpv** [comment]
> Please attach gyroflow.log file

Back to v1.5.2, when exporting files, the blue screen does not appear. Only version 1.5.3 shows all files with errors displayed in blue on the output video. The same thing happened to my computer when I updated to v1.5.3

**Comment by AdrianEddy** [comment]
Please send me gyroflow.log file from latest dev build, I'll need to see why it happens

**Comment by uavquadfpv** [comment]
> What if you change to [wgpu] (Vulkan) in `Device for video processing`?

Screenshot I just took.

![svbd](https://github.com/gyroflow/gyroflow/assets/148299671/47fdd5e1-6821-48bd-aa21-0b78202f8674)

**Comment by AdrianEddy** [comment]
ok but I need to see the log file after rendering

**Comment by snekras0v** [comment]
please find the log attached
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/12983241/gyroflow.log)

if i change to anything but [wgpu] (Vulkan) the FPS decreases to 2

**Comment by AdrianEddy** [comment]
Should be fixed in latest dev build https://gyroflow.xyz/devbuild/

**Comment by snekras0v** [comment]
it's exporting correct image, but FPS is only 4
is it supposed to be such low?

![image](https://github.com/gyroflow/gyroflow/assets/117651095/2d787709-9c16-434e-bd1f-93e3e5e33d43)

**Comment by AdrianEddy** [comment]
Is there a speed difference between v1.5.2 and this build?
Try also OpenCL and wgpu options. Please also attach the log file after rendering I'll check if everything is as expected

**Comment by snekras0v** [comment]
actually it is the first build i've tried. also didn't find a link to download 1.5.2 as only 1.5.3 is now available.

but still log is attached
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/13025121/gyroflow.log)

**Comment by AdrianEddy** [comment]
v1.5.2 you can download here https://github.com/gyroflow/gyroflow/releases/tag/v1.5.2

Everything appears fine in the log. Intel HD 630 is not the newest so it's possible it takes this slow. You can use H264/AVC instead of HEVC, should be faster

**Comment by snekras0v** [comment]
it is 0.7 FPS in 1.5.2 )

Thanks for your help!

**Comment by AdrianEddy** [comment]
Thanks for testing!
