### ISSUE TITLE
Gyroflow ios blue screen error on iPhone 6s - iPhone 7 

### ISSUE THREAD

**Issue by uavquadfpv** [gyroflow/gyroflow#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

V1.5.3

### What operating system are you using?

ios 15.7.9

### What GPU are you using?

[wgpu] Apple A10 GPU (Metal)

### What happened?

Gyroflow ios blue screen error on iPhone 6s - iPhone X
It first appeared when I installed it on all my existing devices, which are those running iOS 15 or later. I don't know if everyone has the same blue screen phenomenon as me. Hopefully the next version will fix errors on older Apple devices using the iOS 15 operating system.

https://github.com/gyroflow/gyroflow/assets/148299671/cf1c8556-334f-45ad-b304-4278f4583b0d

### Relevant log output

```shell
20210101000723_000003_stabilized_2.mp4
```

**Comment by AdrianEddy** [comment]
This is only in rendered file? Does the preview in app look good?

**Comment by uavquadfpv** [comment]
> This is only in rendered file? Does the preview in app look good?

The preview in gyroflow ios is beautiful, very smooth.

**Comment by uavquadfpv** [comment]
> This is only in rendered file? Does the preview in app look good?

![2023_10_18_09_38_IMG_0005](https://github.com/gyroflow/gyroflow/assets/148299671/84393104-1bb0-4b88-aa29-b77d953f24c5)

Screenshot I just took.

**Comment by AdrianEddy** [comment]
Please check in TestFlight version https://testflight.apple.com/join/e0RI1n5i

**Comment by uavquadfpv** [comment]
> Please check in TestFlight version https://testflight.apple.com/join/e0RI1n5i

Very good! It works very smoothly and quickly on my iphone 7 device. 7.5 fps, awesome. This version will officially go into operation soon.

Thanks you so much!

![2023_10_20_15_44_IMG_0010](https://github.com/gyroflow/gyroflow/assets/148299671/705c08c4-904b-4905-bd7f-6e110c2a770f)
![2023_10_20_15_42_IMG_0009](https://github.com/gyroflow/gyroflow/assets/148299671/ccc2d20a-0ab6-4dc3-8cd4-0bc6bb236e22)
