### ISSUE TITLE
DJI action 4 horizon level

### ISSUE THREAD

**Issue by Marcus677** [gyroflow/gyroflow#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

win10

### What GPU are you using?

gtx1080ti

### What happened?

horizon lock on DJIaction4 does not seem to work. After applying horizon lock, the video seems to be drifting and rotating left and right.

I read DJI forum and there may be horizon balancing issues with the camera? Not sure if its the camera, gyroflow that is the issue. Any idea how to resolve it? Does Gopro have the same issues? I have a gopro 8 and horizon lock works really well.

**Comment by AdrianEddy** [comment]
It depends on hardware, GoPro also sometimes has these issues. There's nothing I can do in Gyroflow about it, but you can [keyframe](https://docs.gyroflow.xyz/app/advanced-usage/keyframes) horizon roll
