### ISSUE TITLE
ffmpeg error: ffmpeg::Error(2: No such file or directory)

### ISSUE THREAD

**Issue by someTV** [gyroflow/gyroflow#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

mac ventura 13.5.2

### What GPU are you using?

apple m1 max

### What happened?

in queue and expected a render to take place
![Screenshot 2023-11-08 at 7 15 49 PM](https://github.com/gyroflow/gyroflow/assets/146143230/d2447e95-ff64-4651-919a-9b0b91ed6a79)

**Comment by AdrianEddy** [comment]
there are some issues with app sandbox, you can install from .dmg as a workaround for now https://nightly.link/gyroflow/gyroflow/workflows/release/master/Gyroflow-macos.zip

**Comment by someTV** [comment]
Thanks, will try
Barnaby
323.401.8642

**Comment by AdrianEddy** [comment]
Please try the TestFlight version and let me know if that fixes your issues: https://testflight.apple.com/join/e0RI1n5i

**Comment by AdrianEddy** [comment]
it's fixed in the testflight version

**Comment by someTV** [comment]
using v1.5.4 (gh1679) and it is working.
Thanks
Barnaby
323.401.8642
