### ISSUE TITLE
Include original filename in Metadata

### ISSUE THREAD

**Issue by Fjordx** [gyroflow/gyroflow#758]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

It would be awesome if one could find the original gopro etc file like GX12345.mp4 from the metadata of the stabilized video. Happens to me a LOT.

Steps to take:
- Add original filename to finished mp4 file metadata (e.g. tag.Content provider or comments property)

**Comment by AdrianEddy** [comment]
Added in latest nightly https://gyroflow.xyz/devbuild/
