### ISSUE TITLE
please keep screen on while export

### ISSUE THREAD

**Issue by DGYT** [gyroflow/gyroflow#759]
### Is there an existing feature request for this?

- [x] I have searched the existing requests

### Description

Android export must keep screen on,but now screen will off while export, cause export pause

can keep screen on by 
getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

**Comment by AdrianEddy** [comment]
Does it really interrupt the render for you? It shouldn't because Gyroflow acquires partial wake lock which should keep the CPU running, even if the screen goes off by itself: https://developer.android.com/training/scheduling/wakelock#cpu

**Comment by DGYT** [comment]
as the video shows,it goes a little in near 1min（seams stopped）

https://github.com/gyroflow/gyroflow/assets/22211278/d630a6de-5b39-4548-8fde-5f894e537205

**Comment by DGYT** [comment]
mistake close

**Comment by AdrianEddy** [comment]
Please try latest apk https://nightly.link/gyroflow/gyroflow/workflows/release/master/Gyroflow-android.zip

**Comment by AdrianEddy** [comment]
it works for me with the latest apk
