### ISSUE TITLE
[Bug]: Semantic versioning issues in Cargo.toml

### ISSUE THREAD

**Issue by atouchet** [gyroflow/gyroflow#76]
### Gyroflow version

n/a

### What operating system are you using?

Windows 10

### What happened?

Crates should not be set as requiring version "*" in Cargo.toml as any breaking chances in a dependency can cause compatibility problems.

**Comment by AdrianEddy** [comment]
I know, this will be sorted out before final v1.0.0 release :)

**Comment by ilya-epifanov** [comment]
@atouchet @AdrianEddy it's not a big deal since it's not a library crate. as soon as there's a `Cargo.lock` and some testing, it's gonna be just fine. So no need to rush it before 1.0.0. It should definitely be done at some point, however

**Comment by AdrianEddy** [comment]
Fixed in 4ccdb1685e6fff44c2d74c08a2bb110794ccdcd9
