### ISSUE TITLE
Gyroflow 1.5.4 cannot open

### ISSUE THREAD

**Issue by RyanFPVwing** [gyroflow/gyroflow#761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

windows 10

### What GPU are you using?

NVIDEA GEFORCE 940MX

### What happened?

Hi, I cannot launch a newly downloaded gyro.exe version 1.5.4.  I am using windows 10, updated geforce 940MX. I have already downloaded the missing .dll files.

**Comment by AdrianEddy** [comment]
What's the problem?

**Comment by RyanFPVwing** [comment]
Hi Adrian,

I need help setting up my gyroflow, I can't open the program with the
latest version.

**Comment by AdrianEddy** [comment]
But what's the problem exactly? Is there any error message?

**Comment by RyanFPVwing** [comment]
There is no error message, I just can't
 VID20231124151223[1].mp4
<https://drive.google.com/file/d/1EN024lyJfdso-T6m56TuRBgwMhB7ppQT/view?usp=drive_web>
 simply run the program. I think I have a compatibility issue, previously
my laptop was in windows 7, I encountered several missing dll. files, I
downloaded the missing files and updated my laptop to windows 10 and still
no progress. Gyroflow is my only way of stabilizing videos from my newly
bought hawkeye 4k thumb camera. Thank you.

**Comment by AdrianEddy** [comment]
Install this https://aka.ms/vs/17/release/vc_redist.x64.exe

And install latest GPU drivers for your GPU, it's very important

**Comment by RyanFPVwing** [comment]
I have already installed that software yesterday but it still does not
work. My GPU(geforce 940mx) is also updated.

**Comment by AdrianEddy** [comment]
What's this laptop model?

**Comment by RyanFPVwing** [comment]
Acer Aspire E 15 core i5

**Comment by gecpogi** [comment]
I am having the same issue. Keeps on loading. I've already installed vc_redist64 and updated my graphics driver to the latest version. I'm using Acer Aspire 7 | Ryzen 5 | RTX3050 | 16gb RAM

Tried reinstalling many times with no luck. Tried the store version and the zip version. It's working fine on my pc but I can't get it to work with my laptop.

![Screenshot 2023-12-07 155504](https://github.com/gyroflow/gyroflow/assets/69830433/0e93271f-cf1f-4353-a6a7-64862c65e8c3)

**Comment by AdrianEddy** [comment]
@gecpogi this is most likely caused by the missing GPU drivers for your **other** GPU, which is integrated in your CPU. You need to install AMD drivers, it'll probably be this one https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-23.11.1-win10-win11-nov3-vega-polaris.exe

**Comment by gecpogi** [comment]
> @gecpogi this is most likely caused by the missing GPU drivers for your **other** GPU, which is integrated in your CPU. You need to install AMD drivers, it'll probably be this one https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-23.11.1-win10-win11-nov3-vega-polaris.exe

Thank you so much. It's working now. :)

**Comment by AdrianEddy** [comment]
@ferdiaz63 Install this driver https://us.download.nvidia.com/Windows/391.35/391.35-notebook-win10-64bit-international-whql.exe

**Comment by RyanFPVwing** [comment]
Thank you @AdrianEddy , I can now open Gyroflow and stabilize my videos, however, I came up with a new problem, I cannot save or export the rendered video clips. 
![error](https://github.com/gyroflow/gyroflow/assets/151829981/f6945c1a-7d5e-4df5-aa4f-03703a48d873)

**Comment by RyanFPVwing** [comment]
Thank you @AdrianEddy <https://github.com/AdrianEddy> , I can now open
Gyroflow and stabilize my videos, however, I came up with a new problem, I
cannot save or export the rendered video clips.

**Comment by AdrianEddy** [comment]
@RyanFPVwing change export codec to H264 or disable GPU encoding

**Comment by RyanFPVwing** [comment]
works like a miracle, thank you @AdrianEddy and to the gyroflow team.
