### ISSUE TITLE
MacOS custom lens profile from BRAW crash

### ISSUE THREAD

**Issue by Mcrubens** [gyroflow/gyroflow#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

macOS Sonoma 14.1.1

### What GPU are you using?

M2 MacBook Pro 13" 2022

### What happened?

I'm trying to create a new lens profile from a BRAW video. Everything seems to work (see uploaded screenshot) until auto calibration reaches 100%. Then Gyroflow crashes.

<img width="1240" alt="Screenshot 2023-11-26 at 20 59 40" src="https://github.com/gyroflow/gyroflow/assets/78466877/d571bae1-83bd-43ea-a9e0-0c7566bdbe42">

**Comment by Mcrubens** [comment]
This is the crash log from MacOS

[Crash log Gyroflow Custom lens profile.txt](https://github.com/gyroflow/gyroflow/files/13467948/Crash.log.Gyroflow.Custom.lens.profile.txt)

**Comment by AdrianEddy** [comment]
It's fixed in latest dev build https://gyroflow.xyz/devbuild
