### ISSUE TITLE
Gyroflow 1.5.4 program closes when trying to load a video file into it

### ISSUE THREAD

**Issue by Kirill-GRO** [gyroflow/gyroflow#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

windows 10 /64

### What GPU are you using?

AMD Radeon R5 m430

### What happened?

Hello. The program loads normally. As soon as I try to load a video file into it, it automatically closes. No messages appear
Laptop HP 15-ba559ur
CPU AMD A8-7410 APU with AMD Radeon R5 Graphics  2.20 GHz 
RAM 8 GB
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/13513551/gyroflow.log)
[6d025ba6-d95b-44d8-8c63-1fbf468643ce.dmp](https://github.com/gyroflow/gyroflow/files/13513553/6d025ba6-d95b-44d8-8c63-1fbf468643ce.dmp)

Tried to download video files from the camera Gopro 6 and ThumbPro 4K in format 1080p 60fps.

**Comment by AdrianEddy** [comment]
Did you install latest GPU drivers from amd.com? the ones from windows update are not enough

**Comment by AdrianEddy** [comment]
Did you try the latest dev build from https://gyroflow.xyz/devbuild/ ?

**Comment by Kirill-GRO** [comment]
Yes, I just tried this version of the program. It also closes itself when trying to open a video file...
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/13513975/gyroflow.log)
[1e1c4f95-a0b2-4c3b-a68e-0a3e004f99f6.dmp](https://github.com/gyroflow/gyroflow/files/13513981/1e1c4f95-a0b2-4c3b-a68e-0a3e004f99f6.dmp)

**Comment by Kirill-GRO** [comment]
I did everything as you wrote. The program still closes...
[2a345313-1968-4e10-96bc-c7e3ba79e963.dmp](https://github.com/gyroflow/gyroflow/files/13515965/2a345313-1968-4e10-96bc-c7e3ba79e963.dmp)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/13515966/gyroflow.log)

**Comment by AdrianEddy** [comment]
Try to use different "Preview pipeline" and/or "Device for video processing" (both are in Advanced on bottom right). Change these settings before loading the file

**Comment by Kirill-GRO** [comment]
I tried all the combinations. The program still closes...
![Снимок экрана (5)](https://github.com/gyroflow/gyroflow/assets/152504779/446257a1-5115-4699-874b-8c37c6d66da6)
![Снимок экрана (6)](https://github.com/gyroflow/gyroflow/assets/152504779/38149f64-e5f5-447f-8d53-b65842aa9492)
![Снимок экрана (7)](https://github.com/gyroflow/gyroflow/assets/152504779/3fd7d4cb-a2b2-4241-a02e-0ccae304d5bd)
[gyroflow.log](https://github.com/gyroflow/gyroflow/files/13516238/gyroflow.log)
[8220a71a-077f-48ad-8df8-990daaeb9ac6.dmp](https://github.com/gyroflow/gyroflow/files/13516244/8220a71a-077f-48ad-8df8-990daaeb9ac6.dmp)

**Comment by Kirill-GRO** [comment]
If I disable one of the video adapters, in the device manager. Then the program downloads the video file. And it begins to process it using the processor. 1.5 minutes of 1080/60fps video takes 4-5 hours to process :(
I'll try to install drivers for the video adapter from HP. They are old, from 2017. But with them, my video adapter is at least correctly displayed as M430, and not M330...
![Снимок экрана (8)](https://github.com/gyroflow/gyroflow/assets/152504779/57a80071-baba-41f2-b830-a2af2d9a88d1)
