### ISSUE TITLE
Video and audio out of sync after export

### ISSUE THREAD

**Issue by jonashogstrom** [gyroflow/gyroflow#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4 (also tested master)

### What operating system are you using?

Windows 10 22H2

### What GPU are you using?

Nvidia RTX A2000 8GB

### What happened?

I have a camera that produces video files where the first frame doesn't start at 0. In many cases, it starts close to zero, but it can be delayed up to ~800ms. This can be seen using ffprobe. The first videoframe can look like this: 
```
[FRAME]
media_type=video
key_frame=1
pts=2136
pts_time=0.854400
pkt_dts=2136
pkt_dts_time=0.854400
best_effort_timestamp=2136
best_effort_timestamp_time=0.854400
pkt_duration=100
pkt_duration_time=0.040000
/*...*/
[/FRAME]
```

Audio in this mp4-file starts at zero. VLC plays audio and video in sync and so does the gyroflow UI.

After export, the video is shifted 854 ms, but the audio retains its timestamps, so the effect is that audio and video is 854ms out of sync. 
Here is a short sample video. 

https://github.com/gyroflow/gyroflow/assets/1035652/cf7ec1b7-4446-4241-aa40-80aab225ec38

Here is the same video file after export (with audio and video out of sync)

https://github.com/gyroflow/gyroflow/assets/1035652/4252e60c-6f95-4554-b9c0-763e977eb5e4

I have looked at the code in `ffmpeg_video.rs` and in the method `receive_and_process_video_frames`, on [line 191](https://github.com/gyroflow/gyroflow/blob/master/src/rendering/ffmpeg_video.rs#L191), the timestamp for the videoframes are offset with the timestamp of the first VIDEO frame. The same is done for audio, but using the timestamp of the first AUDIO frame. So, if the audio and video was in sync in the original file, and the first audio and first video frame has different timestamps, the two streams will now be out of sync after export. 

I have tried to remove the modification of the video frame timestamp, and in my case it results in an exported video file where audio and video is in sync. In my use case I have previously had to adjust the IMU data timestamps to compensate for the offset of the video timestamps, but with this change I can keep the original timestamps of the IMU data. 

I realize that it is not ideal to have a video that doesn't have the first frame located at time 0, but most players appears to handle this without any major issues. I also realize that simply removing this compensation would probably impact the sync between IMU and video for most other use cases (that have the first video frame at a non-zero timestamp). 

An option would be to add a setting to the project file called "Preserve audio and video timestamps", and if this was set, the timestamps of the audio and video frames would simply not be modified during export.

**Comment by AdrianEddy** [comment]
Good catch, fixed in 32db02daf7c6247463f2d4eb1ce611d9aa4611c3
