### ISSUE TITLE
Command line will sometime flip gopro videos to be upside down

### ISSUE THREAD

**Issue by noobtoob4lyfe** [gyroflow/gyroflow#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

Gyroflow1_5_4

### What operating system are you using?

windows

### What GPU are you using?

nvidia 1080ti

### What happened?

when rendering the same gopro video in the GUI it looks fine, but the command line will flip it to be upside down.

### Relevant log output

```shell
n/a
```

**Comment by AdrianEddy** [comment]
Fixed in https://github.com/gyroflow/gyroflow/commit/ae9d42851bd770e1604ba2c76e5535eeb26ee248
Available in latest dev build https://gyroflow.xyz/devbuild/
