### ISSUE TITLE
Gyroflow App stop running while sincro 

### ISSUE THREAD

**Issue by CitosMad** [gyroflow/gyroflow#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

V 1.5.4

### What operating system are you using?

IOS 17.1.2

### What GPU are you using?

Apple A15 (iphone 13)

### What happened?

Hello everyone, I am trying to render a project with the app and while I am synchronizing the application it stops halfway through the process. Could someone tell me what the problem could be? (apple IOS 17.1.2 iphone 13 A15 chip)

**Comment by AdrianEddy** [comment]
Not enough RAM, try to lower the Processing resolution in Synchronization -> Advanced
