### ISSUE TITLE
Set settings profile as default or add window with presets

### ISSUE THREAD

**Issue by abramowv** [gyroflow/gyroflow#769]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I often stabilise gopro 8:7 videos twise, horizontal format and vertical. Please make settings preset automaticly applied when you open program or add window with presets with one click activation

**Comment by AdrianEddy** [comment]
It's already there, just add your preset to camera_presets folder and it will appear in the lens profile list. You can then make it favorite and it will stay on top
https://docs.gyroflow.xyz/app/advanced-usage/settings-presets

**Comment by abramowv** [comment]
<img width="311" alt="Screenshot 2023-12-13 at 18 28 49" src="https://github.com/gyroflow/gyroflow/assets/153727772/7bb1c074-b7f3-4846-be3f-1839f7cf0495">

**Comment by AdrianEddy** [comment]
Right, fixed in latest dev build https://gyroflow.xyz/devbuild/
