### ISSUE TITLE
Export problem, I used prores and h264/5, 

### ISSUE THREAD

**Issue by Stef2365** [gyroflow/gyroflow#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

Windows 10

### What GPU are you using?

Rtx3060 laptop

### What happened?

color layers shorter than brightness
![1](https://github.com/gyroflow/gyroflow/assets/154288161/8733e022-f98b-4bff-b8fb-c420bd9c41c7)

**Comment by AdrianEddy** [comment]
can you send me the original video file?

**Comment by AdrianEddy** [comment]
Please try latest dev build https://gyroflow.xyz/devbuild/

**Comment by AdrianEddy** [comment]
Any update?
