### ISSUE TITLE
Flow motion highlighted curve/white lines not showing

### ISSUE THREAD

**Issue by DpLorski** [gyroflow/gyroflow#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

v1.5.4

### What operating system are you using?

ventura 13.2.1

### What GPU are you using?

Intel UHD Graphics 617

### What happened?

After completing auto syncing there are no highlighted curves or white lines to represent the optical flow  data.
I only see the motion data from the gopro. When i tick the box in the sync menu "show optical flow" no difference. I try to tweak my motion data vs the image but thats pretty hard without the optical flow curve.
I recorded some Alexa. mini footage with a gopro on top to record motion datas.
I'd like to do some decent testing for an upcoming project but this feels to much like guessing.
please help.

**Comment by AdrianEddy** [comment]
There are small R P Y buttons next to timeline on the right which toggle the data

**Comment by DpLorski** [comment]
i tried those but they are for the motion data.
https://www.youtube.com/watch?v=QAds3x8UU1w
in the online gyroflow tutorial on youtube on around 23 minutes he just synced gopro motion data with another video source.
it now shows an extra white curve and highlighted motion curves at the sync points. 
Mine is not showing that so there is nothing to move/overlay to properly manually tweak.

**Comment by AdrianEddy** [comment]
That sounds like you have too small "Sync search size" and it's not picking any sync points. Read these:
https://docs.gyroflow.xyz/app/getting-started/basic-usage
https://docs.gyroflow.xyz/app/getting-started/basic-usage/timeline-and-gyro-chart
https://docs.gyroflow.xyz/app/getting-started/basic-usage/synchronization

**Comment by DpLorski** [comment]
Solved it. I initially installed Gyroflow through the Mac app store. This install didn't give me the light lines (optical flow sync)
 I removed the program and dowloaded the .DMG installer.
Now it works perfectly.
