### ISSUE TITLE
Stuck on Loading in Resolve

### ISSUE THREAD

**Issue by pkanddk** [gyroflow/gyroflow#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

Ventura 13.5

### What GPU are you using?

Mac Studio Apple M1 32 GB

### What happened?

When loading current file in resolve, Gyroflow gets stuck on 'loading'. If it helps, I'm trying to stabilize a Red Komodo file through Davinci Resolve. 
![Screenshot 2023-12-30 at 1 39 01 AM](https://github.com/gyroflow/gyroflow/assets/57553298/5a5e32fa-6017-4e69-a635-d13b7681afe1)

**Comment by AdrianEddy** [comment]
Did you install from App Store? When using the plugin, use the .dmg version. App Sandbox doesn't play well with the plugin
https://github.com/gyroflow/gyroflow/releases/download/v1.5.4/Gyroflow-mac-universal.dmg

**Comment by AdrianEddy** [comment]
Any update?
