### ISSUE TITLE
[Possible Bug]: Prores encoder using only 1 core on 12gen Intel.

### ISSUE THREAD

**Issue by leitmanr** [gyroflow/gyroflow#78]
### Gyroflow version

1.0

### What operating system are you using?

Windows 10 Pro 21H2 19044.1466

### What GPU are you using?

EVGA RTX 3080ti FTW3

### What happened?

When using the prores encoder, it only seems to be using one CPU core (i9-12900K) and therefore it takes almost 30 minutes to render 2 min of footage.
Not sure whether it is a limitation of the encoder or could be possibly improved.
![GF_prores_export_1core_only](https://user-images.githubusercontent.com/99039827/152638111-b245fc28-1511-4a05-a8c0-c9e25d2e657f.png)

**Comment by AdrianEddy** [comment]
Fixed in latest commit, you will be able to download binary from here when it finishes building: https://github.com/gyroflow/gyroflow/actions/runs/1799912667
