### ISSUE TITLE
Unable to render with GPU

### ISSUE THREAD

**Issue by heeken14** [gyroflow/gyroflow#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

Windows 10 Famille 22H2

### What GPU are you using?

Radeon RX580 Series

### What happened?

I've been using Gyroflow for a month, haven't encountered any problems and have always been able to export with the GPU, but I don't know why, I can't anymore. I tried uninstalling and reinstalling Gyroflow, I updated all my drivers. (My computer is only 2 years old) Thanks in advance !

### Relevant log output

```shell
https://we.tl/t-WRjteHacXe
```

**Comment by AdrianEddy** [comment]
Install latest driver from the AMD website: https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-23.11.1-win10-win11-nov3-vega-polaris.exe

The log you included indicates that you don't have latest driver installed
