### ISSUE TITLE
Parse accelerometer metadata from mp4 files recorded on Android

### ISSUE THREAD

**Issue by UnlimitedIllusionsSoftware** [gyroflow/gyroflow#793]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

If I understand correctly accelerometer metadata is needed to make "Horizon Lock" feature work.
Is that possible to add support for such kind of metadata similar with https://github.com/gyroflow/gyroflow/issues/753?
 (big-endian, "mett" box, application/gyro and application/accel mime type)

**Comment by AdrianEddy** [comment]
Can you share a sample file?

**Comment by UnlimitedIllusionsSoftware** [comment]
Sure, here it is
https://drive.google.com/file/d/1smWmTq_zUF5AE8Ut_keDiUKNhOGgFiZq/view?usp=sharing

**Comment by AdrianEddy** [comment]
That file seems corrupted, the `stbl` for the accel track is empty:
![image](https://github.com/gyroflow/gyroflow/assets/3849067/ce503a6d-8ad2-4611-b60b-ba3fc553eca1)

**Comment by UnlimitedIllusionsSoftware** [comment]
Could you please try this one:
https://drive.google.com/file/d/1L7GJsNqf8JX6wsYDCNfsx8qMNLYoUhSh/view?usp=sharing

**Comment by AdrianEddy** [comment]
this one is good. What's the unit of the accelerometer? `m/s²` or `g`?

**Comment by AdrianEddy** [comment]
Done in https://github.com/AdrianEddy/telemetry-parser/commit/3097e1b6c2750256f4c021e725cc822d58e5d1ea
Latest dev build: https://gyroflow.xyz/devbuild/
