### ISSUE TITLE
Missing IMU orientation / rotation in calibration page

### ISSUE THREAD

**Issue by StefanMeGit** [gyroflow/gyroflow#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

MacOS 

### What GPU are you using?

M1

### What happened?

It looks like there is no chance to calibrate a new lens with a naked blackmagic.

I tried to calibrate a new lens with my NAKED Blackmagic Pocket 6k. The Mainboard with Gyro and the Image Sensor is not in the same orientation as on the original camera. 

On the main page, there is an option called IMU ORIENTATION that works perfectly fine. When i choose an equivalent lens profile from he drop down list, i get very good results. When i try to calibrate a new lens, nothing works. You can clrealy see the axis shifting around in the wrong directions. Any change to implement this IMU orientation and rotation in the calibration page? I would love to create my own perfectly fitted lens profile with my lenses.

**Comment by AdrianEddy** [comment]
Gyro data is not needed for calibration, so the IMU orientation doesn't really matter. It won't stabilize your preview but it also won't affect the lens calibration

**Comment by StefanMeGit** [comment]
Oh i am Sorry. Misunderstood this. I ll give it another try. Thank you.
