### ISSUE TITLE
ask for https://github.com/AdrianEddy/rust-ffmpeg.git  when running 'cargo run'

### ISSUE THREAD

**Issue by huntkao** [gyroflow/gyroflow#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

master git

### What operating system are you using?

windows 10

### What GPU are you using?

no gpu

### What happened?

'cargo run' asks for https://github.com/AdrianEddy/rust-ffmpeg.git , but it is missing. please help thanks.

**Comment by AdrianEddy** [comment]
There's no such dependency on master, are you sure you're on the latest commit?
