### ISSUE TITLE
[Bug]: Not working with Runcam 5 orange 4K XV mode

### ISSUE THREAD

**Issue by BJY1991** [gyroflow/gyroflow#80]
### Gyroflow version

1.0-RC1

### What operating system are you using?

Windows 10

### What GPU are you using?

GeForce GTX 1070

### What happened?

Runcam 5 orange shot with 4K XV mode video resolution is 3840 x 2160. 
But when I choose camera preset with Runcam_5_Orange_4K_30FPS_XV_16by9_stretched Gyroflow will warning about video resolution is not match which should be 2880 x 2160. Also exported file is not useable.
It works with Gyroflow 0.3.0 Beta

**Comment by AdrianEddy** [comment]
Duplicate #71
