### ISSUE TITLE
Feature Request: Anamorphic Video Support in Gyroflow

### ISSUE THREAD

**Issue by egorovmp** [gyroflow/gyroflow#809]
Hello **Gyroflow Development Team,**

I hope this message finds you well. I am reaching out to suggest a potentially valuable feature addition to Gyroflow - support for anamorphic video footage. Anamorphic lenses are widely used in filmmaking for their ability to capture a wider field of view compared to traditional lenses, providing a unique aesthetic that is highly sought after for cinematic productions. However, one of the challenges with anamorphic footage is stabilizing it in post-production, due to the unique squeeze factor of the lens.

**Rationale:**

Broadening User Base: By supporting anamorphic video stabilization, Gyroflow could attract a wider audience, including professional cinematographers and filmmakers who frequently utilize anamorphic lenses for their work.
Enhanced Creative Options: Providing this feature would empower users to experiment more freely with anamorphic lenses, knowing they have a reliable tool for stabilization in post-production, thereby enhancing the creative options available to them.
Filling a Market Gap: Currently, there are limited options available that adequately address the stabilization of anamorphic footage without significant manual intervention. Implementing this feature could position Gyroflow as a leader in this niche area.

**Implementation Suggestions:**

**Squeeze Factor Input:** Implement a user input field for the anamorphic squeeze factor in the Gyroflow interface. This field would allow users to specify the squeeze factor of their lens, which could range from 1.33x to 2x, or even custom values.

**Aspect Ratio Correction Pre-stabilization:** Before applying the stabilization algorithm, temporarily adjust the video's aspect ratio according to the specified squeeze factor. This step would involve stretching the footage horizontally to correct the anamorphic squeeze, making it look like standard footage to the stabilization algorithm.

**Stabilization Process:** Apply Gyroflow's existing stabilization algorithm to the corrected footage. Given that the footage now has a standard aspect ratio, the stabilization should proceed as it does for non-anamorphic footage, ensuring accurate motion tracking and correction.

**Aspect Ratio Re-application Post-stabilization:** After stabilization, apply the inverse of the initial aspect ratio correction—this time, compressing the footage horizontally by the same squeeze factor to return it to its original anamorphic aspect ratio.

**Preview and Export Options:** Include preview options that allow users to view their footage both in its corrected (pre-squeeze) and final anamorphic forms. Furthermore, provides export settings that let users choose between exporting in the corrected standard aspect ratio or the original anamorphic format.

**Automatic Crop and Zoom Adjustments:** To accommodate the changes in framing that might occur from the stabilization process, implement auto-crop and zoom features that adjust the frame to ensure optimal composition while maintaining the anamorphic look.

I believe this feature would be a significant value addition to Gyroflow and greatly appreciated by the filmmaking community. I understand that feature implementation involves careful consideration, and I sincerely hope the team finds this suggestion to be both feasible and beneficial.

Thank you for considering this feature request. I am looking forward to any possibility of its implementation.

**Comment by AdrianEddy** [comment]
This is already supported, see `Input horizontal stretch` in lens calibrator 
https://docs.gyroflow.xyz/app/getting-started/lens-calibration#input-stretch
