### ISSUE TITLE
Is it possible for you to share materials to understand the stabilization correction algorithm?

### ISSUE THREAD

**Issue by Hiroaki-K4** [gyroflow/gyroflow#814]
Hi. Thank you for sharing a cool work.
I would like to understand the principle of stabilization. Is it possible for you to share materials or papers on the algorithms used?

**Comment by Hiroaki-K4** [comment]
I found answers on discord.

**Comment by vincentme** [comment]
> I found answers on discord.

Could you please give some hints on this? I am also interested and seems that the source code is hard to read...
