### ISSUE TITLE
Video blank if gyro data is imported but not if just the video is imported and not the gyro data

### ISSUE THREAD

**Issue by CrashDBN** [gyroflow/gyroflow#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4(gh1826)

### What operating system are you using?

Windows 11

### What GPU are you using?

AMD Radeon Vega 8

### What happened?

If I just import the video file from the Hawkeye Split 4k V4 I can see the video etc and its not blank if I then go and import the gyro data the video goes black
![GyroFlow with Gyro Data](https://github.com/gyroflow/gyroflow/assets/7872529/183dbf9f-5ec5-4a62-87bc-5c1cf6d8d3d8)
![GyroFlow without Gyro Data](https://github.com/gyroflow/gyroflow/assets/7872529/9746e248-3b17-4908-a28a-7cd191aa0b36)

**Comment by AdrianEddy** [comment]
go to Advanced on bottom right and "Reset all settings to defaults"

**Comment by CrashDBN** [comment]
Hi there.Thried that removed the app and reinstalled same thing Get Outlook for Android

**Comment by AdrianEddy** [comment]
show me a screenshot of the "Stabilization" section opened

**Comment by CrashDBN** [comment]
![Untitled](https://github.com/gyroflow/gyroflow/assets/7872529/0123fc09-dc4b-4218-8dfc-749288993101)

**Comment by CrashDBN** [comment]
Hi there

I came across this issue it is sorta related to my issue and that is why I am using the dev version of gyroflow but it said it was resolved. So not sure if its got anything to do with it.

https://github.com/gyroflow/gyroflow/issues/559

**Comment by AdrianEddy** [comment]
1. Install latest GPU driver (I think it may be this one https://dl.dell.com/FOLDER07839672M/1/AMD-Radeon-Graphics-Driver_251TV_WIN64_30.0.13020.4_A01.EXE )
2. If that doesn't help, send me gyroflow.log file (it's next to Gyroflow.exe)

**Comment by CrashDBN** [comment]
![image](https://github.com/gyroflow/gyroflow/assets/7872529/e668442b-ed0e-4d7f-b4c9-ddebe2c68e32)
