### ISSUE TITLE
Improve "Browse" feature

### ISSUE THREAD

**Issue by nogod4me** [gyroflow/gyroflow#820]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hello everyone!
It would be nice if browse option (three dots in the bottom of app) asks only for default folder for exported files and save it after exit app. 
<img width="925" alt="Снимок экрана 2024-04-22 в 10 03 44" src="https://github.com/gyroflow/gyroflow/assets/99600621/d696925b-b20b-4c23-9f60-28f92ce32609">

Now (in macOS) it asks for the file name and at the same time does not offer a default file name, so I have to enter it manually. This breaks file organization, I would like to use the default camera filename. 
<img width="807" alt="Снимок экрана 2024-04-22 в 10 21 32" src="https://github.com/gyroflow/gyroflow/assets/99600621/378f0e90-885a-4e7b-9f88-e3a98b941f36">

**Comment by AdrianEddy** [comment]
It's already fixed in the dev build https://gyroflow.xyz/devbuild/
