### ISSUE TITLE
Full Sony metadata support

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#825]
In order: 
- [x] #44
- [x] #727 
- [ ] OIS data (tag [0xe416](https://github.com/AdrianEddy/telemetry-parser/blob/master/src/sony/rtmd_tags.rs#L450)) I think this means adding this data to cx and cy of the camera intrinsic matrix, but I could be wrong
- [ ] EIS data ([already figured out](https://github.com/gyroflow/gyroflow/files/15135551/mesh_correction_reverse.zip), just needs to be ported to the gpu kernel)

**Comment by Subh231004** [comment]
Attempt #825

**Comment by AdrianEddy** [comment]
This is now mostly done. Majority of the work was done by @VladimirP1 and me (EIS), with reverse-engineering help from @digital-phoenix.

If you're curious what this task required, it's essentially [sony.rs](https://github.com/gyroflow/gyroflow/blob/master/src/core/gyro_source/sony.rs) + changes in [frame_transform.rs](https://github.com/gyroflow/gyroflow/blob/master/src/core/stabilization/frame_transform.rs#L245-L263) + changes in kernels eg. in opencl_undistort.cl [ibis/ois](https://github.com/gyroflow/gyroflow/blob/master/src/core/gpu/opencl_undistort.cl#L302-L332) and [eis](https://github.com/gyroflow/gyroflow/blob/master/src/core/gpu/opencl_undistort.cl#L170-L228)

The amount of work required to get this done was insane so please pay huge respect to @VladimirP1, he figured out all the needed math for this, and @digital-phoenix did a lot of reverse-enginnering with Frida scripts required to dump data from Catalyst and compare logic and functions. 

There are still some bugs in some files, but majority of the videos already work properly. For the remaining issues see #849 

/tip $1000 @digital-phoenix

**Comment by rgaufman** [comment]
Are there any instructions how to use this? Or is it just automatic in the latest version from git?

**Comment by AdrianEddy** [comment]
automatic https://gyroflow.xyz/devbuild/

**Comment by danielkelNL** [comment]
Thank you for all the time and effort! Does it also work in combination with Active Stabilization mode. The Sony A7IV does have this mode.

**Comment by AdrianEddy** [comment]
Yes

**Comment by Hevinxue** [comment]
> automatic https://gyroflow.xyz/devbuild/

Tried the beta and:
"0xc00000142" error on 2 of my 3 windows platforms, win11(23H2) and win10(22H2).

**Comment by AdrianEddy** [comment]
@Hevinxue Install VC Redist https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by cesccc** [comment]
Is the bounty still on? @AdrianEddy

**Comment by cyfdecyf** [comment]
> Yes, try it

I'm really excited when I see this message. I've tried the dev build with some videos shoot on Sony A7 IV with PZ 16-35 lens at various focal lengths (with IBIS turned on), all works very well automatically like magic. The stablization even works for videos that has zooming.

Thanks for the great work!

**Comment by rgaufman** [comment]
Total game changer this and so much faster and better than Sony's Catalyst!
