### ISSUE TITLE
BRAW crashing when loading new file after successfully loaded another one

### ISSUE THREAD

**Issue by pkarc** [gyroflow/gyroflow#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4 (gh1869)

### What operating system are you using?

Windows 11

### What GPU are you using?

NVIDIA GeForce GTX 1650 Ti

### What happened?

I'm exporting project process data directly from the UI using BRAW file, the program crash when loading a BRAW file after successfully loading and exporting proccess data of the 1st successfully loaded file, it happens randomly sometimes the 2nd, 3rd, 4th, etc...

### Relevant log output

```shell
attached file
```

[gyroflow.log](https://github.com/gyroflow/gyroflow/files/15195026/gyroflow.log)

**Comment by AdrianEddy** [comment]
Should be fixed in latest dev build https://gyroflow.xyz/devbuild/

**Comment by alexrjohnston** [comment]
This is now happening to me for some reason - 1.6.1 M1 mac pro

first file - loads fine, second file gyroflow freezes. Looks like the fix was added in 1.6.0, what am I missing?
