### ISSUE TITLE
Wrong "dynamic zooming" russian translation

### ISSUE THREAD

**Issue by lukegluke** [gyroflow/gyroflow#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

Any

### What happened?

Dear @AdrianEddy, quite time ago on crowdin we fixed wrong copypaste russian translation for "Dynamic zoom" mode and  you approved the correct one (Динамический зум = Dynamic zoom): https://crowdin.com/editor/gyroflow/7/en-ru?view=comfortable#2633

But in 1.5.4 application there is still this issue with wrong translation:
![изображение](https://github.com/gyroflow/gyroflow/assets/3624285/4fcf0ece-c794-4f9a-9e63-ed912ae0523e)
(=No zoom, No zoom, Static zoom instead of No zoom, Dynamic zoom, Static zoom)

**Comment by AdrianEddy** [comment]
Yes because there was no official update since 1.5.4. use the dev build https://gyroflow.xyz/devbuild

**Comment by lukegluke** [comment]
Dear @AdrianEddy,

Found another small issue with Russian translation for "Output size" in Export. The translation itself is right, but it is too long so input fields of resolution don't show whole number (on default width of side panel):
![Image](https://github.com/user-attachments/assets/74e34480-3b32-43d1-ad41-a90c0606fb40)

I've added a short version "Разрешение" = "Resolution", could you please apply it
https://crowdin.com/editor/gyroflow/7/en-ru?view=comfortable#1313

And also there could  be a reason to set/increase minimal width for these and maybe other input fields so no translation on any language will break them again.

**Comment by AdrianEddy** [comment]
updated in latest dev build
