### ISSUE TITLE
Hi all,
 Recently I build source code following the build flow from the official website and it works nice.
The problem is, When I debug in VS Code and set breakpoint at the entrance of function  qrhi_undistort::render(), which is inside init_player (), it shows that variables such as _fram and timestamp_ms  are not successive. for example, currently _fram’value is 56, but after I run step one more, it'value jump to 60 rather than  57.  
 What's cause to it? 
Thanks very much. 
 

### ISSUE THREAD

**Issue by Ming-chwan** [gyroflow/gyroflow#841]
Hi all, Recently I build source code following the build flow from the official website and it works nice. The problem is, When I debug in VS Code and set breakpoint at the entrance of function qrhi_undistort::render(), which is inside init_player (), it shows that variables such as _fram and timestamp_ms are not successive. for example, currently _fram’value is 56, but after I run step one more, it'value jump to 60 rather than 57. What's cause to it? Thanks very much.

**Comment by AdrianEddy** [comment]
Did you try to add debug log instead of doing breakpoints? The video decoding happens in a different thread and it's possible it just skips to next frame while you're waiting on this variable breakpoint
