### ISSUE TITLE
moving keyframes in time, please

### ISSUE THREAD

**Issue by Ji-flyby** [gyroflow/gyroflow#842]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

1.) wonderful app that let me do exciting shots ! thank you
2.) missing possibility to move keyframe on the timeline (maybe with option key down?),
because: sometimes scaling/framing has to be done/keyframed on an specific image,
but the actual parameter change should be performed earlier so that the (cam)movement is not that visible etc.....
thank you !

**Comment by AdrianEddy** [comment]
Done in 3d306320bc4c5606e8a8cb1669e46863f47c47f1. Check out the dev build https://gyroflow.xyz/devbuild/

**Comment by Ji-flyby** [comment]
you have won the cup for quick solution ! thank you
I have never received a coded response so quickly,
will need longer even to evaluate !
thank you very much !
