### ISSUE TITLE
slider resolutions - modifier key for more precise adjustments

### ISSUE THREAD

**Issue by Ji-flyby** [gyroflow/gyroflow#843]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

keyframe moving works great ! thank you very much !!

playing around I encountered that there is another wish:
could we also have a modifier-key (also Alt ?) when manipulating sliders to temporary get 5x or 10x resolution
so it is easier to make more subtile adjustments ?
I'm using FOV and the additional 3D-rotations a lot.

**Comment by AdrianEddy** [comment]
Added in latest dev build https://gyroflow.xyz/devbuild/
