### ISSUE TITLE
Gridlines reference in preview window

### ISSUE THREAD

**Issue by malinhiles** [gyroflow/gyroflow#846]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

When adjusting horizon leveling lock amount, roll angle correction, lens correction amount, and other features, it would be helpful to enable a set of gridlines for reference. This feature is common in photo and video editing suites.

I imagine its implementation would look something like this: 
![gridlines button](https://github.com/gyroflow/gyroflow/assets/93371446/c2a25f8c-cfde-4210-a213-3bb559e92725)
When toggled, a set of reference lines are overlaid on the preview window. I anticipate there would be a couple modes of overlay lines that could be helpful for gyroflow:

-Dense Grid: for adjusting horizon lock amount, roll angle correction, lens correction amount, etc.
-Rule of Thirds: for composition when adjusting stabilization and zoom amounts

This function is in Darktable, a popular, open source, photo editing platform. 
A left click on this icon enables the grid, and right click on this icon opens the options panel for the gridlines.
You can change the grid type, change characteristics of the grid, and change the opacity of the grid:
![darktable gridlines button](https://github.com/gyroflow/gyroflow/assets/93371446/5443890c-341d-4f2a-b04d-4156a5f7dd64)
![darktable gridlines options](https://github.com/gyroflow/gyroflow/assets/93371446/f97ceaa1-8a58-4af5-9e26-7c5329c23155)

**Comment by AdrianEddy** [comment]
There's a grid already, you can right click on the video area and toggle it, or use the G shortcut
Ctrl+G to toggle black/white

for horizon roll adjustments, there are E and R keys with modifiers, see here: https://github.com/gyroflow/gyroflow/blob/master/src/ui/Shortcuts.qml#L280-L287
