### ISSUE TITLE
Semi-blind OIS-aware stabilization

### ISSUE THREAD

**Issue by matt-from-wii-sports-2** [gyroflow/gyroflow#851]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Somewhat related to #825, but that one requires existing IBIS metadata (non-blind).

GyroFlow requires disabling the OIS/IBIS, but that makes the unprocessed footage shakier. This means that the FOV of the GyroFlow-processed videos will be narrower that it could have been, the resolution will decrease more than it could have, and most importantly there will be small motion blur present after the stabilization that the OIS could have physically removed.

How about implementing a semi-blind OIS-aware mode, when the user takes 2 videos of a calibration target while shaking and moving the camera, first with OIS/IBIS disabled and then enabled? GyroFlow could then estimate how effective the OIS is and use the data to correctly stabilize the footage with OIS enabled. Of course this won't be perfect since the motion in the 2 videos will likely be different but it hopefully would be better than nothing at all.

**Comment by AdrianEddy** [comment]
What camera are you talking about? I don't think what you described has any chance of working at all, I don't see how it would. the internal OIS/IBIS is different for every frame so there's no way to "calibrate" for that

**Comment by AdrianEddy** [comment]
It won't be sufficient, there's no way to correlate the movement this way. 
The only way is for the camera to record how the OIS element was moved, which Sony does, and that is now supported.

For your use case, it will be #45 once it's done properly

**Comment by AdrianEddy** [comment]
of course, OIS does only small corrections, while gyro does the main one, so you should always have gyro if possible. Optical flow will never be perfect
