### ISSUE TITLE
Gyroflow terribly slow on iMac 5K Retina with AMD Radeon Pro

### ISSUE THREAD

**Issue by Giammi** [gyroflow/gyroflow#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

macOS Ventura 13.6.7

### What GPU are you using?

Radeon Pro 580 8Gb

### What happened?

I tried several export settings, but there’s no way I can go faster than 0.2-0.3 fps. Exporting a couple of minutes clip results in hours of rendering.

Specifically I’m trying to export a GoPro 11 footage in H265, 5312x4648. Using CPU gives slightly better results (0.5 fps). GPU is absolutely unusable. It works, but as written above is too slow.

<img width="273" alt="Screenshot 2024-06-29 alle 21 53 32" src="https://github.com/gyroflow/gyroflow/assets/66137675/44814942-17fe-4b58-b776-8022be4e0a49">

<img width="281" alt="Screenshot 2024-06-29 alle 21 53 37" src="https://github.com/gyroflow/gyroflow/assets/66137675/cdb982c5-629e-4470-bcfc-d150b46f5e65">

<img width="265" alt="Screenshot 2024-06-29 alle 21 55 02" src="https://github.com/gyroflow/gyroflow/assets/66137675/64bb7eaa-ba42-478e-8d7e-7796f20fe783">

<img width="329" alt="Screenshot 2024-06-29 alle 21 54 08" src="https://github.com/gyroflow/gyroflow/assets/66137675/06fbe7dd-c55f-4a27-bb57-b2feb28cf4b9">

**Comment by AdrianEddy** [comment]
did you try the dev build? https://gyroflow.xyz/devbuild/

**Comment by Giammi** [comment]
> did you try the dev build? https://gyroflow.xyz/devbuild/

Tested it right now and no improvements. Same slowness.

**Comment by AdrianEddy** [comment]
try different "Device for video processing"
also, send gyroflow.log file, it's in "Show package contents" -> Contents -> MacOS

**Comment by Giammi** [comment]
> try different "Device for video processing" also, send gyroflow.log file, it's in "Show package contents" -> Contents -> MacOS

Ok, so: originally I was using "OpenCL Apple AMD Radeon Pro". Very slow (0.2 fps), but works. I tried "WGPU AMD Radeon Pro Metal" and the whole iMac got stuck. After a while (I'd say a good 3 minutes), without clicking anything, the rendering started but with 0.0 fps. I hence aborted the process.

Going back to OpenCL, works again, slow as usual.

Oh, one thing that maybe is important to mention. When I select GPU, I get prompted that the Pixel format is not supported by GPU.

<img width="508" alt="Screenshot 2024-06-29 alle 22 57 04" src="https://github.com/gyroflow/gyroflow/assets/66137675/a2938185-8bc5-4e28-9d5a-117188a7abc7">

If I select YUV420P (that's the original one), I get this error:

<img width="571" alt="Screenshot 2024-06-29 alle 22 55 52" src="https://github.com/gyroflow/gyroflow/assets/66137675/f128b64b-8324-42bc-94cf-23fcd467f0c4">

With NV12 or P010LE it works, but slow as described above.

Nevertheless, here's the log:
[gyroflow.log](https://github.com/user-attachments/files/16042185/gyroflow.log)

**Comment by AdrianEddy** [comment]
That GPU doesn't support 10-bit encoding, so I'm afraid your only option is encoding on CPU (or recording 8-bit in gopro)
There's nothing I can do about it

**Comment by Giammi** [comment]
> try different "Device for video processing"
> 
> also, send gyroflow.log file, it's in "Show package contents" -> Contents -> MacOS

Oh, I see. At least I know what is the reason. Thanks a lot for your time!
