### ISSUE TITLE
About "additional_rotation"

### ISSUE THREAD

**Issue by laocan** [gyroflow/gyroflow#856]
https://github.com/gyroflow/gyroflow/blob/428f051905d2e61202dbc14a8c5c51d8223d3028/src/core/stabilization/frame_transform.rs#L230

What does "additional_rotation" mean here?
Why is it needed?
How to measure it?
thx.

**Comment by AdrianEddy** [comment]
it's set by the user, it's useful for example to frame 9:16 video from 16:9 source
![image](https://github.com/gyroflow/gyroflow/assets/3849067/c026c839-4b14-4a3f-bee6-339f7e3dfdc3)
it's optional
