### ISSUE TITLE
Which reference should be used?

### ISSUE THREAD

**Issue by rongjx3** [gyroflow/gyroflow#860]
Hello!
I think your work is very valuable. If I want to discuss your work or make comparisons in my paper, which reference would be most appropriate?

**Comment by AdrianEddy** [comment]
what do you mean by reference? I think you should just use the link to the repository if I understand correctly

**Comment by rongjx3** [comment]
I apologize for not expressing my problem clearly.
I am referring to the references section at the end of an academic paper, which typically lists other cited works, usually papers or books. So I would like to know which paper or book your work is primarily based on?

**Comment by rongjx3** [comment]
I see. Thanks for your help!
