### ISSUE TITLE
Incomplete Output of Video Frame Correction Information

### ISSUE THREAD

**Issue by laocan** [gyroflow/gyroflow#864]
I tried to print and write out the correction information for each frame, but I found that: 
if the video stream is played directly, more than half of the intermediate video frames do not print or write output data; 
if played frame by frame, 10% of the frames still have no data output. 
The code I added is after this line:
https://github.com/gyroflow/gyroflow/blob/6ba6c322fc1426c47f8429d760a303b6914625a9/src/core/stabilization/frame_transform.rs#L237

**Comment by laocan** [comment]
From frame 617 to frame 779, the frames with the sequence numbers shown below have no output information.
![aaa](https://github.com/user-attachments/assets/df0f3a5d-a50f-4915-8ed5-918508a22f4c)

**Comment by laocan** [comment]
Thx!
Can you briefly describe how to render all video frames, after synchronizing and stabilizing a shaky video in the player. So that 
 I can dump all~

**Comment by AdrianEddy** [comment]
hmm, not sure what you mean, just click Export?

**Comment by laocan** [comment]
> This is expected, not all frames are rendered for playback because of multiple factors, eg frame processing time, audio sync and caching. If you want to dump all, you have to render the video, instead of doing it in playback

Thx!
Can you briefly describe how to render all video frames, after synchronizing and stabilizing a shaky video in the player. So that
I can dump all~

**Comment by laocan** [comment]
My goal is to print out the final correction information for all frames, but currently, some frames are being skipped. Will I be able to obtain the correction information for all frames after rendering all of them?

**Comment by AdrianEddy** [comment]
yes, rendering processes all frames. What do you need this for? Camera data can be exported simply using the Motion Data->Export option in the UI

**Comment by laocan** [comment]
I have written my own rolling shutter correction method and want to verify its feasibility. Therefore, I need Gyroflow to obtain the correction quaternions for every line of each frame image. However, I am currently unable to get the correction quaternions for all frames because some frames are being skipped.

**Comment by AdrianEddy** [comment]
ok then just render the video from gyroflow and dump then, it processes all frames. Note that it processes the 3 video planes per frame (Y, U and V) so you need to use just the first one per frame (Y channel)
