### ISSUE TITLE
crash when open any video files

### ISSUE THREAD

**Issue by huntkao** [gyroflow/gyroflow#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

master code

### What operating system are you using?

windows 10

### What GPU are you using?

nvidia geforce mx550

### What happened?

Crash when open any test videos.

[gyroflow.log](https://github.com/user-attachments/files/16302540/gyroflow.log)

**Comment by AdrianEddy** [comment]
Install latest drivers for your integrated Intel card, from intel.com and also make sure you have latest driver from  nvidia.com. the point is, install latest drivers for **both** GPUs

**Comment by huntkao** [comment]
Does CUDA version matter?

Thank you so much.

**Comment by AdrianEddy** [comment]
no, but I'm pretty sure the crash is related to your integrated Intel card, not NVIDIA one

**Comment by huntkao** [comment]
oh... Thanks. I will check it out.

**Comment by huntkao** [comment]
Both drivers for integrated Intel card and NVIDIA card are updated. But the fresh-built gyroflow still crashs. 
The new log file u
[gyroflow.log](https://github.com/user-attachments/files/16309855/gyroflow.log)
ploaded.

**Comment by AdrianEddy** [comment]
does the build from https://gyroflow.xyz/devbuild/ work?

**Comment by huntkao** [comment]
yes. devbuild works.

**Comment by AdrianEddy** [comment]
ok then try to rebuild everything again:
1. delete the `ext` folder
2. update rust: `rustup update`
3. install deps: `just install-deps`
4. compile and run: `just run`

**Comment by huntkao** [comment]
I followed your steps. 
At the first time running, It hangs when I clicked the "dont load .gyroflow file" dialog. (no crash)
But at the later runs, it crashes immediately every time when that dialog box appears.

[gyroflow.log](https://github.com/user-attachments/files/16310799/gyroflow.log)

**Comment by huntkao** [comment]
I followed your steps. 
Also I found that there was system-level Qt confliction problem.
It works awesome after I fixed all the things. 
Thanks a lot!
