### ISSUE TITLE
Additional 3D rotation doesn't work properly with Horizon lock

### ISSUE THREAD

**Issue by Ji-flyby** [gyroflow/gyroflow#871]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

sometimes I wished I could simply shift the visible frame within the bigger stabilized/lenscorrected image legft/right or up/down.
using 3D pitch works great to look 'deeper', but 'yaw' allways also needs some "roll" to keep the horizont horizontal (with 'lock horizont' enabled).
maybe shift-sliders applied after the 3D section would make sense.
thank you for the great app !

**Comment by AdrianEddy** [comment]
Fixed in 67a9a6a, use the dev build https://gyroflow.xyz/devbuild/
