### ISSUE TITLE
GPU-Encoding Bitrate does not match on Apple M1 Pro

### ISSUE THREAD

**Issue by prafgup** [gyroflow/gyroflow#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

v1.5.4

### What operating system are you using?

mcOs Sonoma 14.5 (23F79)

### What happened?

I have a similar issue with my Apple M1 Pro as #472 , if I disable GPU encoding it works fine and respects my Bitrate that I have set, but gives out a random Bitrate in case its enabled, I have tried setting the `-rc cqp` custom encoder as well as suggested in the comments.

![image](https://github.com/user-attachments/assets/645b7ca3-493a-4a3f-aa89-2910a4704f69)

With GPU - 
<img width="342" alt="image" src="https://github.com/user-attachments/assets/67c78235-e9af-4f5d-9f9b-33b5b6d696a6">

With CPU - 
<img width="344" alt="image" src="https://github.com/user-attachments/assets/ce4bd56b-1813-4679-a911-0cb1e460e066">

**Comment by AdrianEddy** [comment]
That was already fixed in the dev build https://gyroflow.xyz/devbuild

**Comment by prafgup** [comment]
Thanks for the update @AdrianEddy 

Seems like the last release https://github.com/gyroflow/gyroflow/releases/tag/v1.5.4 is from `Nov 1, 2023` thats around 10 months old. A new release soon might help others as well :)

**Comment by AdrianEddy** [comment]
I'm working on getting 1.6.0 done, but there's still some work to do before release
