### ISSUE TITLE
crash on file open. Insta360 ace pro 

### ISSUE THREAD

**Issue by AndriiShramko** [gyroflow/gyroflow#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

the last one and previous

### What operating system are you using?

Windows 10 Pro 22h2

### What GPU are you using?

rtx 3070 and 4090

### What happened?

https://drive.google.com/drive/folders/1J0bvuauoN51C1HGo3CZsrka7qm7hRB0S?usp=sharing   crash on file open

**Comment by AdrianEddy** [comment]
That was already fixed in the dev build https://gyroflow.xyz/devbuild/

always check the dev build before filing any bugs, most of them are already resolved
