### ISSUE TITLE
Nightly build fails to start on windows. (0xc0000142)

### ISSUE THREAD

**Issue by MingchenZhang** [gyroflow/gyroflow#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

758dcfe8c264d3d056135bca2851800f46a3d6e2

### What operating system are you using?

Windows 10

### What GPU are you using?

RTX 2070 super

### What happened?

The program can't start at all, with following error message:
The application was unable to start correctly (0xc0000142).
There is no log in the console.

**Comment by AdrianEddy** [comment]
Install VC redist https://aka.ms/vs/17/release/vc_redist.x64.exe
