### ISSUE TITLE
Export to mkv

### ISSUE THREAD

**Issue by d123456temp** [gyroflow/gyroflow#889]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Mp4 container is prone to destruction - head/tail missing renders it useless and beyond recovery. Mkv on the other hand requires header only - this will have two advantages:
1) In case of GF/system error the work already rendered won't be lost (I lost c.a. 20 hours of rendering on my laptop in last 20 weeks - lot's of energy and time)
2) It will allow to watch partially rendered content and spot mistakes earlier.

These two points are crucial for non-GPU setups like laptops. Rendering of a 3 min clip from avata 2 takes 15 hours. With mp4 loosing it is really painful.  Of course MKV can/should be an option in case somebody wants to stick to the subpar mp4...

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/
