### ISSUE TITLE
[Bug]: Longer videos show no gyro traces until I zoom in

### ISSUE THREAD

**Issue by b14ckyy** [gyroflow/gyroflow#89]
### Gyroflow version

1.0.0-rc1

### What operating system are you using?

Windows 11 - 22000.438

### What GPU are you using?

Core i7 7700K + GTX 1080ti

### What happened?

![image](https://user-images.githubusercontent.com/33039058/152656462-584e6437-cd7d-468c-aa58-cfe4f307308b.png)
![image](https://user-images.githubusercontent.com/33039058/152656477-70e6a0f1-b0f2-49f8-9ee2-c7968f59752b.png)

As seen in the pictures, it seems like if more than 20min of video is shown in the timeline, the Gyro traces disappear. Not sure if I have merged the original files back then or if the SMO 4K has no file size limit but this can be confusing. 

I guess sample file is not needed? If you need one I will upload the 21GB video :D

**Comment by AdrianEddy** [comment]
Could you use `gyro2bb` and upload just the csv with the gyro data? https://github.com/AdrianEddy/telemetry-parser/releases

**Comment by b14ckyy** [comment]
@AdrianEddy here you go: 
[PRO_VID_20210614_170412_00_002.mp4.zip](https://github.com/gyroflow/gyroflow/files/8010301/PRO_VID_20210614_170412_00_002.mp4.zip)

**Comment by AdrianEddy** [comment]
Fixed in 8319d87742194dcfe17341d914ebfe6ec186706e
