### ISSUE TITLE
Manage render queue order/priority

### ISSUE THREAD

**Issue by d123456temp** [gyroflow/gyroflow#890]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

On systems without GPU, when single 3m file renders for 15 hours it would be great to have a possibility to move some jobs up/down the priority queue as new clips are filmed some time later. Now it only works in FIFO mode ("render now" bogs the system and really is not that efficient if you still want to use to laptop for other purposes).
This could be achieved in two ways: by adding priorities 1-10 or 1-99 to files, or allowing to move the job up/down the queue. The latter would be more user friendly/obvious.

**Comment by AdrianEddy** [comment]
Done in efaa1c08fb9f9e4e944797990643152c5b9ce111
Available in latest dev build https://gyroflow.xyz/devbuild/
Use Ctrl+drag the item, or right click and use the context menu
