### ISSUE TITLE
Add more dependencies

### ISSUE THREAD

**Issue by javierckr** [gyroflow/gyroflow#892]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I'm using it on Gentoo and it's missing some dependencies, it depends on wayland: `./gyroflow: error while loading shared libraries: libwayland-client.so.0`
and it depends on mit-krb5: `./gyroflow: error while loading shared libraries: libgssapi_krb5.so.2`

**Comment by AdrianEddy** [comment]
I can't add these dependencies, because that's the responsibility of your system, not the app. Every linux distro is different and you have to take care of the dependencies for your case
