### ISSUE TITLE
`smoothness` vs `max smoothness` vs `max smoothness at high velocity`

### ISSUE THREAD

**Issue by scr255** [gyroflow/gyroflow#896]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Hi, I looked at the documentation but couldn't find the difference between `smoothness`, `max smoothness`, and `max smoothness at high velocity`. I noticed that the latter two have values in seconds, so now I'm also unsure about what seemed like an easy-to-understand setting: `zooming speed`.

I experimented with all the parameters and observed a stronger crop when moving the slider to the right on all of them, but that's about it. If I can get a solid understanding, I'll help update the official documentation, thanks!

**Comment by AdrianEddy** [comment]
The algorithm is roughly outlined here https://github.com/gyroflow/gyroflow/blob/master/src/core/smoothing/default_algo.rs#L4-L13

also on Discord [here](https://discord.com/channels/797044698682228736/797044698682228741/1140594141156364329) and [here](https://discord.com/channels/797044698682228736/797044698682228741/1231949638907465829) and [here](https://discord.com/channels/797044698682228736/797045396425408522/1057448680644423681)

zooming speed determines the time window in which the zooming can happen to cover the needed area

**Comment by AdrianEddy** [comment]
The main smoothness slider is the threshold, it's defined at 500deg/s when the smoothness slider is 100% so at 50% it's 250deg/s
