### ISSUE TITLE
Decouple Video Export Functionality from App and Integrate into Core Module

### ISSUE THREAD

**Issue by heiha100** [gyroflow/gyroflow#898]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

The video export code seems to be closely tied to the app. Are there any plans to separate this part or integrate it into the core?

**Comment by AdrianEddy** [comment]
No, this is by design. Read why here https://docs.gyroflow.xyz/app/technical-details/gyroflow-core
