### ISSUE TITLE
RED Komodo-X on OSX not always asking for import of folder option after file import

### ISSUE THREAD

**Issue by Fuwubuman** [gyroflow/gyroflow#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.5.4

### What operating system are you using?

Sequoia 15 (but also previous versions)

### What GPU are you using?

OSX

### What happened?

The program sometimes asks if i want to use the whole folder in stead of a single file after dragging a RED file or by pressing "open file" Sometimes a bleu box pops up in the left top corner to select the whole folder. This however most of the times doesn't work and than randomly works again after closing down the program and even restarting the macbook. 
![Screenshot 2024-09-30 at 14 34 15](https://github.com/user-attachments/assets/980e3e06-6ad0-4fa4-a69f-df8f277c28e6)

**Comment by AdrianEddy** [comment]
It's already fixed in the dev build https://gyroflow.xyz/devbuild

**Comment by Fuwubuman** [comment]
Hi Adrian, thnx for the link and your reply, i didn't know it was already fixed but i'm happy this will be fixt in the next release. Any idea when the next release will be out? As i don't have testflight experience i seem to not be able to download the latest dev version of gyroflow. Thanks!

**Comment by AdrianEddy** [comment]
you don't need testflight, just download the .dmg from that link, click on "Gyroflow app"

Next version will be out in a few weeks

**Comment by Fuwubuman** [comment]
Thnx! Got it :)
