### ISSUE TITLE
merge gcsv fail, gyroflow v1.54 and dev 1.54(gh2148)

### ISSUE THREAD

**Issue by robin-debug** [gyroflow/gyroflow#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

v1.54 and dev 1.54(gh2148)

### What operating system are you using?

Windows 11

### What happened?

merge 3 gcsv file into one,the joined file has bad time length,maybe bad time index.
[gyroflow.log](https://github.com/user-attachments/files/17269131/gyroflow.log)
[gcsv.zip](https://github.com/user-attachments/files/17269133/gcsv.zip)
![屏幕截图 2024-10-06 194021](https://github.com/user-attachments/assets/7e622a49-0048-4569-b77b-5e5c5e550094)

**Comment by robin-debug** [comment]
I guess the bug in src/controller.rs line 2172,in function merge_gcsv
![屏幕截图 2024-10-06 203657](https://github.com/user-attachments/assets/535ce9a9-d14e-4d25-9237-83e7446f272b)
the 1st gcsv have 11947 timestamps,and the 2nd have 11951,
when run in 2nd file,work with 11948 timestamp,
base on code 2172,the add_timestamp reset to 0
then all left timestamp is bad
![屏幕截图 2024-10-06 203622](https://github.com/user-attachments/assets/e7f327b9-e621-49fe-bc8a-b0dce3db67a3)
and because 3th gcsv have more timestamp(11967) then 2nd(11951),same bug again
![屏幕截图 2024-10-06 204544](https://github.com/user-attachments/assets/febc8854-90d1-4247-b3a0-3c2db9414462)

**Comment by AdrianEddy** [comment]
Fixed in 8a989f7be0aa29cf839f0085e250cd413bb0462d
