### ISSUE TITLE
Allow customizing output file suffix in CLI

### ISSUE THREAD

**Issue by jameslin123** [gyroflow/gyroflow#903]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I would like to use CLI to batch process videos into different bitrates. For example, given "myVideo.mp4", I would like to run the CLI multiple times, each time supplying different bitrate info via presets, and eventually generate these outputs:

myVideo_stabilized_12Mbps.mp4   (Provide bitrate and suffix overrides via CLI arguments)
myVideo_stabilized.mp4  (The default option, no bitrate and no suffix override)

However, it seems that the default suffix is loaded from settings.json, and there's currently no way to customize it via CLI, so we can't use something like "_stabilized_12Mbps" as a suffix.

It would be helpful to support suffix customization. Thank you!

**Comment by AdrianEddy** [comment]
Done in 159647bdbf3320f5926f9fbb1bc0a23c6cf1cd4f https://gyroflow.xyz/devbuild/
