### ISSUE TITLE
Use mouse scroll wheel to increment number input fields

### ISSUE THREAD

**Issue by hilmiyafia** [gyroflow/gyroflow#904]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Right now you have to type in the numbers, this is really hard to fine tune the parameters like the rotation in the motion data for example.

For the rotation it could be on increment 0.1° for one step on the mouse wheel.

**Comment by AdrianEddy** [comment]
in the dev build ( https://gyroflow.xyz/devbuild/ ) you can manipulate digits by using the Up/Down arrows while focusing on the digit you want to adjust, eg when focused on |1.234 you'll be changing the most significant digit, while when focusing on 1.23|4 you'll be changing the least significant digit. 
Other than that, you can drag the slider values while holding down the alt key, which will increase the slide resolution  by 10x.

I think this is enough options for fine-grained control

**Comment by hilmiyafia** [comment]
@AdrianEddy Thank you so much! 😊
