### ISSUE TITLE
export imu data as csv file

### ISSUE THREAD

**Issue by taomiao** [gyroflow/gyroflow#905]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I want to use pandas to process imu data. Gyroflow can read imu data from mp4 files, but there seems to be no option to export imu data.
![image](https://github.com/user-attachments/assets/51f8f9f3-ca63-40d4-b536-b45fdf40a0e9)

**Comment by AdrianEddy** [comment]
It's already there in the dev build https://gyroflow.xyz/devbuild
