### ISSUE TITLE
gyroflow CLI is not working on mac - cannot open video files. 

### ISSUE THREAD

**Issue by EmilRejman** [gyroflow/gyroflow#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

Gyroflow 1.5.4

### What operating system are you using?

Ventura 13.0.1

### What GPU are you using?

m1 8core gpu.

### What happened?

Gyroflow CLI on mac is not opening video files (both straight from memory card nor mac disc.)
Camera used DJI osmo action 5 pro.

command run:
```
./gyroflow /Users/<username_hidden>/Downloads/DJI_20241019160620_0227_D.MP4
```
(any preset, lens profiles, more videos etc any cli combination is not working. Cli is breaking on reading videofile ( 

outpur error:
```
15:44:17 [INFO] Videos: ["/Users/<username_hidden>/Downloads/DJI_20241019160620_0227_D.MP4"]
............
15:44:19 [INFO] start_accessing_url: file:///Users/<username_hidden>/Downloads/DJI_20241019160620_0227_D.MP4 - OPEN
15:44:19 [WARN] [add_file]: Unable to read the video file.
15:44:19 [ERROR] [a787bb46] Error: An error occured: Unable to read the video file.
```

the program is breaking in queue function, but i wasnt digging more, it should be here in inner function:
```
https://github.com/gyroflow/gyroflow/blob/master/src/cli.rs#L440-L442
```

gyroflow built for:
```
macOS110000/13.0.1 ARMv8 AArch64; AppleClang14.0.3 (clang-1403.0.22.14.1)GCC4.2.1; libc++15006; 10:04:15 Nov  1 2023
```

gyroflow:
```
gyroflow: [in main] Qt version: 6.6.0
Gyroflow 1.5.4
```

### Relevant log output

```shell
15:44:19 [INFO] start_accessing_url: file:///Users/<username_hidden>/Downloads/DJI_20241019160620_0227_D.MP4 - OPEN
15:44:19 [WARN] [add_file]: Unable to read the video file.
15:44:19 [ERROR] [a787bb46] Error: An error occured: Unable to read the video file.
```

**Comment by AdrianEddy** [comment]
If you want to use the CLI then you have to use the dmg version. Sandbox simply doesn't allow that. You can download the dmg from the downloads page
