### ISSUE TITLE
Colors export are different while using GPU encoding or not

### ISSUE THREAD

**Issue by tipaul426** [gyroflow/gyroflow#909]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

Windows version 22H 19045.5011

### What GPU are you using?

RX 5700 XT

### What happened?

Hi,
After the 1.6.0 update rendering is different if I use Enconding CPU or not.
If I export a footage with CPU encoding : 

Before : 
<img width="974" alt="2024-10-25_12h28_04" src="https://github.com/user-attachments/assets/6bed34e9-0308-4847-ae1a-5dec7a3b2998">

After :
<img width="1294" alt="2024-10-25_12h28_23" src="https://github.com/user-attachments/assets/73e48f3a-1590-434e-baaf-1bf232e47d81">

There will be no problem if without performance encoding it is a fast export but it's taking ages if you dont tick the parameter.
Do I need to untick something so even with CPU Encoding there is no colors changed between before and after ?

Already tried to reset to default settings but it's not better.

Summary : if I export without CPU encoding I have the original colors, if I do export with, colors are modified.
I tried to also reinstall my GPU but not better.
Didn't have that issue with the previous version.
Already reinstalled twice Gyroflow.

Im available if needed;

Paul

PS : camera parameter
<img width="253" alt="2024-10-25_12h35_19" src="https://github.com/user-attachments/assets/e7baa024-17b5-4e28-96e0-4a5807198784">

**Comment by AdrianEddy** [comment]
this looks like some LUT applied, are you sure you're checking correct files? It would be very weird because Gyroflow doesn't apply any color changes, and the only issue that could be related to this (color range) won't look like that for sure

**Comment by AdrianEddy** [comment]
I just tested with Avata 2 (D-LogM) and RTX 3080 Ti and no problem here. Looks like same parameters as yours
![image](https://github.com/user-attachments/assets/c2ef90a6-b5a1-496c-8747-1c43bc1bd735)

**Comment by tipaul426** [comment]
Hey, thanks for the answer, let me show it to you by video :
https://github.com/user-attachments/assets/716abcf2-9bd2-4eb1-b682-d06cff9649c6

Looks really weird, is there a way to rollback the version maybe to 15.0 to see if I can reproduce that ? 
I exported like 50+ video from my avata without having the issue

ty

**Comment by AdrianEddy** [comment]
ok, can you send me gyroflow.log file? it's in `%localappdata%/Gyroflow` (paste that in file explorer dir path)

**Comment by tipaul426** [comment]
here we go :
[gyroflow.log](https://github.com/user-attachments/files/17523147/gyroflow.log)

**Comment by AdrianEddy** [comment]
ok, can you please check this version and also send me gyroflow.log after rendering on this one?

https://github.com/gyroflow/gyroflow/actions/runs/11254703273/artifacts/2034788248

**Comment by tipaul426** [comment]
Same behavior :
[gyroflow.log](https://github.com/user-attachments/files/17523397/gyroflow.log)

i dont recall on which version I was before updating today ..
May it be a weird parameter ticked ?

**Comment by tipaul426** [comment]
just to let you know I tested some old footage that I had w/ same parameters on my avata with D-LOG M also, and yet the same issue is hapenning, so I dont think it's coming from the avata

**Comment by AdrianEddy** [comment]
interesting, that version was before a change which I thought could have influenced this. But since it's not, we need to find first version which broke. 

Please go to https://github.com/gyroflow/gyroflow/actions and start trying older and older versions until you find one that works. After clicking on a version, scroll down to Artifacts and then Gyroflow-windows. You can start from eg. # 2147, and then go lower like # 2122 and so on. The one I sent you in previous message was 2158

**Comment by tipaul426** [comment]
Hey,
Just tested out a bunch of version,
Looks like the issue is happening between version 2100 and 2101,
Export is ok on 2100 but not OK on 2101,

Let me know if you need more details, I will gladly help you ;)

**Comment by AdrianEddy** [comment]
ok so something changed in ffmpeg

can you try copying these files from 2100 to the latest one (2206)?
 ```
 avcodec-61.dll
 avdevice-61.dll
 avfilter-10.dll
 avformat-61.dll
 avutil-59.dll
 swresample-5.dll
 swscale-8.dll
 ```

**Comment by tipaul426** [comment]
I can confirm that version 2206 is working fine when you replace those dll thanks !

**Comment by AdrianEddy** [comment]
can you also send me a log from the latest version with these new files where it's working?

**Comment by AdrianEddy** [comment]
I suspect it's one of these commits to ffmpeg:
![image](https://github.com/user-attachments/assets/29c075f7-4e7f-4786-895b-ef17ad059144)

it's specific to AMD encoder

is the Avata video HDR?

**Comment by AdrianEddy** [comment]
Also, can you send me your original video file?

**Comment by tipaul426** [comment]
here are the logs :
[gyroflow.log](https://github.com/user-attachments/files/17524382/gyroflow.log)

Im filming in 4K/60fps with DLOG-M on, not sure if this is enabling HDR by default

**Comment by tipaul426** [comment]
> Also, can you send me your original video file?

Yep I can, but its 1GB size, where do you want me to upload it ? thanks

**Comment by AdrianEddy** [comment]
you can use wetransfer, google drive, dropbox, mega or swisstransfer

**Comment by tipaul426** [comment]
https://drive.google.com/file/d/1OFyV08QcJnrK8fNYCeQt2jTvW-Olt5Dw/view?usp=sharing

**Comment by AdrianEddy** [comment]
ok looks like I can reproduce, but the issue is in the metadata and depends actually on the player
In MPC-HC I see the original colors, but in Windows' Media Player, I see broken colors. Please try different players (eg. VLC, mpv, MPC-HC, some video editor like Resolve or Premiere if you have) and confirm

**Comment by tipaul426** [comment]
Okay, I used VLC > Broken colors
If I upload the video with the broken colors to an editor like Filmora or Capcut I have the same behavior

**Comment by tipaul426** [comment]
Tried Microsoft Clipchamp to see, I have the right colors so it really depends on the player

**Comment by AdrianEddy** [comment]
Ok this is clearly a bug in ffmpeg, I reported it [here](https://trac.ffmpeg.org/ticket/11269#ticket). I hope you don't mind if I used your sample video

**Comment by tipaul426** [comment]
Sure no problem !
Have a nice day

**Comment by tipaul426** [comment]
Should be fine now

**Comment by AdrianEddy** [comment]
could you try latest dev build? https://gyroflow.xyz/devbuild/

**Comment by tipaul426** [comment]
hey, can confirm that it's working fine now !
Thanks
