### ISSUE TITLE
Crash on Use Alpha, wrong Output size, no alpha on video in davinchi

### ISSUE THREAD

**Issue by AndriiShramko** [gyroflow/gyroflow#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

Windows 10 Pro 22h2

### What GPU are you using?

rtx 4090

### What happened?

https://youtu.be/stR-MaL_nD0?si=AiIeYrxLAaY7msP_ 
1. Davinchi crash when I remove check box Use Alpha.
2. Alpha on stabilized video not active. It is not transparent. How to make it transparent.
3. Outputs size always change to unnecessary value after I open 8/7 GoPro video from Davinchi in gyroflow.

**Comment by AdrianEddy** [comment]
Fixed in latest plugin from https://gyroflow.xyz/devbuild/

for transparent background, just set "transparent" as background color in the app (and in your preset or project)
