### ISSUE TITLE
OpenFX install permission denied

### ISSUE THREAD

**Issue by VBK7** [gyroflow/gyroflow#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

v1.6.0

### What operating system are you using?

macOS Sequoia Version 15.1 (24B83)

### What GPU are you using?

AMD Radeon Pro 5500M 8 GB

### What happened?

When I try to install the OpenFX plug-in through the Gyroflow application, I get the following message:
<img width="1436" alt="Screenshot 2024-11-05 at 2 22 09 PM" src="https://github.com/user-attachments/assets/5ecf1b61-e8fa-4dac-a6d3-c9344d3161d8">

**Comment by AdrianEddy** [comment]
already fixed in the dev build https://gyroflow.xyz/devbuild/
