### ISSUE TITLE
[Bug]: Firefly x lite CSV file unsupported

### ISSUE THREAD

**Issue by Jrham08** [gyroflow/gyroflow#92]
### Gyroflow version

1.0.0rc

### What operating system are you using?

Windows 10

### What GPU are you using?

AMD Vega 56

### What happened?

Using Firefly x lite 4k , Gyroflow allows me to select my media and my lens profile but as soon as I try to apply my motion date with a csv file I receive an error unsupported file format.
[144055AA.CSV](https://github.com/gyroflow/gyroflow/files/8008967/144055AA.CSV)
![Capture gyroflow](https://user-images.githubusercontent.com/99099443/152659980-e7d8f6c2-0d6c-4aba-8f2f-2e480fac6d8b.JPG)

**Comment by ElvinC** [comment]
This is fixed with https://github.com/AdrianEddy/telemetry-parser/pull/9
Note that the firefly gyro data has been shown to contain gaps in the gyro data, so your results may vary.

**Comment by MarkfpvMark** [comment]
Hi! thanks! how can i install this update in gyoflow?

**Comment by ElvinC** [comment]
Automated builds are in the `Actions` page. Direct link to latest one: https://github.com/gyroflow/gyroflow/suites/5196621997/artifacts/158496425
