### ISSUE TITLE
Linux AppImage is missing libstdc++

### ISSUE THREAD

**Issue by hansfbaier** [gyroflow/gyroflow#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

v1.6.0 AppImage release

### What operating system are you using?

Ubuntu 22.04.5 LTS 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC

### What GPU are you using?

NVIDIA GeForce RTX 2060 SUPER

### What happened?

The AppImage seems to be missing libstdc++.so (see log).
A previous version of the AppImage worked fine.

### Relevant log output

```shell
jack@familie-desktop:~$ /opt/Gyroflow-linux64.AppImage 
/tmp/.mount_GyroflxRaKgy//gyroflow: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

**Comment by AdrianEddy** [comment]
Fixed in 373dd2bcaf4c5a16ec5e450d40a4f7adf732cb4a
Download from https://gyroflow.xyz/devbuild/
