### ISSUE TITLE
Build iOS release issue

### ISSUE THREAD

**Issue by bias123456** [gyroflow/gyroflow#926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

a76cabda

### What operating system are you using?

MacOS 14.4.1 (23E224), Apple M1

### What happened?

I encountered an issue while compiling the project to iOS release, which seems to be an error of not being able to link to the QT library. 

"ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)", 

I cannot find the reason or solution. Could you provide some guidance or solution. The [attachment]
[error_log.txt](https://github.com/user-attachments/files/17771528/error_log.txt)
 is the content of the full log on my Mac mini (MacOS 14.4.1 (23E224), Apple M1 ) . Thanks

bbiasxie@BBiasdeMac-mini gyroflow % just ios run
just -f _scripts/ios.just run
   Compiling proc-macro2 v1.0.89
   Compiling unicode-ident v1.0.13
   Compiling libc v0.2.161
   Compiling autocfg v1.4.0
   Compiling shlex v1.3.0
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling regex-syntax v0.8.5
   Compiling serde v1.0.214
   Compiling glob v0.3.1
   Compiling num-traits v0.2.19
   Compiling aho-corasick v1.1.3
   Compiling clang-sys v1.8.1
   Compiling quote v1.0.37
   Compiling syn v2.0.87
   Compiling jobserver v0.1.32
   Compiling regex-automata v0.4.8
   Compiling paste v1.0.15
   Compiling cc v1.1.35
   Compiling byteorder v1.5.0
   Compiling libloading v0.8.5
   Compiling stable_deref_trait v1.2.0
   Compiling bytemuck v1.19.0
   Compiling log v0.4.22
   Compiling either v1.13.0
   Compiling num-integer v0.1.46
   Compiling semver v1.0.23
   Compiling itertools v0.13.0
   Compiling smallvec v1.13.2
   Compiling num-bigint v0.4.6
   Compiling getrandom v0.2.15
   Compiling matrixmultiply v0.3.9
   Compiling writeable v0.5.5
   Compiling ring v0.17.8
   Compiling core-foundation-sys v0.8.7
   Compiling litemap v0.7.3
   Compiling lazy_static v1.5.0
   Compiling regex v1.11.1
   Compiling safe_arch v0.7.2
   Compiling minimal-lexical v0.2.1
   Compiling rawpointer v0.2.1
   Compiling thiserror v1.0.68
   Compiling nom v7.1.3
   Compiling num-rational v0.4.2
   Compiling wide v0.7.28
   Compiling approx v0.5.1
   Compiling synstructure v0.13.1
   Compiling cpp_common v0.5.9
   Compiling percent-encoding v2.3.1
   Compiling icu_locid_transform_data v1.5.0
   Compiling bindgen v0.70.1
   Compiling typenum v1.17.0
   Compiling cfg_aliases v0.1.1
   Compiling cexpr v0.6.0
   Compiling allocator-api2 v0.2.18
   Compiling bitflags v2.6.0
   Compiling rustls v0.23.16
   Compiling equivalent v1.0.1
   Compiling unicode-xid v0.2.6
   Compiling foldhash v0.1.3
   Compiling once_cell v1.20.2
   Compiling icu_properties_data v1.5.0
   Compiling serde_derive v1.0.214
   Compiling zerofrom-derive v0.1.4
   Compiling yoke-derive v0.7.4
   Compiling zerovec-derive v0.10.3
   Compiling displaydoc v0.2.5
   Compiling icu_provider_macros v1.5.0
   Compiling zerocopy-derive v0.7.35
   Compiling thiserror-impl v1.0.68
   Compiling rustc-hash v1.1.0
   Compiling zerocopy v0.7.35
   Compiling hashbrown v0.15.1
   Compiling cpp_build v0.5.9
   Compiling zerofrom v0.1.4
   Compiling yoke v0.7.4
   Compiling version_check v0.9.5
   Compiling write16 v1.0.0
   Compiling syn v1.0.109
   Compiling bitflags v1.3.2
   Compiling utf16_iter v1.0.5
   Compiling zerovec v0.10.4
   Compiling utf8_iter v1.0.4
   Compiling anyhow v1.0.92
   Compiling icu_normalizer_data v1.5.0
   Compiling crossbeam-utils v0.8.20
   Compiling spin v0.9.8
   Compiling rustls-pki-types v1.10.0
   Compiling untrusted v0.9.0
   Compiling tinystr v0.7.6
   Compiling icu_collections v1.5.0
   Compiling icu_locid v1.5.0
   Compiling indexmap v2.6.0
   Compiling icu_provider v1.5.0
   Compiling malloc_buf v0.0.6
   Compiling pkg-config v0.3.31
   Compiling icu_locid_transform v1.5.0
   Compiling adler2 v2.0.0
   Compiling libm v0.2.11
   Compiling miniz_oxide v0.8.0
   Compiling icu_properties v1.5.1
   Compiling num-complex v0.4.6
   Compiling objc v0.2.7
   Compiling form_urlencoded v1.2.1
   Compiling rand_core v0.6.4
   Compiling lock_api v0.4.12
   Compiling crc32fast v1.4.2
   Compiling unicode-width v0.1.14
   Compiling icu_normalizer v1.5.0
   Compiling zeroize v1.8.1
   Compiling subtle v2.6.1
   Compiling parking_lot_core v0.9.10
   Compiling flate2 v1.0.34
   Compiling crossbeam-epoch v0.9.18
   Compiling idna_adapter v1.2.0
   Compiling idna v1.0.3
   Compiling webpki-roots v0.26.6
   Compiling ahash v0.8.11
   Compiling qttypes v0.2.12 (https://github.com/AdrianEddy/qmetaobject-rs.git?rev=ff1e23d#ff1e23dc)
   Compiling url v2.5.3
   Compiling core-foundation v0.9.4
   Compiling rayon-core v1.12.1
   Compiling scopeguard v1.2.0
   Compiling itoa v1.0.11
   Compiling termcolor v1.4.1
   Compiling base64 v0.22.1
   Compiling simba v0.8.1
   Compiling crossbeam-deque v0.8.5
   Compiling simba v0.7.3
   Compiling ppv-lite86 v0.2.20
   Compiling foreign-types-macros v0.2.3
   Compiling nalgebra-macros v0.2.2
   Compiling naga v23.0.0
   Compiling block v0.1.6
   Compiling doc-comment v0.3.3
   Compiling sample-consensus v1.0.2
   Compiling fixedbitset v0.4.2
   Compiling foreign-types-shared v0.3.1
   Compiling convert_case v0.4.0
   Compiling arrayvec v0.7.6
   Compiling bit-vec v0.8.0
   Compiling derive_more v0.99.18
   Compiling bit-set v0.8.0
   Compiling foreign-types v0.5.0
   Compiling petgraph v0.6.5
   Compiling rand_chacha v0.3.1
   Compiling parking_lot v0.12.3
   Compiling codespan-reporting v0.11.1
   Compiling core-graphics-types v0.1.3
   Compiling nalgebra v0.30.1
   Compiling nalgebra v0.32.6
   Compiling coreaudio-sys v0.2.16
   Compiling spirv v0.3.0+sdk-1.3.268.0
   Compiling wgpu-hal v23.0.0
   Compiling clang v2.0.0
   Compiling num_cpus v1.16.0
   Compiling dunce v1.0.5
   Compiling hexf-parse v0.2.1
   Compiling ryu v1.0.18
   Compiling hamming v0.1.3
   Compiling primal-bit v0.3.2
   Compiling opencv-binding-generator v0.92.0
   Compiling ffmpeg-sys-next v7.1.0
   Compiling metal v0.29.0
   Compiling hashbrown v0.13.2
   Compiling rand v0.8.5
   Compiling argh_shared v0.1.12
   Compiling cpp_macros v0.5.9
   Compiling wgpu-types v23.0.0
   Compiling rustls-webpki v0.102.8
   Compiling cv-core v0.15.0 (https://github.com/rust-cv/cv.git?rev=82a25ee#82a25ee3)
   Compiling wgpu-core v23.0.0
   Compiling iana-time-zone v0.1.61
   Compiling libmimalloc-sys v0.1.39
   Compiling primal-check v0.3.4
   Compiling half v2.4.1
   Compiling static_assertions v1.1.0
   Compiling color_quant v1.1.0
   Compiling rustix v0.38.39
   Compiling profiling v1.0.16
   Compiling serde_json v1.0.132
   Compiling primal-estimate v0.3.3
   Compiling float-ord v0.3.2
   Compiling time-core v0.1.2
   Compiling litrs v0.4.1
   Compiling raw-window-handle v0.6.2
   Compiling powerfmt v0.2.0
   Compiling vcpkg v0.2.15
   Compiling num-conv v0.1.0
   Compiling libm v0.1.4
   Compiling spirv-std-types v0.9.0 (https://github.com/EmbarkStudios/rust-gpu?rev=54f6978#54f6978c)
   Compiling spirv-std-macros v0.9.0 (https://github.com/EmbarkStudios/rust-gpu?rev=54f6978#54f6978c)
   Compiling document-features v0.2.10
   Compiling opencv v0.93.3
   Compiling time-macros v0.2.18
   Compiling deranged v0.3.11
   Compiling primal-sieve v0.3.7
   Compiling ureq v2.10.1
   Compiling image v0.24.9
   Compiling chrono v0.4.38
   Compiling cpp v0.5.9
   Compiling argmin-math v0.4.0
   Compiling argh_derive v0.1.12
   Compiling space v0.17.0
   Compiling fallible_collections v0.4.9
   Compiling prost-derive v0.13.3
   Compiling rayon v1.10.0
   Compiling itertools v0.10.5
   Compiling rand_xoshiro v0.6.0
   Compiling ndarray v0.15.6
   Compiling toml v0.5.11
   Compiling rustfft v6.2.0
   Compiling qmetaobject v0.2.10 (https://github.com/AdrianEddy/qmetaobject-rs.git?rev=ff1e23d#ff1e23dc)
   Compiling csv-core v0.1.11
   Compiling wgpu v23.0.0
   Compiling num_threads v0.1.7
   Compiling errno v0.3.9
   Compiling filetime v0.2.25
   Compiling bitreader v0.3.11
   Compiling instant v0.1.13
   Compiling cpal v0.15.3
   Compiling bytes v1.8.0
   Compiling ash v0.38.0+1.3.281
   Compiling strength_reduce v0.2.4
   Compiling simd-adler32 v0.3.7
   Compiling telemetry-parser v0.3.0 (https://github.com/AdrianEddy/telemetry-parser.git?rev=8500bb3#8500bb3e)
   Compiling same-file v1.0.6
   Compiling glam v0.25.0
   Compiling integer-encoding v3.0.4
   Compiling ciborium-io v0.2.2
   Compiling tinyvec_macros v0.1.1
   Compiling portable-atomic v1.9.0
   Compiling unsafe-libyaml v0.2.11
   Compiling gimli v0.31.1
   Compiling serde_yaml v0.9.34+deprecated
   Compiling spirv-std v0.9.0 (https://github.com/EmbarkStudios/rust-gpu?rev=54f6978#54f6978c)
   Compiling addr2line v0.24.2
   Compiling tinyvec v1.8.0
   Compiling ciborium-ll v0.2.2
   Compiling time v0.3.36
   Compiling fc-blackbox v0.2.0 (https://github.com/ilya-epifanov/fc-blackbox.git?rev=de08350#de08350b)
   Compiling walkdir v2.5.0
   Compiling nshare v0.9.0 (https://github.com/rust-cv/nshare.git?rev=cd4a5c007ecf4ef62c938a6ac64fd90edf895360#cd4a5c00)
   Compiling zune-inflate v0.2.54
   Compiling transpose v0.2.3
   Compiling prost v0.13.3
   Compiling argmin v0.10.0
   Compiling mp4parse v0.17.0 (https://github.com/AdrianEddy/mp4parse-rust.git#2f1b4a5a)
   Compiling winres v0.1.12
   Compiling csv v1.3.0
   Compiling argh v0.1.12
   Compiling enum_delegate_lib v0.2.0
   Compiling coreaudio-rs v0.11.3
   Compiling bitarray v0.9.3
   Compiling qml-video-rs v0.1.0 (https://github.com/AdrianEddy/qml-video-rs.git?rev=2a3bd8b#2a3bd8ba)
   Compiling gyroflow-core v1.6.0 (/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/src/core)
   Compiling primal v0.3.3
   Compiling cv-pinhole v0.6.0 (https://github.com/rust-cv/cv.git?rev=82a25ee#82a25ee3)
   Compiling qmetaobject_impl v0.2.10 (https://github.com/AdrianEddy/qmetaobject-rs.git?rev=ff1e23d#ff1e23dc)
   Compiling objc_id v0.1.1
   Compiling object v0.36.5
   Compiling num-iter v0.1.45
   Compiling topology-traits v0.1.2
   Compiling ogg v0.8.0
   Compiling mach2 v0.4.2
   Compiling bit_field v0.10.2
   Compiling superslice v1.0.0
   Compiling pretty-hex v0.4.1
   Compiling human-sort v0.2.2
   Compiling futures-core v0.3.31
   Compiling lebe v0.5.2
   Compiling rustc-demangle v0.1.24
   Compiling keep-awake v0.1.0 (https://github.com/AdrianEddy/keep-awake-rs.git?rev=04ce779#04ce7791)
   Compiling dasp_sample v0.11.0
   Compiling assert_float_eq v1.1.3
   Compiling ffmpeg-next v7.1.0
   Compiling xdg v2.5.2
   Compiling app_dirs2 v2.5.5 (https://github.com/app-dirs-rs/app_dirs2.git#1137ee05)
   Compiling enterpolation v0.2.1
   Compiling exr v1.73.0
   Compiling futures-intrusive v0.5.0
   Compiling backtrace v0.3.74
   Compiling rs-sync v0.1.0 (https://github.com/gyroflow/rs-sync.git?rev=0d22978#0d229781)
   Compiling lewton v0.10.2
   Compiling num v0.4.3
   Compiling objc-foundation v0.1.1
   Compiling biquad v0.4.2
   Compiling eight-point v0.8.0 (https://github.com/rust-cv/cv.git?rev=82a25ee#82a25ee3)
   Compiling akaze v0.7.0 (https://github.com/rust-cv/cv.git?rev=82a25ee#82a25ee3)
   Compiling enum_delegate v0.2.0
   Compiling mimalloc v0.1.43
   Compiling gyroflow v1.6.0 (/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow)
   Compiling xattr v1.3.1
   Compiling ciborium v0.2.2
   Compiling stabilize_spirv v0.0.0 (/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/src/core/gpu/stabilize_spirv)
   Compiling filetime_creation v0.2.0
   Compiling ahrs v0.6.0 (https://github.com/jmagnuson/ahrs-rs.git?rev=bf7b41d#bf7b41d0)
   Compiling console v0.15.8
   Compiling arrsac v0.10.0
   Compiling bincode v1.3.3
   Compiling lru v0.12.5
   Compiling line_drawing v1.0.0
   Compiling cstr v0.2.12
   Compiling simple-easing v1.0.1
   Compiling whoami v1.5.2
   Compiling fastrand v2.1.1
   Compiling base91 v0.1.0
   Compiling urlencoding v2.1.3
   Compiling number_prefix v0.4.0
   Compiling dispatch v0.2.0
   Compiling pollster v0.4.0
   Compiling dyn-clone v1.0.17
   Compiling indicatif v0.17.8
   Compiling mp4-merge v0.1.10
   Compiling tar v0.4.43
   Compiling rodio v0.19.0
   Compiling log-panics v2.1.0
   Compiling simplelog v0.12.2
warning: variable does not need to be mutable
   --> src/core/calibration/mod.rs:180:45
    |
180 | ...                   if let Some(mut pt2) = digital.undistort_point((pt.x,  pt.y), &kernel_params) {
    |                                   ----^^^
    |                                   |
    |                                   help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: unused variable: `digital`
   --> src/core/calibration/mod.rs:218:21
    |
218 |         if let Some(digital) = self.digital_lens.as_ref().map(|x| DistortionModel::from_name(&x)) {
    |                     ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_digital`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
   --> src/core/calibration/mod.rs:217:13
    |
217 |         let mut width = self.width as i32;
    |             ----^^^^^
    |             |
    |             help: remove this `mut`

warning: unused variable: `distortion_model`
  --> src/core/stabilization/cpu_undistort.rs:91:98
   |
91 |     pub fn undistort_image_cpu_spirv<T: PixelType>(buffers: &mut Buffers, params: &KernelParams, distortion_model: &DistortionModel, digital_lens: Option<&DistortionModel>, matrices: &[[f32; 14]], drawing: &[u8]) -> bool {
   |                                                                                                  ^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_distortion_model`

warning: unused variable: `digital_lens`
  --> src/core/stabilization/cpu_undistort.rs:91:134
   |
91 |     pub fn undistort_image_cpu_spirv<T: PixelType>(buffers: &mut Buffers, params: &KernelParams, distortion_model: &DistortionModel, digital_lens: Option<&DistortionModel>, matrices: &[[f32; 14]], drawing: &[u8]) -> bool {
   |                                                                                                                                      ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_digital_lens`

warning: `gyroflow-core` (lib) generated 5 warnings (run `cargo fix --lib -p gyroflow-core` to apply 2 suggestions)
warning: unused variable: `command`
    --> src/controller.rs:2332:27
     |
2332 |     fn nle_plugins(&self, command: QString, typ: QString) -> QString {
     |                           ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_command`
     |
     = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `typ`
    --> src/controller.rs:2332:45
     |
2332 |     fn nle_plugins(&self, command: QString, typ: QString) -> QString {
     |                                             ^^^ help: if this is intentional, prefix it with an underscore: `_typ`

error: linking with `cc` failed: exit status: 1
  |
  = note: env -u MACOSX_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/bbiasxie/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/bbiasxie/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/bbiasxie/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/_scripts/..//ext/6.7.3/ios/bin:/usr/libexec/:/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/_scripts/..//ext//6.7.3/macos/bin:/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/_scripts/..//ext/ffmpeg-arm64/bin:/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/_scripts/..//ext/ffmpeg-
……

  = note: ld: warning: ignoring duplicate libraries: '-lSystem', '-lc++'
          ld: warning: alignment (1) of atom 'anon-34' from '/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/ext/ffmpeg-7.1-iOS-gpl-lite/lib/libavfilter.a[47](vsrc_testsrc.o)' is too small and may result in unaligned pointers 
          ld: warning: alignment (1) of atom 'anon-6' from '/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/ext/ffmpeg-7.1-iOS-gpl-lite/lib/libavfilter.a[46](vsink_nullsink.o)' is too small and may result in unaligned pointers 
          ld: warning: alignment (1) of atom 'anon-12' from '/Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/ext/ffmpeg-7.1-iOS-gpl-lite/lib/libavfilter.a[45](video.o)' is too small and may result in unaligned pointers 
          ……          

          Undefined symbols for architecture arm64:
            "qt_static_plugin_QSvgPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QJpegPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQmlPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QSvgIconPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuick2Plugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QmlShapesPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQmlMetaPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQmlModelsPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickDialogsPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickEffectsPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickLayoutsPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuick_WindowPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QIOSIntegrationPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickControls2Plugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QSecureTransportBackend()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQmlWorkerScriptPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickTemplates2Plugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickControls2ImplPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickControls2BasicStylePlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickControls2MaterialStylePlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QtQuickControls2BasicStyleImplPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qRegisterNormalizedMetaType_QNetworkReply__NetworkError(QByteArray const&)", referenced from:
                QMetaTypeId<QNetworkReply::NetworkError>::qt_metatype_id() in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QMetaTypeId<QNetworkReply::NetworkError>::qt_metatype_id() in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
            "qt_static_plugin_QtQuickControls2MaterialStyleImplPlugin()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "qt_static_plugin_QSCNetworkReachabilityNetworkInformationBackendFactory()", referenced from:
                __GLOBAL__sub_I_qml_plugins.cpp in 0bcc199e7a9fe996-qml_plugins.o
            "QNetworkReply::staticMetaObject", referenced from:
                QtPrivate::MetaObjectForType<QNetworkReply*, void>::metaObjectFunction(QtPrivate::QMetaTypeInterface const*) in libQt6Qml.a[arm64][208](qqmltypeloadernetworkreplyproxy.cpp.o)
                QMetaTypeIdQObject<QNetworkReply*, 8>::qt_metatype_id() in libQt6Qml.a[arm64][208](qqmltypeloadernetworkreplyproxy.cpp.o)
                QQmlXMLHttpRequest::error(QNetworkReply::NetworkError) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::error(QNetworkReply::NetworkError) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::error(QNetworkReply::NetworkError) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QtPrivate::MetaObjectForType<QNetworkReply::NetworkError, void>::metaObjectFunction(QtPrivate::QMetaTypeInterface const*) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QtPrivate::QDebugStreamOperatorForType<QNetworkReply::NetworkError, true>::debugStream(QtPrivate::QMetaTypeInterface const*, QDebug&, void const*) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                ...
            "QQmlIntForeign::staticMetaObject", referenced from:
                qml_register_types_QML() in libQt6Qml.a[arm64][204](qmlbuiltins_qmltyperegistrations.cpp.o)
            "QQmlUrlForeign::staticMetaObject", referenced from:
                qml_register_types_QML() in libQt6Qml.a[arm64][204](qmlbuiltins_qmltyperegistrations.cpp.o)
            "QQmlVarForeign::staticMetaObject", referenced from:
                QJSValue::isVariant() const in libQt6Qml.a[arm64][42](qjsvalue.cpp.o)
                qml_register_types_QML() in libQt6Qml.a[arm64][204](qmlbuiltins_qmltyperegistrations.cpp.o)
                QtPrivate::MetaObjectForType<QQmlVarForeign, void>::metaObjectFunction(QtPrivate::QMetaTypeInterface const*) in libQt6Qml.a[arm64][204](qmlbuiltins_qmltyperegistrations.cpp.o)
                QtPrivate::QMetaTypeForType<QQmlVarForeign>::getLegacyRegister()::'lambda'()::__invoke() in libQt6Qml.a[arm64][204](qmlbuiltins_qmltyperegistrations.cpp.o)
            "QNetworkRequest::setAttribute(QNetworkRequest::Attribute, QVariant const&)", referenced from:
                QQmlXMLHttpRequest::open(QV4::Object*, QString const&, QUrl const&, QQmlXMLHttpRequest::LoadType) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::requestFromUrl(QUrl const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
            "QNetworkRequest::setRawHeader(QByteArray const&, QByteArray const&)", referenced from:
                QQmlXMLHttpRequest::addHeader(QString const&, QString const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::addHeader(QString const&, QString const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
            "QNetworkRequest::setUrl(QUrl const&)", referenced from:
                QV4Include::QV4Include(QUrl const&, QV4::ExecutionEngine*, QV4::QmlContext*, QV4::Value const&) in libQt6Qml.a[arm64][68](qv4include.cpp.o)
                QQmlXMLHttpRequest::requestFromUrl(QUrl const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
            "QNetworkRequest::setHeader(QNetworkRequest::KnownHeaders, QVariant const&)", referenced from:
                QQmlXMLHttpRequest::requestFromUrl(QUrl const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::requestFromUrl(QUrl const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
            "QNetworkRequest::QNetworkRequest(QUrl const&)", referenced from:
                QQmlTypeLoader::loadThread(QQmlRefPointer<QQmlDataBlob> const&) in libQt6Qml.a[arm64][182](qqmltypeloader.cpp.o)
                QQmlTypeLoader::networkReplyFinished(QNetworkReply*) in libQt6Qml.a[arm64][182](qqmltypeloader.cpp.o)
            "QNetworkRequest::QNetworkRequest(QNetworkRequest const&)", referenced from:
                QQmlXMLHttpRequest::requestFromUrl(QUrl const&) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
            "QNetworkRequest::QNetworkRequest()", referenced from:
                QV4Include::QV4Include(QUrl const&, QV4::ExecutionEngine*, QV4::QmlContext*, QV4::Value const&) in libQt6Qml.a[arm64][68](qv4include.cpp.o)
                QQmlXMLHttpRequest::QQmlXMLHttpRequest(QNetworkAccessManager*, QV4::ExecutionEngine*) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::error(QNetworkReply::NetworkError) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)
                QQmlXMLHttpRequest::abort(QV4::Object*) in libQt6Qml.a[arm64][228](qqmlxmlhttprequest.cpp.o)

                ......
            
            "_png_write_info", referenced from:
                QPNGImageWriter::writeImage(QImage const&, int, QString const&, int, int) in libQt6Gui.a[arm64][216](qpnghandler.cpp.o)
            "_png_write_rows", referenced from:
                QPNGImageWriter::writeImage(QImage const&, int, QString const&, int, int) in libQt6Gui.a[arm64][216](qpnghandler.cpp.o)
                QPNGImageWriter::writeImage(QImage const&, int, QString const&, int, int) in libQt6Gui.a[arm64][216](qpnghandler.cpp.o)
            "_qt_main_wrapper", referenced from:
                <initial-undefines>
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

warning: `gyroflow` (bin "gyroflow") generated 2 warnings
error: could not compile `gyroflow` (bin "gyroflow") due to 1 previous error; 2 warnings emitted
error: Recipe `build-and-package` failed with exit code 101
[....] Waiting for iOS device to be connected
[....] Using d24b15f7168c321105e0bc9bc9b753a58eaa015f (D22AP, iPhone X, iphoneos, arm64, 15.4.1, 19E258) a.k.a. 'iPhone-biasTest'.
------ Install phase ------
[  0%] Found d24b15f7168c321105e0bc9bc9b753a58eaa015f (D22AP, iPhone X, iphoneos, arm64, 15.4.1, 19E258) a.k.a. 'iPhone-biasTest' connected through USB, beginning install
[  0%] Copying /Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/_scripts/..//_deployment/_binaries/ios/Payload/Gyroflow.app/META-INF/ to device
[  0%] Copying /Users/bbiasxie/Documents/TestProject/test_gyroflow/gyroflow/_scripts/..//_deployment/_binaries/ios/Payload/Gyroflow.app/META-INF/com.apple.ZipMetadata.plist to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
2024-11-15 10:51:50.294 ios-deploy[28811:618699] [ !! ] Error 0xe8000051: Could not inspect the application package. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
error: Recipe `run` failed with exit code 253
error: Recipe `ios` failed on line 39 with exit code 253
[error_log.txt](https://github.com/user-attachments/files/17771960/error_log.txt)

**Comment by AdrianEddy** [comment]
I'm not sure why you're seeing these errors, running `just ios install-deps` and `just ios deploy` should just work, it works fine in CI

run `cargo clean`, delete the `ext` directory and start again, make sure to call  `just ios install-deps` and `just ios deploy`

**Comment by bias123456** [comment]
> I'm not sure why you're seeing these errors, running `just ios install-deps` and `just ios deploy` should just work, it works fine in CI
> 
> run `cargo clean`, delete the `ext` directory and start again, make sure to call `just ios install-deps` and `just ios deploy`

In addition running `just ios install-deps` and `just ios deploy`,  do I still need to install  QT environment independently?

**Comment by AdrianEddy** [comment]
No

**Comment by bias123456** [comment]
Hi, AdrianEddy,

My MacBook is Apple M1 chip with arm64 architecture,  do I need to do some additional configuration? Thanks

**Comment by AdrianEddy** [comment]
it should work on M1, you just need to have XCode and iOS platform installed and everything else should be handled  by the script
BTW, why are you compiling iOS version yourself?
