### ISSUE TITLE
Can't read the gyrodata exported by gyroflow itself

### ISSUE THREAD

**Issue by YukiChoco** [gyroflow/gyroflow#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

Window11 23H2

### What happened?

![image](https://github.com/user-attachments/assets/b5e15b07-491e-4b0d-8b04-7ab1ebb9b896)

![image](https://github.com/user-attachments/assets/3f4026cf-88d4-41c7-be2e-838f8408cc7d)

it seems that gyroflow has some problem to read the .csv/.json file exported by itself.
I have tryed all the 3 methods. my camera is DJI Action4.

**Comment by AdrianEddy** [comment]
It's not supposed to. Why are you doing this?
Export project file instead
