### ISSUE TITLE
Use tmp file while writing data

### ISSUE THREAD

**Issue by hamishfagg** [gyroflow/gyroflow#929]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

It'd be great to have an option for gyroflow to write to `<filename>.tmp` and then rename to `<filename>` once processing is complete.

I'm using the `--watch` CLI option in a docker container, and its hard to know when processing is complete so the output file can be used.
Thank you for providing the CLI options!

**Comment by AdrianEddy** [comment]
Done in 10612ea
