### ISSUE TITLE
[Bug]: ffmpeg Error CUDA ERROR 

### ISSUE THREAD

**Issue by KwadLife** [gyroflow/gyroflow#93]
### Gyroflow version

1.0.0

### What operating system are you using?

Windows 10

### What GPU are you using?

Nvidia geforce GTX 1060

### What happened?

Trying to export GoPro Hero 6 Footage.
The internal IMU stabilization didn't work from beginning so it was pretty shaky. Auto Sync on 5 Point solved it somehow but on export with GPU enabled this error occured... Other clips have worked good so far on GPU render.
![Error](https://user-images.githubusercontent.com/44123988/152660447-cf6feed7-cafe-4eb4-aa9f-6aac24dedbef.PNG)
![Gyroflow_FlipiFloppiSettings](https://user-images.githubusercontent.com/44123988/152660451-0d4206b8-4144-475b-8d97-abb8199b8784.PNG)

**Comment by AdrianEddy** [comment]
Please test this one and report back: https://github.com/gyroflow/gyroflow/suites/5205488855/artifacts/159064470

**Comment by KwadLife** [comment]
fixed
