### ISSUE TITLE
iOS profile error

### ISSUE THREAD

**Issue by JunWeiAndroid** [gyroflow/gyroflow#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

a76cabd

### What operating system are you using?

macOS Ventura 13.3

### What happened?

when I run `just ios debug`, some errors have occurred.
![image](https://github.com/user-attachments/assets/afeaad63-6cc8-4aa8-a202-0cb2162f7884)
![image](https://github.com/user-attachments/assets/14c58e9f-6202-4590-9eee-4df94fff23a8)
![image](https://github.com/user-attachments/assets/efd897a9-631e-4795-86a8-b85208887248)
![image](https://github.com/user-attachments/assets/c814777a-c6c8-4812-9387-16c62285511e)

**Comment by JunWeiAndroid** [comment]
@AdrianEddy 
I have placed my own profile file in the designated directory, `DevelopmentCertificateSHA` and `DevelopmentProvision`have been set up, but it's not work. Please help me check if there are any errors in the settings. Thank you.
![image](https://github.com/user-attachments/assets/45b7f973-3901-4f9a-a0e7-b4db09be88fc)
![image](https://github.com/user-attachments/assets/0b6baf3f-c9d5-44f4-a96b-1021856935da)

**Comment by AdrianEddy** [comment]
what's the error?
