### ISSUE TITLE
fail to install dependencies in Windows

### ISSUE THREAD

**Issue by SquabPigeon** [gyroflow/gyroflow#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

Windows

### What happened?

I encountered an issue while following the instructions on GitHub for compiling the source code on Windows. During the fourth step, "Install dependencies: just install-deps," I encountered the following error. I have already reviewed previous issues but have not been able to resolve it. Therefore, I am raising this issue to seek assistance.

######error information######
At C:\Users\AppData\Local\Temp\just-AlWAvZ\install-deps.ps1:77 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

error: Recipe `install-deps` failed with exit code 1
error: Recipe `install-deps` failed on line 27 with exit code 1

**Comment by AdrianEddy** [comment]
Delete everything from `C:\Users\AppData\Local\Temp\` and try again
