### ISSUE TITLE
[Bug]: Lens Profile Name is not generated properly with filled in camera details if user does not confirm manually

### ISSUE THREAD

**Issue by b14ckyy** [gyroflow/gyroflow#94]
### Gyroflow version

1.0.0-rc1

### What operating system are you using?

Windows 11 - 22000.438

### What GPU are you using?

Core i7 7700K + GTX 1080ti

### What happened?

![image](https://user-images.githubusercontent.com/33039058/152660523-e0ae07fa-bd44-4ca9-adbb-2f2e561629f0.png)

as seen in the screenshot, if the user misses to hit enter after filling in the camera detail fields, the data are not saved and included in the file name.

**Comment by AdrianEddy** [comment]
Fixed in d7b0cb20fba5e85f2bd73fccd57552cb42a8b8f1
