### ISSUE TITLE
GPU accelerated encoder doesn't support this pixel format (YUV422P10LE)

### ISSUE THREAD

**Issue by IRyzoI** [gyroflow/gyroflow#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

macOS Sequoia 15.1

### What happened?

I get this error message when I try to output and speed is sometimes 11fps, sometimes 1. Is there a best choice codec and is there a way to assign that one to choose every time without having to manually choose upon every export?
<img width="724" alt="Screenshot 2024-12-23 at 12 43 40 AM" src="https://github.com/user-attachments/assets/d9e16dc9-0396-4ece-bce3-3db9b3cb2944" />

**Comment by AdrianEddy** [comment]
that happens when the gpu decoder fails and gyroflow has to fallback to software decoding. The one that's highlighted is the best match
